### ISSUE TITLE
RuntimeError when using radius_graph

### ISSUE THREAD

**Issue by mkumaszka** [rusty1s/pytorch_geometric#1060]
Hi,
while calculating edge_index for ShapeNet with radius_graph function I encounter an error:
`Traceback (most recent call last):
  File "/home/martyna/PycharmProjects/jaw_3d/src/experiments/scripts/modelnet_meshsnet_small.py", line 44, in <module>
    train_step(model, train_loader, device, optimizer, batch_size, N, classes)
  File "/home/martyna/PycharmProjects/jaw_3d/src/learning/train.py", line 14, in train_step
    out = model(data)
  File "/home/martyna/miniconda3/envs/teeth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/martyna/PycharmProjects/jaw_3d/src/models/meshsnet.py", line 148, in forward
    edge_index_lg = radius_graph(x, r=self.r_large, batch=batch)
  File "/home/martyna/miniconda3/envs/teeth/lib/python3.7/site-packages/torch_geometric/nn/pool/__init__.py", line 196, in radius_graph
    flow)
  File "/home/martyna/miniconda3/envs/teeth/lib/python3.7/site-packages/torch_cluster/radius.py", line 137, in radius_graph
    max_num_neighbors if loop else max_num_neighbors + 1)
  File "/home/martyna/miniconda3/envs/teeth/lib/python3.7/site-packages/torch_cluster/radius.py", line 95, in radius
    col = [sample(torch.tensor(c), max_num_neighbors) for c in col]
  File "/home/martyna/miniconda3/envs/teeth/lib/python3.7/site-packages/torch_cluster/radius.py", line 95, in <listcomp>
    col = [sample(torch.tensor(c), max_num_neighbors) for c in col]
RuntimeError: tensors used as indices must be long, byte or bool tensors
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/martyna/miniconda3/envs/teeth/lib/python3.7/site-packages/torch_cluster/radius.py", line 10
def sample(col: torch.Tensor, count: int) -> torch.Tensor:
    if col.size(0) > count:
        col = col[torch.randperm(col.size(0))][:count]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return col`

Steps to reproduce an error:

` import os.path as osp

from torch_geometric.data import DataLoader
from torch_geometric.datasets import ShapeNet
import torch_geometric.transforms as T
from torch_geometric.nn import radius_graph

N = 100
batch_size = 2

category = 'Airplane'
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'ShapeNet')
transform = T.Compose([
    T.RandomTranslate(0.01),
    T.RandomRotate(15, axis=0),
    T.RandomRotate(15, axis=1),
    T.RandomRotate(15, axis=2),
    T.FixedPoints(N),
])
pre_transform = T.NormalizeScale()
train_dataset = ShapeNet(path, category, split='trainval', transform=transform,
                         pre_transform=pre_transform)
train_loader = DataLoader(
    train_dataset, batch_size=batch_size, shuffle=True, num_workers=4)

for i, data in enumerate(train_loader):
    x, batch = data.x, data.batch
    edge_index_sm = radius_graph(x, r=0.2, batch=batch)`

Could you please help me with an error? Noticed that when changing line 10 in file torch_cluster/radius.py to:
`col = col[torch.randperm(col.size(0)).long()][:count]` 
error no longer occurs.

**Comment by rusty1s** [comment]
This one is on my. Sorry! I fixed it in `torch-cluster` master. If you do not want to reinstall, you can simply fix the Python file in `torch_cluster/radius.py` by yourself. All you need to do is swap out the `sample` function with:
```python
@torch.jit.script
def sample(col: torch.Tensor, count: int) -> torch.Tensor:
    if col.size(0) > count:
        col = col[torch.randperm(col.size(0), dtype=torch.long)][:count]
    return col
```

**Comment by mkumaszka** [comment]
Great, thanks for the fix!
