### ISSUE TITLE
QM9 stopped working

### ISSUE THREAD

**Issue by pavelbatyr** [rusty1s/pytorch_geometric#1068]
## 🐛 Bug

Hello. QM9 has stopped working today, using pytorch geometric 1.3.2.
```
Downloading http://www.roemisch-drei.de/qm9.zip
Extracting /storage/Batyr/db/datasets/QM9/raw/qm9.zip
Processing...
Using a pre-processed version of the dataset. Please install `rdkit` to alternatively process the raw data.
Traceback (most recent call last):
  File "/storage/Batyr/graphNets/graphNets.py", line 26, in <module>
    spec.loader.exec_module(config)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/storage/Batyr/graphNets/configs/config101.py", line 27, in <module>
    dataset = QM9(root='/storage/Batyr/db/datasets/QM9', pre_transform=transform)
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/qm9.py", line 58, in __init__
    super(QM9, self).__init__(root, transform, pre_transform, pre_filter)
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/in_memory_dataset.py", line 52, in __init__
    pre_filter)
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/dataset.py", line 104, in __init__
    self._process()
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/dataset.py", line 148, in _process
    self.process()
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/qm9.py", line 81, in process
    data_list = [data for data in self]
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/qm9.py", line 81, in <listcomp>
    data_list = [data for data in self]
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/in_memory_dataset.py", line 71, in __getitem__
    data = self.get(idx)
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/in_memory_dataset.py", line 106, in get
    s = list(repeat(slice(None), item.dim()))
AttributeError: 'list' object has no attribute 'dim'
```

## Environment
torch (1.3.1)
torch-cluster (1.4.5)
torch-geometric (1.3.2)
torch-scatter (1.4.0)
torch-sparse (0.4.3)
torch-spline-conv (1.1.1)
Python 3.6.9, Linux
I can't really upgrade pytorch geometric to 1.4 because CUDA version on cluster seems to be out of my control so I can't upgrade it.

## Additional context
Same thing happens in k-gnn from https://github.com/chrsmrrs/k-gnn

Maybe you could provide a link to QM9 dataset with a fixed version instead of gradually changing it without versioning? Thanks.

**Comment by rusty1s** [comment]
I see, I will try to make use of versioning in future releases. PyG 1.3.2 crashes because it cannot handle string attributes yet (`name` for QM9). You can fix it by replacing line 81 in `qm9.py` with:
```python
self.data.name = None
data_list = [self.get(i) for i in range(len(self))]
```

**Comment by pavelbatyr** [comment]
It works. Thank you!
