### ISSUE TITLE
Data processing NoneTypes

### ISSUE THREAD

**Issue by happenwah** [rusty1s/pytorch_geometric#108]
Hi, and first of all: Thank you for this awesome package!

I was previously using torch_geometric on another machine, but have recently installed it on my Windows 10 laptop, using CUDA 10.0 and PyTorch 1.0.0

After downloading each dataset and moving it to raw directory, it seems that there are issues with reading the processed file. Looking at the enzymes_diff_pool.py example, here is the error message:

`'Traceback (most recent call last):
  File "enzymes_diff_pool.py", line 143, in <module>
    train_loss = train(epoch)
  File "enzymes_diff_pool.py", line 122, in train
    output, reg = model(data.x, data.adj, data.mask)
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "enzymes_diff_pool.py", line 97, in forward
    s = self.gnn1_pool(x, adj, mask)
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "enzymes_diff_pool.py", line 69, in forward
    batch_size, num_nodes, in_channels = x.size()
AttributeError: 'NoneType' object has no attribute 'size''`

Amongst the few examples I have tested, only the ones involving the Cora dataset run smoothly, such as gat.py and cora.py. I have also tried mutag_gin.py and got the same error message.

Apart from this everything seems to be working fine, I wonder whether anyone is having the same issue. Thanks in advance!

**Comment by rusty1s** [comment]
It is hard to tell what when wrong from your error message. It seems that `data` has no attributes? Can you show me the output of `print(dataset.data)`?

**Comment by happenwah** [comment]
Only contains edges:
`Data(edge_index=[2, 73706])`

Also, the first error message is the following:

`Downloading https://ls11-www.cs.uni-dortmund.de/people/morris/graphkerneldatasets/ENZYMES.zip
Extracting C:\Users\tiago\Desktop\data\ENZYMES_d\ENZYMES.zip
Traceback (most recent call last):
  File "enzymes_diff_pool.py", line 24, in <module>
    pre_filter=MyFilter())
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_geometric\datasets\tu_dataset.py", line 47, in __init__
    pre_filter)
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 56, in __init__
    pre_filter)
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_geometric\data\dataset.py", line 82, in __init__
    self._download()
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_geometric\data\dataset.py", line 108, in _download
    self.download()
  File "C:\Users\tiago\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_geometric\datasets\tu_dataset.py", line 83, in download
    os.rename(osp.join(self.root, self.name), self.raw_dir)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\tiago\\Desktop\\data\\ENZYMES_d\\ENZYMES' -> 'C:\\Users\\tiago\\Desktop\\data\\ENZYMES_d\\raw'`

I have ignored it at first since it can be fixed by moving data manually to raw. But the Cora examples do not require me to perform this extra step.

**Comment by rusty1s** [comment]
Seems Windows related. I pushed a possible fix to current master. Can you try it out?

**Comment by happenwah** [comment]
That fixes the raw directory issues, but the processed data file still contains only edges.

**Comment by rusty1s** [comment]
Quite hard to tell and I do not have a Windows machine :(
Maybe you can debug `read/tu.py` by yourself?

**Comment by happenwah** [comment]
Will look into that, thank you

**Comment by neon5d** [comment]
names = [f.split('/')[-1][len(prefix) + 1:-4] for f in files]
=> replace '/' with 'os.sep'
names = [f.split(os.sep)[-1][len(prefix) + 1:-4] for f in files]

**Comment by rusty1s** [comment]
Awesome! Fixed in master.
