### ISSUE TITLE
process blocked on import

### ISSUE THREAD

**Issue by kunshouout** [rusty1s/pytorch_geometric#1101]
the process seems to be blocked when i simply 
`import torch_geometric
`
After i press ctrl+c, the errors look like this:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-dd0eabcc7f2f>", line 1, in <module>
    from torch_geometric.utils import dense_to_sparse
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\torch_geometric\__init__.py", line 5, in <module>
    import torch_geometric.transforms
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\torch_geometric\transforms\__init__.py", line 36, in <module>
    from .gdc import GDC
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\torch_geometric\transforms\gdc.py", line 20, in <module>
    class GDC(object):
  File "C:\Program Files\Python37\lib\site-packages\torch_geometric\transforms\gdc.py", line 497, in GDC
    @jit()
  File "C:\Program Files\Python37\lib\site-packages\torch_geometric\transforms\gdc.py", line 13, in decorator
    return numba.jit(cache=True)(func)
  File "C:\Program Files\Python37\lib\site-packages\numba\decorators.py", line 193, in wrapper
    disp.enable_caching()
  File "C:\Program Files\Python37\lib\site-packages\numba\dispatcher.py", line 679, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "C:\Program Files\Python37\lib\site-packages\numba\caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "C:\Program Files\Python37\lib\site-packages\numba\caching.py", line 344, in __init__
    locator = cls.from_function(py_func, source_path)
  File "C:\Program Files\Python37\lib\site-packages\numba\caching.py", line 183, in from_function
    self.ensure_cache_path()
  File "C:\Program Files\Python37\lib\site-packages\numba\caching.py", line 127, in ensure_cache_path
    tempfile.TemporaryFile(dir=path).close()
  File "C:\Program Files\Python37\lib\tempfile.py", line 547, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Program Files\Python37\lib\tempfile.py", line 255, in _mkstemp_inner
    name = next(names)
  File "C:\Program Files\Python37\lib\tempfile.py", line 156, in __next__
    letters = [choose(c) for dummy in range(8)]
  File "C:\Program Files\Python37\lib\tempfile.py", line 156, in <listcomp>
    letters = [choose(c) for dummy in range(8)]
  File "C:\Program Files\Python37\lib\random.py", line 259, in choice
    i = self._randbelow(len(seq))
  File "C:\Program Files\Python37\lib\random.py", line 234, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
KeyboardInterrupt

## Environment

* OS: windows 10
* Python version: 3.7
* PyTorch version: 1.4.0
* CUDA/cuDNN version: cpu

**Comment by rusty1s** [comment]
Mh, I don't really know what is causing this and I may need a little help from you here. It would be first good to find out which subpackage is causing this, *i.e.*, by importing `torch_geometric.nn`, `torch_geometric.data` and so on.

**Comment by kunshouout** [comment]
The behaviour can be reproduced by 
`import torch_geometric.transforms`

I think it's the caused by jit decorator in GDC.py

**Comment by rusty1s** [comment]
Do you know why numba does not work for you?

**Comment by kunshouout** [comment]
After a little dig-in, I found the problem. The jit decorator in torch_geometric\transforms\gdc.py asks numba to cache, and numba tries to create a cache file in torch_geometric\__py_cache__ where the  jit decorator resides. My user account does not have write permission to torch_geometric\__py_cache__, hence it blocks. 

I still don't understand why it doesn't raise an exception instead, but I found a quick fix. Create a configuration file named .numba_config.yaml where python is invoked, and specify the cache_dir yourself like this:

`CACHE_DIR: D:\Ken\study\study_pytorch\pyg`

Check out the numba doc here [https://numba.pydata.org/numba-doc/latest/reference/envvars.html#envvar-NUMBA_CACHE_DIR](url)

This is not really a pyg issue, but i guess it could be helpful if it is mentioned somewhere in the manual

**Comment by rusty1s** [comment]
Interesting. I am wondering why this does not get caught by [this snippet](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/transforms/gdc.py#L10-L17).
