### ISSUE TITLE
TUD Datasets: Regression datasets with multiple target do not work

### ISSUE THREAD

**Issue by chrsmrrs** [rusty1s/pytorch_geometric#1117]
## 🐛 Bug

Regression datasets with multiple targets do not work. 

## To Reproduce
```
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'datasets', "alchemy_valid")
TUDataset(path, name="alchemy_valid")
```

Downloading https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/alchemy_valid.zip
Extracting /Users/chrsmrrs/localwl_dev/datasets/alchemy_valid/alchemy_valid.zip
Processing...
Traceback (most recent call last):
  File "/Users/chrsmrrs/localwl_dev/kgnn/kgnn_regress_base.py", line 97, in <module>
    TUDataset(path, name="alchemy_valid")
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 47, in __init__
    pre_filter)
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 87, in process
    self.data, self.slices = read_tu_data(self.raw_dir, self.name)
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/io/tu.py", line 84, in read_tu_data
    y = read_file(folder, prefix, 'graph_attributes')
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/io/tu.py", line 102, in read_file
    return read_txt_array(path, sep=',', dtype=dtype)
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/io/txt_array.py", line 13, in read_txt_array
    return parse_txt_array(src, sep, start, end, dtype, device)
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/io/txt_array.py", line 5, in parse_txt_array
    src = [[float(x) for x in line.split(sep)[start:end]] for line in src]
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/io/txt_array.py", line 5, in <listcomp>
    src = [[float(x) for x in line.split(sep)[start:end]] for line in src]
  File "/Users/chrsmrrs/miniconda3/envs/learn2maxcut/lib/python3.7/site-packages/torch_geometric/io/txt_array.py", line 5, in <listcomp>
    src = [[float(x) for x in line.split(sep)[start:end]] for line in src]
ValueError: could not convert string to float: '1.145679771862074 1.2776982391515177 -1.5830948608858193 -0.20776688667940443 3.894671919769575 -0.20775251859217939 0.19154616548695583 -0.207760304662119 -0.20775251859212454 0.41064412346139784 -0.9805896405620556 0.09537043972313793 '

**Comment by rusty1s** [comment]
The graph attributes file is missing a comma between different regression values.

**Comment by chrsmrrs** [comment]
Thanks, we will stick to commas.
