### ISSUE TITLE
reddit.py

### ISSUE THREAD

**Issue by chenxuhao** [rusty1s/pytorch_geometric#1128]
## ❓ Questions & Help

Hi all,
I was trying to run $ python examples/reddit.py, and I got this error:
Traceback (most recent call last):
  File "examples/reddit.py", line 63, in <module>
    model = Net(dataset.num_features, dataset.num_classes).to(device)
  File "examples/reddit.py", line 25, in __init__
    self.conv1 = SAGEConv(in_channels, 16, normalize=False, concat=concat)
  File "/h2/xchen/work/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/sage_conv.py", line 34, in __init__
    super(SAGEConv, self).__init__(aggr='mean', **kwargs)
TypeError: __init__() got an unexpected keyword argument 'concat'

Similarly, some error like this:
Traceback (most recent call last):
  File "examples/reddit.py", line 92, in <module>
    loss = train()
  File "examples/reddit.py", line 73, in train
    out = model(data.x.to(device), data_flow.to(device))
  File "/h2/xchen/work/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "examples/reddit.py", line 33, in forward
    res_n_id=data.res_n_id))
  File "/h2/xchen/work/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'res_n_id'

Any idea?

Xuhao

**Comment by rusty1s** [comment]
You need to update your PyTorch Geometric version :)
