### ISSUE TITLE
os error

### ISSUE THREAD

**Issue by Ashappyboy** [rusty1s/pytorch_geometric#1146]
## Environment

* OS: windows
* Python version: 3.6
* PyTorch version:1.4.0
* CUDA/cuDNN version: no
* GCC version: 
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

>>> import torch_geometric
Traceback (most recent call last):
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_sparse\__init__.py", line 15, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch\_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "G:\anaconda\envs\python3.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_sparse\__init__.py", line 23, in <module>
    raise OSError(e)
OSError: [WinError 126] 找不到指定的模块。

**Comment by rusty1s** [comment]
Can you translate the OSError message?

**Comment by Ashappyboy** [comment]
windows OSError 126.
The error just mention the error code. After that I found some resources, because the lace of ddl file.&nbsp;
The way to slove the problem is to uninstall the package and reinstall it.
Thank you for your attention.&nbsp;
Best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Matthias Fey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上8:58
收件人:&nbsp;"rusty1s/pytorch_geometric"<pytorch_geometric@noreply.github.com&gt;;
抄送:&nbsp;"朵朵"<884665320@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rusty1s/pytorch_geometric] os error (#1146)





 
Can you translate the OSError message?

**Comment by masizhou** [comment]
hello,when I to import "torch_geometric",this error happened,have you solved this error?

**Comment by liwentao-123** [comment]
Hello , I have met the same problem as you have met , I see that you say the way to solve the problem is to uninstall the package and reinstall it and you have found some resources, so could you please describle what the resources are and which the  package has to uninstall and reinstall ? thanks you @ AShappyboy
