### ISSUE TITLE
DD、PROTEINS、NCI1 datasets cannot work with DIFFPOOL

### ISSUE THREAD

**Issue by Lhr1037** [rusty1s/pytorch_geometric#1154]
## ❓ Questions & Help

Hello:
    when i run the code in path: rusty1s/pytorch_geometric/benchmark/kernel/main, 
    DD、PROTEINS、NCI1 datasets cannot work with diffpool, 
    it will rise the " ValueError:  Found input variables with inconsistent numbers of samples: [xxxx, ####] "
    Do you know why is it? Thank you.

**Comment by snubeaver** [comment]
This is because in datasets.py they limit the total number of nodes

        if name == 'REDDIT-BINARY':
            num_nodes = min(int(num_nodes / len(dataset) * 1.5), max_num_nodes)
        else:
            num_nodes = min(int(num_nodes / len(dataset) * 5), max_num_nodes)

Then you have to also limit the number of the label to make the number of the samples consistent

        dataset.data.y = dataset.data.y[torch.tensor(indices)]

**Comment by jiaruHithub** [comment]
If I use dataset NCI109,The new bug has been reported:
```NCI109 - DiffPool
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    logger=None,
  File "/home/pyg/pyg/benchmark/kernel1/train_eval.py", line 43, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "/home/pyg/pyg/benchmark/kernel1/train_eval.py", line 114, in train
    out = model(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyg/pyg/benchmark/kernel1/diff_pool.py", line 65, in forward
    s = self.pool_block1(x, adj, mask, add_loop=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyg/pyg/benchmark/kernel1/diff_pool.py", line 27, in forward
    x1 = F.relu(self.conv1(x, adj, mask, add_loop))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given
```
How can I fix this error?

**Comment by rusty1s** [comment]
Should be fixed in master. Thanks for reporting!
