### ISSUE TITLE
Error when use own dataset

### ISSUE THREAD

**Issue by logsea** [rusty1s/pytorch_geometric#1158]
## ❓ Questions & Help

Hi, I'm using a Dataloader to feed data to train, but a error occur.
**dimension specified as 0 but tensor has no dimensions**
Is there any error in my code?

this is the code:

> 
    train_dataset = dataset.train_dataset
    random.shuffle(train_dataset)
    train_loader = DataLoader(train_dataset, batch_size=16)

> 
    def train(epoch):

        model.train()

        loss_all = 0
        for data in train_loader: 
            data = data.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = F.nll_loss(output, data.y)
            loss.backward()
            loss_all += data.num_graphs * loss.item()
            optimizer.step()
        return loss_all / len(train_dataset)

The `train_dataset` from `dataset.train_dataset` is just a Python array like the guidebook say. The `y` is a tensor with only one `torch.long` variable , mean the label of the graph.
![图片](https://user-images.githubusercontent.com/25080448/80298588-8995fc00-87c0-11ea-89df-b0b182cf47ac.png)

The error message is (forget the filename, the network is not GAT, it's a topk_pool):

> 
    Traceback (most recent call last):
      File "ML_GAT.py", line 96, in <module>
        loss = train(epoch)
      File "ML_GAT.py", line 73, in train
        for data in train_loader:
      File "C:\Users\username\.conda\envs\torchGeo\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
        data = self._next_data()
      File "C:\Users\username\.conda\envs\torchGeo\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
        data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
      File "C:\Users\username\.conda\envs\torchGeo\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
        return self.collate_fn(data)
      File "C:\Users\username\.conda\envs\torchGeo\lib\site-packages\torch_geometric\data\dataloader.py", line 47, in <lambda>
        collate_fn=lambda batch: collate(batch), **kwargs)
      File "C:\Users\username\.conda\envs\torchGeo\lib\site-packages\torch_geometric\data\dataloader.py", line 26, in collate
        return Batch.from_data_list(batch, follow_batch)
      File "C:\Users\username\.conda\envs\torchGeo\lib\site-packages\torch_geometric\data\batch.py", line 50, in from_data_list
        size = item.size(data.__cat_dim__(key, data[key]))
    IndexError: dimension specified as 0 but tensor has no dimensions

**Comment by rusty1s** [comment]
Try to save `y` as a one-dimensional tensor (`torch.tensor([value])`) instead of a zero-dimensional tensor. That should fix the `cat` bug.

**Comment by logsea** [comment]
Thank you for your reply. The data can be read normally now.
