### ISSUE TITLE
run example cora error

### ISSUE THREAD

**Issue by fuxianh** [rusty1s/pytorch_geometric#117]
ModuleNotFoundError: No module named 'unique_cuda'

Since my pytorch version is 1.0.0. I cannot install torch-unique with pip, it gives me error, seems didn't support 1.0.0, which confuses me a lot.

**Comment by rusty1s** [comment]
Hi, this seems to be an error with the installation of torch-sparse (which also comes with an unique kernel for faster coalescing). Can you run the test suite of torch-sparse?

**Comment by rusty1s** [comment]
I created a [FAQ](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#frequently-asked-questions) for common installation errors. Let me know if this fixes your issues.

**Comment by rusty1s** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by patilaum** [comment]
Got the same error when I ran 
`allennlp train train_configs/defaults.jsonnet -s experiments/name_of_experiment --include-package dataset_readers.spider --include-package models.semantic_parsing.spider_parser` from repo [https://github.com/benbogin/spider-schema-gnn.git](url)

following are the logs

`2019-08-19 18:46:32,077 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-08-19 18:46:32,480 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-08-19 18:46:32,483 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
Traceback (most recent call last):
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp===0.8.5-unreleased', 'console_scripts', 'allennlp')()
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/allennlp-0.8.5_unreleased-py3.6.egg/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/allennlp-0.8.5_unreleased-py3.6.egg/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/allennlp-0.8.5_unreleased-py3.6.egg/allennlp/common/util.py", line 323, in import_submodules
    module = importlib.import_module(package_name)
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./models/semantic_parsing/__init__.py", line 1, in <module>
    from models.semantic_parsing.spider_parser import SpiderParser
  File "./models/semantic_parsing/spider_parser.py", line 18, in <module>
    from torch_geometric.data import Data, Batch
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_sparse/__init__.py", line 1, in <module>
    from .coalesce import coalesce
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 4, in <module>
    from .utils.unique import unique
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_sparse/utils/unique.py", line 5, in <module>
    import unique_cuda
ModuleNotFoundError: No module named 'unique_cuda'`

**Comment by patilaum** [comment]
I got the above error when I install torch_sparse==0.2.1

Got the following error when I installed torch_sparse>=0.2.2

Traceback (most recent call last):
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp===0.8.5-unreleased', 'console_scripts', 'allennlp')()
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/allennlp-0.8.5_unreleased-py3.6.egg/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/allennlp-0.8.5_unreleased-py3.6.egg/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/allennlp-0.8.5_unreleased-py3.6.egg/allennlp/common/util.py", line 323, in import_submodules
    module = importlib.import_module(package_name)
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./models/semantic_parsing/__init__.py", line 1, in <module>
    from models.semantic_parsing.spider_parser import SpiderParser
  File "./models/semantic_parsing/spider_parser.py", line 18, in <module>
    from torch_geometric.data import Data, Batch
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 6, in <module>
    from .sampler import NeighborSampler
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_geometric/data/sampler.py", line 4, in <module>
    from torch_cluster import neighbor_sampler
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_cluster/__init__.py", line 1, in <module>
    from .graclus import graclus_cluster
  File "/home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_cluster/graclus.py", line 2, in <module>
    import torch_cluster.graclus_cpu
ImportError: /home/aum/IMBS/text2sql/spider-schema-gnn-master/alle/lib/python3.6/site-packages/torch_cluster/graclus_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

**Comment by rusty1s** [comment]
You should try downgrading gcc to 5.4.

**Comment by patilaum** [comment]
My gcc version is already 5.4.0
here's the log when I ran `gcc -v`

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by patilaum** [comment]
My gcc version is already 5.4.0
here's the log when I ran `gcc --version`


gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by rusty1s** [comment]
Mh, eventually those threads may help you: https://github.com/open-mmlab/mmdetection/issues/728#issuecomment-497232980 and https://github.com/facebookresearch/maskrcnn-benchmark/issues/223

**Comment by patilaum** [comment]
Issue is still not getting solved. Some threads say the problem is because of incompatible pytorch version which some say it is because of cuda version. I uninstalled and reinstalled pytorch and torchvision with cuda 10 and others being pillow-6.1.0 torch-1.2.0 torchvision-0.4.0

But still the problem persists. Please help.

**Comment by rusty1s** [comment]
Please see my message here https://github.com/rusty1s/pytorch_geometric/issues/632#issuecomment-523129293.
