### ISSUE TITLE
Question about reddit.py

### ISSUE THREAD

**Issue by SKD621** [rusty1s/pytorch_geometric#1182]
## ❓ Questions & Help

Hello, in the reddit.py, the implement of SAGENet is 
```
class SAGENet(torch.nn.Module):
    
    def __init__(self, in_channels, out_channels, concat=False):
        super(SAGENet, self).__init__()
        self.conv1 = SAGEConv(in_channels, 16, normalize=False, concat=concat)
        self.conv2 = SAGEConv(16, out_channels, normalize=False, concat=concat)

    def forward(self, x, data_flow):
        data = data_flow[0]
        x = x[data.n_id]
        x = F.relu(
            self.conv1((x, None), data.edge_index, size=data.size,
                       res_n_id=data.res_n_id))
        x = F.dropout(x, p=0.5, training=self.training)
        data = data_flow[1]
        x = self.conv2((x, None), data.edge_index, size=data.size,
                       res_n_id=data.res_n_id)
        return F.log_softmax(x, dim=1)
```
why the input of self.conv1 for positional argument is (x, None), not x? 
And, is there some special meanings of (x, None) for sage_conv?

Thanks for help in advance.

**Comment by SKD621** [comment]
In addition, when run the following code: 
```
from torch_geometric.data import Data
from torch_geometric.datasets import Planetoid, Reddit

import numpy as np

import torch
import torch.nn.functional as F
import torch_geometric.transforms as T
from torch_geometric.data import NeighborSampler
from torch_geometric.nn import SAGEConv, GATConv

dataset = Planetoid(root='dataset', name='Cora', transform=T.NormalizeFeatures())
# dataset = Reddit("dataset/Reddit")
data = dataset[0]

class SAGENet(torch.nn.Module):

    def __init__(self, in_channels, out_channels, concat=False):
        super(SAGENet, self).__init__()
        self.conv1 = SAGEConv(in_channels, 16, normalize=False, concat=concat)
        self.conv2 = SAGEConv(16, out_channels, normalize=False, concat=concat)

    def forward(self, x, data_flow):
        data = data_flow[0]
        x = x[data.n_id]
        x = F.relu(
            self.conv1((x, None), data.edge_index, size=data.size,
                       res_n_id=data.res_n_id))
        x = F.dropout(x, p=0.5, training=self.training)
        data = data_flow[1]
        x = self.conv2((x, None), data.edge_index, size=data.size,
                       res_n_id=data.res_n_id)
        return F.log_softmax(x, dim=1)

# device = torch.device('cpu')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model, data = SAGENet(dataset.num_features, dataset.num_classes).to(device), dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)


loader = NeighborSampler(data.to(device), size=[25, 10], num_hops=2, batch_size=1000,
                         shuffle=True, add_self_loops=True)

def train():
    model.train()

    total_loss = 0
    for data_flow in loader(data.train_mask):
        optimizer.zero_grad()
        out = model(data.x.to(device), data_flow.to(device))
        loss = F.nll_loss(out, data.y[data_flow.n_id].to(device))
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * data_flow.batch_size
    return total_loss / data.train_mask.sum().item()


def test(mask):
    model.eval()

    correct = 0
    for data_flow in loader(mask):
        pred = model(data.x.to(device), data_flow.to(device)).max(1)[1]
        correct += pred.eq(data.y[data_flow.n_id].to(device)).sum().item()
    return correct / mask.sum().item()

best_val, best_test = 0., 0.
for epoch in range(1, 201):
    loss = train()
    test_acc,val_acc = test(data.test_mask), test(data.val_mask)
    if best_val < val_acc:
        best_val, best_test = val_acc, test_acc
    print('Epoch: {:02d}, Loss: {:.4f}, Test: {:.4f}'.format(
        epoch, loss, best_test))
```
It's ok with CPU, however it occur some problems in GPU mode(I have checked the GPU is ok).  It seems that some problems in sampler.py. The error messages are:
```
Traceback (most recent call last):
  File "/home/cgy/jxq/gnn/graphsage.py", line 91, in <module>
    loss = train()
  File "/home/cgy/jxq/gnn/graphsage.py", line 70, in train
    for data_flow in loader(data.train_mask):
  File "/home/cgy/anaconda3/envs/torch_geo/lib/python3.6/site-packages/torch_geometric/data/sampler.py", line 271, in __call__
    yield produce(n_id)
  File "/home/cgy/anaconda3/envs/torch_geo/lib/python3.6/site-packages/torch_geometric/data/sampler.py", line 172, in __produce_bipartite_data_flow__
    e_id = neighbor_sampler(n_id, self.cumdeg, self.size[l])
torch.jit.Error: Exception
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/cgy/anaconda3/envs/torch_geo/lib/python3.6/site-packages/torch_cluster/sampler.py", line 6
@torch.jit.script
def neighbor_sampler(start: torch.Tensor, rowptr: torch.Tensor, size: float):
    assert not start.is_cuda
    ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

    factor: float = -1.
```
