### ISSUE TITLE
GEDDataset

### ISSUE THREAD

**Issue by shi27feng** [rusty1s/pytorch_geometric#1189]
import torch_geometric as tg
dataset_name = 'LINUX'
dl = tg.datasets.GEDDataset(root='./data/{}'.format(dataset_name), name=dataset_name)
Downloading https://drive.google.com/uc?export=download&id=1nw0RRVgyLpit4V4XFQyDy0pI6wUEXSOI
Extracting data/LINUX/raw/uc?export=download&id=1nw0RRVgyLpit4V4XFQyDy0pI6wUEXSOI
Downloading https://drive.google.com/uc?export=download&id=14FDm3NSnrBvB7eNpLeGy5Bz6FjuCSF5v
Processing...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-abbe00cde14e>", line 1, in <module>
    dl = tg.datasets.GEDDataset(root='./data/{}'.format(dataset_name), name=dataset_name)
  File "/home/xx/.local/lib/python3.7/site-packages/torch_geometric/datasets/ged_dataset.py", line 82, in __init__
    pre_filter)
  File "/home/xx/.local/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/xx/.local/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/xx/.local/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/home/xx/.local/lib/python3.7/site-packages/torch_geometric/datasets/ged_dataset.py", line 156, in process
    mat[x, y], mat[y, x] = g, g
RuntimeError: expected dtype Float but got dtype Double

**Comment by shi27feng** [comment]
Can I change this line to:
mat[x, y], mat[y, x] = float(g), float(g) ?

**Comment by shi27feng** [comment]
I convert the g to torch.float:
```python
x, y, g = torch.tensor(xs), torch.tensor(ys), torch.tensor(gs, dtype=torch.float)
mat[x, y], mat[y, x] = g, g
```

**Comment by tianyang1998** [comment]
The suggestion does work!

**Comment by rusty1s** [comment]
Great! Fixed in master.
