### ISSUE TITLE
Graph_SAINT  ConnectionRefusedError

### ISSUE THREAD

**Issue by xiangzhang1015** [rusty1s/pytorch_geometric#1295]
## ❓ Questions & Help

Hi, I tried to run the example graph_saint.py at 
Python == 3.7.4
geometric == 1.4.3

BTW, geometric 1.4.3 doesn't have datasets/flickr.py and data/graph_saint.py, I manually copied them to my local site-packages and revised the __init__.py accordingly.

But when I run the example, I got an error as follow:

```
Process Process-2:
Traceback (most recent call last):
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xz204/.local/lib/python3.7/site-packages/torch_geometric/data/graph_saint.py", line 187, in __put_data__
    sample = self.__sample_queue__.get()
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/xz204/.local/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/n/app/python/3.7.4/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

The problem is in  `GraphSAINTRandomWalkSampler`, but I do not understand why it tried to call socket to build connection that seems totally irrelevant?  

Is this caused by the `num_workers=4` in `GraphSAINTRandomWalkSampler`? I tried to use single-worker by set `num_workers=1`, but still got the same error.

 Could you please help me fix the error, thanks very much!

**Comment by xiangzhang1015** [comment]
The problem was solved by set num_workers=0, but still don't know why the multiworker doesn't work.

**Comment by xbinglzh** [comment]
how  fix
