### ISSUE TITLE
The Bug of to_dense_batch:''AttributeError: 'Batch' object has no attribute 'size'. ''

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1326]
## 🐛 Bug

When I use the func pytorch_geometric.utils.to_dense_batch.The bug is arise:
```python
Traceback (most recent call last):
  File "trails.py", line 194, in <module>
    test()
  File "trails.py", line 191, in test
    a = to_dense_batch(data)
  File "\anna\to_dense_batch.py", line 27, in to_dense_batch
    mask = torch.ones(1, x.size(0), dtype=torch.bool, device=x.device)
AttributeError: 'Batch' object has no attribute 'size.
```
## To Reproduce

I use the 'DD' dataset
The code of bug as fellow:

```python
num_training = int(len(dataset)*0.8)
num_val = int(len(dataset)*0.1)
num_test = len(dataset) - (num_training+num_val)
training_set,validation_set,test_set = random_split(dataset,[num_training,num_val,num_test])

train_loader = DataLoader(training_set, batch_size=50, shuffle=True)

@torchsnooper.snoop()
def test():
        for i, data in enumerate(train_loader):
                a = to_dense_batch(data)
                print(a.shape)

test()
```
## Expected behavior

I don't know how to set the parameters of to_dense_batch and tackle this bug.
I want to this func help me to creat a matrix for every batch and every batch have N graphs 
## Environment

* OS:
* Python version:3.6
* PyTorch version:1.4.0
* CUDA/cuDNN version:9.0
* GCC version:
* Any other relevant information:

## Additional context

@

**Comment by jiaruHithub** [comment]
I am sorry, I sovle it!Thank you!
