### ISSUE TITLE
How to use benchmarks to repeat experiment?

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1345]
## ❓ Questions & Help

Hello,I try to run the benchmarks for graph classification.I don't know how to use the benchmarks.
For example, I wnat to reproduce the SAGPool in D&D dataset.
Forgive me for being slow:).How do I operate?

**Comment by shangguan91** [comment]
i have same problem, i want to reproduce five different networks model for point cloud on  ModelNet10 dataset. 
I got stuck there for 3 days.

**Comment by rusty1s** [comment]
You need to run [main.py](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/main.py). If you only want to train a specific implementation/dataset, you can comment out all other models/datasets in `nets` and `datasets`. For a better logging experience, you can also pass `logger` to the `cross_validation_with_val_set` method.

**Comment by jiaruHithub** [comment]
> You need to run [main.py](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/main.py). If you only want to train a specific implementation/dataset, you can comment out all other models/datasets in `nets` and `datasets`. For a better logging experience, you can also pass `logger` to the `cross_validation_with_val_set` method.

Fine, thanks.
Em...but I can't find this file,how can I call this file 'main.py'?
Please Forgive me for being slow... :)

**Comment by rusty1s** [comment]
You just call it via python, see [here](https://github.com/rusty1s/pytorch_geometric/tree/master/benchmark/kernel).

**Comment by jiaruHithub** [comment]
> You just call it via python, see [here](https://github.com/rusty1s/pytorch_geometric/tree/master/benchmark/kernel).

Thank you for your patient answer!
the file eported an error:
```PROTEINS - SAGPool
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    logger=None,
  File "D:\muqian\code\pytorch_geometric\benchmark\kernel\train_eval.py", line 19, in cross_validation_with_val_set
    val_idx) in enumerate(zip(*k_fold(dataset, folds))):
  File "D:\muqian\code\pytorch_geometric\benchmark\kernel\train_eval.py", line 93, in k_fold
    train_mask[test_indices[i]] = 0
IndexError: tensors used as indices must be long, byte or bool tensors
```
How can I handle this error?
Thank you!

**Comment by rusty1s** [comment]
Seems to be Windows/numpy related. You can fix it by casting indices to `long` explicitly:
```
test_indices.append(torch.from_numpy(idx).to(torch.long))
```

**Comment by jiaruHithub** [comment]
> test_indices.append(torch.from_numpy(idx).to(torch.long))

It's working!Thank you!
But I have a question that instability of acc and experiment acc can't attend the paper claimed.
Is the question relate the seed or Environment configuration?
