### ISSUE TITLE
Question about add_remain_self_loop

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1355]
## 🐛 Bug

```Traceback (most recent call last):
  File "main.py", line 87, in <module>
    out = model(data)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\pysnooper\tracer.py", line 263, in simple_wrapper
    return function(*args, **kwargs)
  File "D:\muqian\code\SAGPool-master333333333333333333\SAGPool-master\networks.py", line 39, in forward
    x = F.relu(self.conv1(x, edge_index))
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 99, in forward
    self.cached_num_edges = edge_index.size(1)
AttributeError: 'tuple' object has no attribute 'size'
```
## To Reproduce

I use code
```
x, edge_index, batch = data.x, add_remaining_self_loops(data.edge_index), data.batch
x = F.relu(self.conv1(x, edge_index))
x, edge_index, batch, _ = self.pool1(x, edge_index, None, batch)
 x1 = f_neig_max(x, edge_index, batch)
```
I used code before:
```
x, edge_index, batch = data.x, data.edge_index, data.batch
```
That's normal.
Why I use the func```add_remain_self_loop``` then generate bug that as above.
Looking forward to your reply

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
`add_remaining_self_loops` returns a tuple, so you need to do:
```
x, (edge_index, edge_weight), batch = data.x, add_remaining_self_loops(data.edge_index), data.batch
```

**Comment by jiaruHithub** [comment]
> edge_weigh



> `add_remaining_self_loops` returns a tuple, so you need to do:
> 
> ```
> x, (edge_index, edge_weight), batch = data.x, add_remaining_self_loops(data.edge_index), data.batch
> ```

Your reply is so fast!
The speed is too handsome!
I wish you a happy life!
