### ISSUE TITLE
'SparseTensor' object has no attribute 'sample'

### ISSUE THREAD

**Issue by PikachuHy** [rusty1s/pytorch_geometric#1371]
## To Reproduce

I run the example of metapath2vec

https://github.com/rusty1s/pytorch_geometric/blob/master/examples/metapath2vec.py

```
Traceback (most recent call last):
  File "metapath2vec.py", line 69, in <module>
    train(epoch)
  File "metapath2vec.py", line 35, in train
    for i, (pos_rw, neg_rw) in enumerate(loader):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch_geometric/nn/models/metapath2vec.py", line 157, in sample
    return self.pos_sample(batch), self.neg_sample(batch)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch_geometric/nn/models/metapath2vec.py", line 123, in pos_sample
    batch = adj.sample(num_neighbors=1, subset=batch).squeeze()
AttributeError: 'SparseTensor' object has no attribute 'sample'
```

https://github.com/rusty1s/pytorch_geometric/blob/1b6ee0a9893ae00f861383b27225fc6f1b66fad1/torch_geometric/nn/models/metapath2vec.py#L123

and `adj` is `SparseTensor`

https://github.com/rusty1s/pytorch_geometric/blob/1b6ee0a9893ae00f861383b27225fc6f1b66fad1/torch_geometric/nn/models/metapath2vec.py#L4

```python
adj = SparseTensor(row=row, col=col, sparse_sizes=sizes)
adj = adj.to('cpu')
adj_dict[keys] = adj
```

I view the latest source code and find no such method.

https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/tensor.py

Is anything wrong there? thanks.

## Environment

* OS: ubuntu 16.04
* Python version: Python 3.6.8
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.0
* GCC version: 5.4.0
* Any other relevant information:

**Comment by rusty1s** [comment]
No, there's nothing wrong, but `SparseTensor.sample` is only available on PyTorch 1.5. or when installing `torch-sparse` from source via `pip install torch-sparse`. Sorry!

**Comment by PikachuHy** [comment]
Thank you for your prompt reply.

**Comment by PikachuHy** [comment]
time to upgrade 😂

**Comment by zyz-magician** [comment]
Encounter the same issue... But installing torch-sparse can't solve the problem in my  case
![image](https://user-images.githubusercontent.com/70122770/97772031-ff778780-1b96-11eb-9b33-2269af7a64f6.png)

**Comment by zyz-magician** [comment]
Also, it doesn't work for installing torch 1.5 or 1.6

**Comment by rusty1s** [comment]
Which version of `torch-sparse` are you using? It got introduced in 0.6.4, see https://github.com/rusty1s/pytorch_sparse/releases/tag/0.6.4.
