### ISSUE TITLE
URLError for torch_geometric.datasets.Planetoid

### ISSUE THREAD

**Issue by Wuyxin** [rusty1s/pytorch_geometric#1409]
## 🐛 Bug
```
from torch_geometric.datasets import Planetoid
dataset =  Planetoid(root = 'data/', name = "CiteSeer")
```
with result
```
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```
the url seems to be 
```
url = 'https://github.com/kimiyoung/planetoid/tree/master/data'
```  
instead of 
```
url = 'https://github.com/kimiyoung/planetoid/raw/master/data'
```

**Comment by Wuyxin** [comment]
well, another bug appears after i changed the url...

**Comment by rusty1s** [comment]
Yeah, that's really a weird issue. It seems that the URL only works for some people. What's the bug if you change the URL?

**Comment by Wuyxin** [comment]
full bug report:
```
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.x
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.tx
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.allx
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.y
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.ty
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.ally
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.graph
Downloading https://github.com/kimiyoung/planetoid/tree/master/data/ind.pubmed.test.index
Processing...
Traceback (most recent call last):

  File "G:\_GEO-Explain_\PubMed.py", line 12, in <module>
    dataset = Planetoid(root = 'data/', name = "PubMed")

  File "D:\Anaconda3\lib\site-packages\torch_geometric\datasets\planetoid.py", line 55, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)

  File "D:\Anaconda3\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 54, in __init__
    pre_filter)

  File "D:\Anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 93, in __init__
    self._process()

  File "D:\Anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 166, in _process
    self.process()

  File "D:\Anaconda3\lib\site-packages\torch_geometric\datasets\planetoid.py", line 108, in process
    data = read_planetoid_data(self.raw_dir, self.name)

  File "D:\Anaconda3\lib\site-packages\torch_geometric\io\planetoid.py", line 19, in read_planetoid_data
    items = [read_file(folder, prefix, name) for name in names]

  File "D:\Anaconda3\lib\site-packages\torch_geometric\io\planetoid.py", line 19, in <listcomp>
    items = [read_file(folder, prefix, name) for name in names]

  File "D:\Anaconda3\lib\site-packages\torch_geometric\io\planetoid.py", line 66, in read_file
    out = pickle.load(f, encoding='latin1')

UnpicklingError: invalid load key, '\x0a'.
```

**Comment by Wuyxin** [comment]
i think there's some problem when downloading the raw files,
i manually downloaded the files locally then uploaded it and it works.

thank you for your time @rusty1s

**Comment by Mobzhang** [comment]
> i think there's some problem when downloading the raw files,
> i manually downloaded the files locally then uploaded it and it works.
> 
> thank you for your time @rusty1s

hi, i have another question, and i think you might answer my question.
 when i manually download one datasets, I still use the geometric to load it.
such as a.py .
- from torch_geometric.datasets import BitcoinOTC

- dataset = BitcoinOTC(root='/datadrive')

but i get error in ubuntu 16, (I put a.py and datasets in the same file in windows. it can't work)

- No such file or directory: '/datadrive/raw/soc-sign-bitcoinotc.csv.gz' 
I don't know how to define the root?

**Comment by Wuyxin** [comment]
> > i think there's some problem when downloading the raw files,
> > i manually downloaded the files locally then uploaded it and it works.
> > thank you for your time @rusty1s
> 
> hi, i have another question, and i think you might answer my question.
> when i manually download one datasets, I still use the geometric to load it.
> such as a.py .
> 
> * from torch_geometric.datasets import BitcoinOTC
> * dataset = BitcoinOTC(root='/datadrive')
> 
> but i get error in ubuntu 16, (I put a.py and datasets in the same file in windows. it can work)
> 
> * No such file or directory: '/datadrive/raw/soc-sign-bitcoinotc.csv.gz'
>   I don't know how to define the root?

Maybe you should first create a folder /datadrive/raw and then put the unziped data in it.
