### ISSUE TITLE
'SparseTensor' object has no attribute 'sample_adj'

### ISSUE THREAD

**Issue by valentinhofmann** [rusty1s/pytorch_geometric#1424]
## 🐛 Bug
Thanks for all the great work, PyTorch Geometric is a fantastic library!

I would like to use the `NeighborSampler` for mini-batch training on a large graph. I tried to adapt the script [here](https://github.com/snap-stanford/ogb/blob/master/examples/linkproppred/citation/sampler.py) but received the following error:
```
Traceback (most recent call last):
  File "test.py", line 285, in <module>
    main()
  File "test.py", line 267, in main
    optimizer, device)
  File "test.py", line 130, in train
    for i, (pos_data, neg_data) in enumerate(zip(pos_loader, neg_loader)):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "test.py", line 26, in sample
    return super(PositiveLinkNeighborSampler, self).sample(batch)
  File "/.local/lib/python3.6/site-packages/torch_geometric/data/sampler.py", line 108, in sample
    adj, n_id = self.adj.sample_adj(n_id, size, replace=False)
AttributeError: 'SparseTensor' object has no attribute 'sample_adj'

```
The same error occurred when running the script at `examples/reddit.py`. Am I missing something here?

## Environment

* Python version: 3.6
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.1

**Comment by rusty1s** [comment]
I see. This is not linked in the wheel for PyTorch 1.4.0. You may either want to upgrade PyTorch to 1.5.0/1.5.1 or install `torch-sparse` from source via `pip install torch-sparse` (might take some time to compile).

**Comment by valentinhofmann** [comment]
Thanks! I successfully installed `torch-sparse` from source but am getting the following error now:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from torch_geometric.data import NeighborSampler
  File "/.local/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/.local/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/.local/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/.local/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/.local/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/.local/lib/python3.6/site-packages/torch_sparse/__init__.py", line 35, in <module>
    from .tensor import SparseTensor  # noqa
  File "/.local/lib/python3.6/site-packages/torch_sparse/tensor.py", line 11, in <module>
    class SparseTensor(object):
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1274, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1115, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError:
Unknown type name 'torch.device':
  File "/.local/lib/python3.6/site-packages/torch_sparse/tensor.py", line 77
    @classmethod
    def eye(self, M: int, N: Optional[int] = None, has_value: bool = True,
            dtype: Optional[int] = None, device: Optional[torch.device] = None,
                                                          ~~~~~~~~~~~~ <--- HERE
            fill_cache: bool = False):
```
Any idea why this might be the case?

**Comment by rusty1s** [comment]
Yeah, seems like TorchScript is just a mess between different PyTorch versions: `torch.device` is only supported as argument type in PyTorch >=1.5.0. You have two options here:
1. You can install `torch-sparse==0.6.4`
2. You can remove the `@torch.jit.script` decorators in `tensor.py` and `storage.py`.

Sorry for this, but it's really hard to support older PyTorch versions since its API changes rather frequently. It's always best to update your PyTorch to the latest version to avoid all of this.

**Comment by valentinhofmann** [comment]
I installed `torch-sparse==0.6.4`, but it still didn't work. I then upgraded to PyTorch 1.5.1, and now everything is working perfectly. Thanks so much for your help!
