### ISSUE TITLE
RuntimeError: arguments are located on different GPUs. 

### ISSUE THREAD

**Issue by Wenhao-Jin** [rusty1s/pytorch_geometric#1486]
## ❓ Questions & Help
When I trained my model using multiple GPUs with DataParallel, I got this error. 

> RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/wjin/anaconda/envs/python3_gpu/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/wjin/anaconda/envs/python3_gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "<ipython-input-17-2141970c3faa>", line 70, in forward
    out = F.relu(lin(out))#.view(-1)
  File "/home/wjin/anaconda/envs/python3_gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wjin/anaconda/envs/python3_gpu/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/wjin/anaconda/envs/python3_gpu/lib/python3.8/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:277

After some inspection, I found the problem is that the parameter "weight" and "bias" of my Linear object are using the different devices with the input data. The error occurs in the code below (the bold text)

> Class GNN(torch.nn.Module):
def __init__(GNN_num_hidden_list=[32,32], MLP_num_hidden_list=[32,16]):
    ...
    ...
    self.lins = [torch.nn.Linear(self.GNN_num_hidden_list[1],self.MLP_num_hidden_list[0]).to(self.device)]
        for i in range(1, len(self.MLP_num_hidden_list)):
            self.lins.append(torch.nn.Linear(self.MLP_num_hidden_list[i-1],self.MLP_num_hidden_list[i]).to(self.device))
    self.lins.append(torch.nn.Linear(MLP_num_hidden_list[-1], 5).to(self.device))  
def forward():
    ...
    ...
    for lin in self.lins[:-1]:
            print('out.device:{}, lin:{}{}'.format(out.device,lin.bias.device,lin.weight.device))
            **out = F.relu(lin(out))#.view(-1)**
  ...

the device info:

> out.device:cuda:2, lin:cuda:0cuda:0
out.device:cuda:3, lin:cuda:0cuda:0
out.device:cuda:5, lin:cuda:0cuda:0
out.device:cuda:1, lin:cuda:0cuda:0
out.device:cuda:4, lin:cuda:0cuda:0
out.device:cuda:0, lin:cuda:0cuda:0
out.device:cuda:0, lin:cuda:0cuda:0

Thus, I tried moving the Linear object to the device used by the input data (named _out_ here), i.e. 

> def forward():
    ...
    ...
    for lin in self.lins[:-1]:
            **lin=lin.to(out.device)**
            print('out.device:{}, lin:{}{}'.format(out.device,lin.bias.device,lin.weight.device))
            out = F.relu(lin(out))#.view(-1)
  ...

After this, the situation seems better,  the _weight_, _bias_ and the input data use the same device for most of the time but still used the different devices sometimes (shown below) and I got the same error as above. 

> out.device:cuda:3, lin:cuda:3cuda:3
out.device:cuda:3, lin:cuda:3cuda:3
out.device:cuda:5, lin:cuda:5cuda:5
out.device:cuda:5, lin:cuda:5cuda:5
out.device:cuda:1, lin:cuda:1cuda:4
out.device:cuda:4, lin:cuda:4cuda:4
out.device:cuda:4, lin:cuda:4cuda:4
out.device:cuda:2, lin:cuda:2cuda:2
out.device:cuda:0, lin:cuda:0cuda:0out.device:cuda:2, lin:cuda:2cuda:2

out.device:cuda:0, lin:cuda:0cuda:0

Do you know how to fix it? E.g. how to force the parameters of my Linear object to the desired device? Thanks in advance! 
I am using torch 1.4.0 and torch_geometric 1.4.2.

**Comment by Wenhao-Jin** [comment]
Oops, I will close this issue. I fixed it by changing the list of Linear objects to torch.nn.ModuleList format, which allows the "model.to(device)" to affect the Linear objects in the list.
`self.lins = [torch.nn.Linear(self.GNN_num_hidden_list[1],self.MLP_num_hidden_list[0])]
        for i in range(1, len(self.MLP_num_hidden_list)):
            self.lins.append(torch.nn.Linear(self.MLP_num_hidden_list[i-1],self.MLP_num_hidden_list[i]))
        
        self.lins.append(torch.nn.Linear(MLP_num_hidden_list[-1], 5))  
        **self.lins=ModuleList(self.lins)** ## Add this to make "model.to(device)" effective to the linear object list.
`
