### ISSUE TITLE
Overriding __inc__ function of Data

### ISSUE THREAD

**Issue by wentaoveggiebird** [rusty1s/pytorch_geometric#1499]
Hello,

I'm trying to create a PairData class. I overrided the constructor and the ```__inc__``` function as mentioned by the document. Here is my toy test code: 

```Python
"""
Dataloader for the Siamese graph neural network. 
"""
import torch
from torch_geometric.data import Data, Dataset
from torch_geometric.data import DataLoader


class PairData(Data):
    """
    Paired data type. Each object has 2 graphs.
    """
    def __init__(self, edge_attr_a, edge_index_a, x_a, edge_attr_b, edge_index_b, x_b):
        super(PairData, self).__init__()
        self.edge_index_a = edge_index_a
        self.edge_attr_a = edge_attr_a
        self.x_a = x_a
        
        self.edge_index_b = edge_index_b        
        self.edge_attr_b = edge_attr_b
        self.x_b = x_b

    def __inc__(self, key, value):
        if key == 'edge_attr_a':
            return self.x_a.size(0)
        if key == 'edge_attr_b':
            return self.x_b.size(0)
        else:
            return super(PairData, self).__inc__(key, value)
    

if __name__=="__main__":
    edge_index_a = torch.tensor([
        [0, 0, 0, 0],
        [1, 2, 3, 4],
    ])
    x_a = torch.randn(5, 8)  # 5 nodes.
    edge_attr_a = torch.randn(4, 2)

    edge_index_b = torch.tensor([
        [0, 0, 0],
        [1, 2, 3],
    ])
    x_b = torch.randn(3, 8)  # 4 nodes.
    edge_attr_b = torch.randn(3, 2)

    data = PairData(edge_attr_a, edge_index_a, x_a, edge_attr_b, edge_index_b, x_b)
    print(data.keys)
    data_list = [data, data]
    loader = DataLoader(data_list, batch_size=2)
    batch_data = next(iter(loader))
```

I got the following error:
```
Traceback (most recent call last):
  File "dataloader.py", line 55, in <module>
    batch_data = next(iter(loader))
  File "/home/wentao/miniconda3/envs/pytorch-1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/wentao/miniconda3/envs/pytorch-1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wentao/miniconda3/envs/pytorch-1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/wentao/miniconda3/envs/pytorch-1/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 34, in __call__
    return self.collate(batch)
  File "/home/wentao/miniconda3/envs/pytorch-1/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 15, in collate
    return Batch.from_data_list(batch, self.follow_batch)
  File "/home/wentao/miniconda3/envs/pytorch-1/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 54, in from_data_list
    cumsum[key] = cumsum[key] + data.__inc__(key, item)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

When I modified the ```__inc__``` function as follow the error is gone:
```Python
    def __inc__(self, key, value):
        if key == 'edge_index_a':
            return self.x_a.size(0)
        if key == 'edge_index_b':
            return self.x_b.size(0)
        else:
            return super(PairData, self).__inc__(key, value)
```

However, it doesn't make sense to me because the ```x_a```  is after ```edge_attr``` in the ```keys``` list:
```
['edge_index_a', 'edge_attr_a', 'x_a', 'edge_index_b', 'edge_attr_b', 'x_b']
```

Could you please help me understand this? Thanks!

**Comment by rusty1s** [comment]
This is indeed a bit weird on a first look, but it makes kinda sense. The problem is as follows:
PyG cannot identify how to increment the values of `edge_index_a` and `edge_index_b`. By default, these values are incremented based on the output of `data.num_nodes`. However, for your pair data object, `data.num_nodes` is actually `None`, giving you the error `unsupported operand type(s) for +: 'int' and 'NoneType'`. Therefore, you also need to tell PyG how to increment `edge_index_a` and `edge_index_b`.

**Comment by wentaoveggiebird** [comment]
Ah, I was thinking about this increment in a wrong way. This increment increases the value of PyG edge indices to maintain correct batching behavior. Thanks for the explanation.

**Comment by tchaton** [comment]
Hey @rusty1s,

A PairData within PYG could be a nice to have.
