### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1518]
## 🐛 Bug

```
Traceback (most recent call last):
  File "test.py", line 252, in <module>
    logger=logger,
  File "test.py", line 88, in cross_validation_with_val_set
    val_losses.append(eval_loss(model, val_loader))
  File "test.py", line 216, in eval_loss
    out = model(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Cluster_AGPooling-master2222/c_models.py", line 60, in forward
    x, edge_index, _, batch, perm2, _ = self.pool2(x, edge_index, edge_wight, None, batch, None)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Cluster_AGPooling-master2222/c_Layers.py", line 64, in forward
    num_nodes=C_score.size(0))
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/nn/pool/topk_pool.py", line 60, in filter_adj
    row, col = row[mask], col[mask]
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

```
## To Reproduce

1.
1.
1.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Can you run your code with `CUDA_LAUNCH_BLOCKING` to see where exactly the error occurs?

**Comment by jiaruHithub** [comment]
> Can you run your code with `CUDA_LAUNCH_BLOCKING` to see where exactly the error occurs?

EM...It report the second bug.
