### ISSUE TITLE
IndexError: list index out of range when calling jittable()

### ISSUE THREAD

**Issue by yoyololicon** [rusty1s/pytorch_geometric#1531]
## 🐛 Bug

Hi, I want to use the torch.jit feature on my graph model.
I install pytorch and PyG from source on a docker machine, it runs pretty well, but when I call jittable() on the module, an index error will appear.

## To Reproduce

```python
>>>import torch
>>>import torch_geometric as geo
>>>m = geo.nn.ChebConv(4, 8, 2).jittable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/message_passing.py", line 340, in jittable
    ['message', 'aggregate', 'update'])
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/utils/inspector.py", line 42, in types
    arg_types = parse_types(func)[0][0]
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/utils/typing.py", line 95, in parse_types
    arg_types = OrderedDict((k, param_type_repr(v)) for k, v in ps.items())
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/utils/typing.py", line 95, in <genexpr>
    arg_types = OrderedDict((k, param_type_repr(v)) for k, v in ps.items())
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/utils/typing.py", line 57, in param_type_repr
    return sanitize(re.split(r': | =', str(param))[1])
IndexError: list index out of range
```
This error not only when using `ChebConv`, but also appear on other types of GNN layers.
When using `MessagePassing` a different error will appear

```python
>>>m = geo.nn.MessagePassing().jittable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/message_passing.py", line 336, in jittable
    prop_types = dict([re.split(r'\s*:\s*', t) for t in prop_types])
ValueError: dictionary update sequence element #2 has length 1; 2 is required

```

## Environment

* OS: Ubuntu 18.04.3 LTS
* Python version: 3.6.9
* PyTorch version: 1.6
* CUDA/cuDNN version: 10.1/7.6.5
* GCC version: 7.5
* Any other relevant information:
pytorch_geometric version: 1.6
Docker version: 19.03.12
Image: ufoym/deepo:latest

**Comment by rusty1s** [comment]
This might be related to Python 3.6. I need to look into it :)

**Comment by rusty1s** [comment]
Doesn't seem to be related to Python 3.6, as all tests pass with it (see [here](https://travis-ci.org/github/rusty1s/pytorch_geometric/jobs/717834951)).

**Comment by yoyololicon** [comment]
@rusty1s After upgrading to 1.6.1 this error disappeared.
