### ISSUE TITLE
How to build a simple GCN model on "ESOL" like dataset in "MoleculeNet"?

### ISSUE THREAD

**Issue by swpper** [rusty1s/pytorch_geometric#1565]
## ❓ Questions & Help

Hello, I want to build a simple GCN model for regression on molecular dataset like "ESOL" with features:
```
Data(edge_attr=[68, 3], edge_index=[2, 68], smiles="OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O ", x=[32, 9], y=[1, 1])
```
But I met a problem when I replace the "Core" dataset with "ESOL" in the example "gcn.py":

```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 12, add_self_loops=False, normalize=True)
        self.conv2 = GCNConv(12, dataset.num_classes, add_self_loops=False, normalize=True)
    def forward(self, data):
        x, edge_index, edge_weight = data.x, data.edge_index, data.edge_attr
        x = self.conv1(x, edge_index, edge_weight)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index, edge_weight)
        return F.relu(x)

model = Net()
print(model)
print(dataset[0])
print(model(dataset[0]))
```
And the outcome is :
```
Net(
  (conv1): GCNConv(9, 12)
  (conv2): GCNConv(12, 1)
)
Data(edge_attr=[68, 3], edge_index=[2, 68], smiles="OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O ", x=[32, 9], y=[1, 1])
Traceback (most recent call last):
  File "test_GCN.py", line 65, in <module>
    out = model(data); print(out)
  File "D:\Anaconda3\envs\my-rdkit-env\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test_GCN.py", line 48, in forward
    x = self.conv1(x, edge_index, edge_weight)
  File "D:\Anaconda3\envs\my-rdkit-env\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\my-rdkit-env\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 148, in forward
    self.improved, self.add_self_loops, dtype=x.dtype)
  File "D:\Anaconda3\envs\my-rdkit-env\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 63, in gcn_norm
    deg_inv_sqrt = deg.pow_(-0.5)
RuntimeError: result type Floatcan't be cast to the desired output type Long
```

Do I need to do some transform on the data or change the type of the GCN model? Can you give some advice?

**Comment by rusty1s** [comment]
You can have look here to solve your issue: https://github.com/rusty1s/pytorch_geometric/issues/1537

**Comment by swpper** [comment]
@rusty1s Thank you very much.
