### ISSUE TITLE
Using torch_geometric.datasets.ZINC throws OSError

### ISSUE THREAD

**Issue by alstonlo** [rusty1s/pytorch_geometric#1602]
## 🐛 Bug

Creating a ZINC dataset object throws an  `OSError: [Errno 22] Invalid argument`. The ZINC dataset downloads from the url: https://www.dropbox.com/s/feo9qle74kg48gy/molecules.zip?dl=1. Afterwards, line 33 in `download.py` (https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/download.py#L33) is eventually run with: 
```
with open('XXXXX/molecules.zip?dl=1', 'wb') as f:
```
The question mark in the file extension is what seems to cause the error, as running the same line without the question mark works without error.

## To Reproduce

Running the following code:

```
from torch_geometric.datasets import ZINC

ZINC(root='')
```

throws this error:
```
Downloading https://www.dropbox.com/s/feo9qle74kg48gy/molecules.zip?dl=1
Traceback (most recent call last):
  File "****", line 3, in <module>
    ZINC(root='')
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\datasets\zinc.py", line 52, in __init__
    super(ZINC, self).__init__(root, transform, pre_transform, pre_filter)
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 53, in __init__
    super(InMemoryDataset, self).__init__(root, transform, pre_transform,
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\data\dataset.py", line 89, in __init__
    self._download()
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\datasets\zinc.py", line 74, in download
    path = download_url(self.url, self.root)
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\data\download.py", line 33, in download_url
    with open(path, 'wb') as f:
OSError: [Errno 22] Invalid argument: '.\\molecules.zip?dl=1'
```

## Environment

* OS: Windows 10
* Python version: 3.8.5
* PyTorch version: 1.6.0
* CUDA/cuDNN version: cpu

**Comment by rusty1s** [comment]
That's interesting. The suffix `?dl=1` is actually needed to download the correct zip file. I'm not sure how to fix that :(

As an alternative, you can download the file manually and put it into the `raw/` folder.

**Comment by alstonlo** [comment]
No worries, and thank you for the solution! As you suggested, I got it to work by downloading from the dropbox, extracting the downloaded `molecules.zip` file, and then putting the contents in a `root/raw/` folder. Then I commented out lines 73-77 in `zinc.py` (https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/zinc.py#L73).
