### ISSUE TITLE
running error in negative_sampling

### ISSUE THREAD

**Issue by AllenWu18** [rusty1s/pytorch_geometric#163]
## ❓ Questions & Help

Well, I just used my own dataset to use the VGAE, and I have managed my data into the 
torch_geometric.data.data.Data which has the similar form to the Cora_data(dataset[0])
but when I run the code ,there showed some error:

 runfile('/Users/jishilun/Desktop/load_data.py', wdir='/Users/jishilun/Desktop')
Traceback (most recent call last):

  File "<ipython-input-108-ae484e68943a>", line 1, in <module>
    runfile('/Users/jishilun/Desktop/load_data.py', wdir='/Users/jishilun/Desktop')

  File "/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/jishilun/Desktop/load_data.py", line 151, in <module>
    train()

  File "/Users/jishilun/Desktop/load_data.py", line 136, in train
    loss = model.recon_loss(z, data.train_pos_edge_index)

  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/models/autoencoder.py", line 149, in recon_loss
    neg_edge_index = self.negative_sampling(pos_edge_index, z.size(0))

  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/models/autoencoder.py", line 130, in negative_sampling
    perm[rest] = tmp

RuntimeError: shape mismatch: value tensor of shape [2] cannot be broadcast to indexing result of shape [2, 1]

here I got the data of z and data.train_pos_edge_index 
and fed them into the function to test, and there did't show the error,
but when running the main function, the error appears.
How can I deal with that?
Thank you!

**Comment by rusty1s** [comment]
Fixed in master. Thanks!

**Comment by rusty1s** [comment]
Would be interested in the running time of negative sampling for rather small graphs. If you notice a lack in speed, let me know.
