### ISSUE TITLE
GATConv IndexError when x_src.size(0) < x_dst.size(0)

### ISSUE THREAD

**Issue by alstonlo** [rusty1s/pytorch_geometric#1631]
## ❓ Questions & Help

Hi, I was trying to use GATConv on a bipartite graph, but I kept on running into an error `IndexError: index out of range in self` when the number of source nodes is less than the number of target nodes! I was wondering if I was perhaps misusing GATConv, or if this is a bug. Thanks! 

## To Reproduce

```
import torch
import torch_geometric as pyg

conv = pyg.nn.GATConv(in_channels=(1, 1),
                      out_channels=1,
                      heads=1)

x_src = torch.tensor([[0.0], [0.1]])
x_dst = torch.tensor([[0.0], [0.1], [0.2], [0.3]])

src2dst_edge_index = torch.tensor([
    [0, 1, 1, 1],
    [0, 1, 2, 3]
], dtype=torch.long)

conv((x_src, x_dst), src2dst_edge_index,
     size=(x_src.size(0), x_dst.size(0)))
```
raises this error
```
Traceback (most recent call last):
  File "****", line 16, in <module>
    conv((x_src, x_dst), src2dst_edge_index,
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\nn\conv\gat_conv.py", line 149, in forward
    out = self.propagate(edge_index, x=(x_l, x_r),
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 232, in propagate
    coll_dict = self.__collect__(self.__user_args__, edge_index, size,
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 157, in __collect__
    data = self.__lift__(data, edge_index,
  File "C:\Users\****\anaconda3\envs\****\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 127, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
```

## Environment

* OS: Windows 10
* Python version: 3.8.5
* PyTorch version: 1.6.0
* CUDA/cuDNN version: cpu
* PyTorch Geometric version: 1.6.1

**Comment by rusty1s** [comment]
Actually, you are not using it wrong. This is an unintended behaviour, and it is fixed in master now. You can fix it by preventing `GATConv` to add self-loops to your graph:
```python
GATConv(..., add_self_loops=False)
```

**Comment by alstonlo** [comment]
Thanks!
