### ISSUE TITLE
graph saint error

### ISSUE THREAD

**Issue by wohlbier** [rusty1s/pytorch_geometric#1633]
## ❓ Questions & Help

Hi, I'm trying to run the graph_saint example with my own data. I have my data stored in a torch_geometric data class. When I run I get the following error. Any ideas where to look? Thanks.

```
Traceback (most recent call last):
  File "./gs.py", line 106, in <module>
    loss = train()
  File "./gs.py", line 44, in train
    for data in loader:
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/DATA/SDH/packages/anaconda3/envs/twit_env/lib/python3.7/site-packages/torch_geometric/data/graph_saint.py", line 107, in __collate__
    if item.size(0) == self.N:
AttributeError: 'int' object has no attribute 'size'
```

**Comment by reshinthadithyan** [comment]
This means inside the collate_fn in the Saint Sampler, there is a check if the **Number of Nodes** and the **0th Dimension(Num_Nodes)** of the Feature Tensor are equal.  
Because, ideally a **Feature Tensor** should be of size **(Num_Nodes,Feature_Dim)**

**Comment by wohlbier** [comment]
Thanks. I ended up using an `InMemoryDataset` and I no longer have the problem.

**Comment by rusty1s** [comment]
Thanks for reporting. `GraphSAINT` did expect only `torch.Tensors` as attributes for `Data`. This is now fixed in master.

**Comment by mhnnunes** [comment]
Hi!

I am having this exact problem but using the `RandomNodeSampler`. Actually I have even tried to change it to `GraphSaintNodeSampler` after seeing this post but still got the same error. Could you help me debug?

Error:

```
Traceback (most recent call last):
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/mhnnunes/master/src/graphnas/main.py", line 193, in <module>
    main(args)
  File "/srv/mhnnunes/master/src/graphnas/main.py", line 188, in main
    model_selector.select()
  File "/srv/mhnnunes/master/src/graphnas/selectors/model_selector.py", line 58, in select
    self.train()
  File "/srv/mhnnunes/master/src/graphnas/selectors/rs_selector.py", line 53, in train
    self.submodel_manager.train(gnn, format=self.args.format)
  File "/srv/mhnnunes/master/src/graphnas/gnn_model_manager.py", line 97, in train
    self.run_batched_model(model, optimizer,
  File "/srv/mhnnunes/master/src/graphnas_variants/macro/pyg_gnn_model_manager.py", line 205, in run_batched_model
    for data in train_loader:
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/srv/mhnnunes/miniconda3/envs/py383/lib/python3.8/site-packages/torch_geometric/data/sampler.py", line 200, in __collate__
    if item.size(0) == self.N:
AttributeError: 'int' object has no attribute 'size'
```
Env:
```
magma-cuda101             2.5.2                         1    pytorch
mkl                       2020.2                      256
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.2.0            py38h23d657b_0
mkl_random                1.1.1            py38h0573a6f_0
networkx                  2.5                      pypi_0    pypi
numpy                     1.19.2           py38h54aff64_0
numpy-base                1.19.2           py38hfa32c7d_0
ogb                       1.2.3                    pypi_0    pypi
python                    3.8.3                hcff3b4d_2llvmlite                  0.34.0                   pypi_0    pypi
pytorch                   1.6.0           py3.8_cuda10.1.243_cudnn7.6.3_0    https://anaconda.org/pytorch/pytorch/1.6.0/download
torch-cluster             1.5.7                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.7                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
```

**Comment by rusty1s** [comment]
This is now also fixed for `RandomNodeSampler` on master. Your error suggests that you are actually not running the latest PyG from master:
```
pip uninstall torch-geometric
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by mhnnunes** [comment]
It worked! Thanks a lot!
