### ISSUE TITLE
from_networkx function returns TypeError: attribute name must be string, not 'int'

### ISSUE THREAD

**Issue by netphantom** [rusty1s/pytorch_geometric#1645]
## 🐛 Bug
Hi there, 
I am having an error when I pass a networkx graph, which nodes contain a dictionary with integer keys, to the "from_networkx" utility function. It raises a value error:

```
TypeError: attribute name must be string, not 'int'
```

## To Reproduce

```python
>>> import networkx as nx
>>> from torch_geometric.utils import from_networkx
>>> attrs = {0: {1: 20, 2: 50}, 1: {1: 21}}
>>> G = nx.path_graph(3)
>>> nx.set_node_attributes(G, attrs)
>>> G.nodes[0]
{1: 20, 2: 50}
>>> G.nodes[1]
{1: 21}
>>> G.nodes[2]
{}

g = from_networkx(G)
```
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/netp/anaconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/utils/convert.py", line 137, in from_networkx
    data = torch_geometric.data.Data.from_dict(data)
  File "/Users/netp/anaconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/data/data.py", line 105, in from_dict
    data[key] = item
  File "/Users/netp/anaconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/data/data.py", line 118, in __setitem__
    setattr(self, key, value)
TypeError: attribute name must be string, not 'int'
```

## Environment

* OS: Mac os Catalina
* Python version: 3.8.5
* PyTorch version: 1.6
* CUDA/cuDNN version: N/A

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in master. Note that in PyG, all nodes (and edges) should have the same feature dimensionality. Therefore, it is better to change `attrs` to:
```
attrs = {0: {1: 20, 2: 50}, 1: {1: 21, 2: 0}, 3: {1: 0, 2: 0}}
```
