### ISSUE TITLE
Seg fault when using my data

### ISSUE THREAD

**Issue by wohlbier** [rusty1s/pytorch_geometric#1650]
## ❓ Questions & Help

Trying to run gcn clustering on my own dataset. I run into this:

```
Computing METIS partitioning ...
munmap_chunk(): invalid pointer
```

My debugger says that the error is in `pytorch_sparse/csrc/cpu/metis_cpu.cpp` but I don't have line number information. Any ideas? Maybe I'll try to build a debug version.

**Comment by wohlbier** [comment]
Reducing the number of partitions fixed that error. Now I'm getting the following error. 32242 is the correct number of nodes, and the masks are set with that a value. I'm not sure where the 32241 comes from.
```
Computing METIS partitioning...
Done!
Epoch: 01, Loss: 569.2524
Epoch: 02, Loss: 162.9781
Epoch: 03, Loss: 129.5434
Epoch: 04, Loss: 289.1613
Evaluating: 100%|█████████████████████▉| 64482/64484 [00:01<00:00, 58300.52it/s]
Traceback (most recent call last):
  File "./gcn.py", line 105, in <module>
    train_acc, val_acc, test_acc = test()
  File "/DATA/SDH/packages/anaconda3/envs/twit_dbg_env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "./gcn.py", line 80, in test
    correct = y_pred[mask].eq(data.y[mask]).sum().item()
IndexError: The shape of the mask [32242] at index 0 does not match the shape of the indexed tensor [32241] at index 0
```

**Comment by wohlbier** [comment]
Looks like the last batch size is wrong? Uses 512 for 62 times, then uses a 497 for 32241. I think this should be 498.

**Comment by wohlbier** [comment]
I needed to add `num_nodes` to my `NeighborSampler`. Now it works.

```
     subgraph_loader = NeighborSampler(data.edge_index, sizes=[-1],
-                                      batch_size=512, shuffle=False,
-                                      num_workers=1)
+                                      num_nodes=data.num_nodes,
+                                      batch_size=16, shuffle=False,
+                                      num_workers=0)
```
