### ISSUE TITLE
Want to do binary node classification on Cora dataset

### ISSUE THREAD

**Issue by jmandivarapu1** [rusty1s/pytorch_geometric#1698]
## ❓ Questions & Help

HI,

For my given experiment I need to sudivide the cora dataset in 3 subtasks each with two classes and perform binary classification on them

Code so far:

```
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures

dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())

print()
print(f'Dataset: {dataset}:')
print('======================')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')

data = dataset[0]  # Get the first graph object.

```
FILTERING IT - GETTING INDEXES OF FIRST TASK- binary classification of 0 vs 1
```
import collections
import numpy as np
counter=collections.Counter(list(data.y.numpy()))
print(counter)
indexes=list(np.where(dataset[0].y == 1)[0])+list(np.where(dataset[0].y == 0)[0]) # Getting indexes of class 0 and class 1
```
PREPARING NEW DATASET
```
dataset= Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
dataset.data.x=dataset.data.x[indexes]
dataset.data.y=dataset.data.y[indexes]
dataset.data.train_mask=dataset.data.train_mask[indexes]
dataset.data.test_mask=dataset.data.test_mask[indexes]
dataset.data.val_mask=dataset.data.val_mask[indexes]
```

CODE FROM EXAMPLE COLAB NOTEBOOK
```
from IPython.display import Javascript  # Restrict height of output cell.
display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 300})'''))

model = GCN(hidden_channels=16)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

def train():
      model.train()
      optimizer.zero_grad()  # Clear gradients.
      out = model(data.x, data.edge_index)  # Perform a single forward pass.
      loss = criterion(out[data.train_mask], data.y[data.train_mask])  # Compute the loss solely based on the training nodes.
      loss.backward()  # Derive gradients.
      optimizer.step()  # Update parameters based on gradients.
      return loss

def test():
      model.eval()
      out = model(data.x, data.edge_index)
      pred = out.argmax(dim=1)  # Use the class with highest probability.
      test_correct = pred[data.test_mask] == data.y[data.test_mask]  # Check against ground-truth labels.
      test_acc = int(test_correct.sum()) / int(data.test_mask.sum())  # Derive ratio of correct predictions.
      return test_acc


for epoch in range(1, 401):
    loss = train()
    print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}')
```

**ERROR: SO NEED HELP IN COORRECTLY FILTERING THE EDGE INDEX or LOOKING FOR ANYOTHER SIMPLER WAY**

```
/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/gcn_conv.py in gcn_norm(edge_index, edge_weight, num_nodes, improved, add_self_loops, dtype)
     60 
     61         row, col = edge_index[0], edge_index[1]
---> 62         deg = scatter_add(edge_weight, col, dim=0, dim_size=num_nodes)
     63         deg_inv_sqrt = deg.pow_(-0.5)
     64         deg_inv_sqrt.masked_fill_(deg_inv_sqrt == float('inf'), 0)

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_scatter/scatter.py", line 22, in scatter_add
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
RuntimeError: index 633 is out of bounds for dimension 0 with size 568
```

**Comment by rusty1s** [comment]
You can use `torch_geometric.utils.subgraph` to get a subgraph out of `edge_index` containing only the nodes in `indices`.

**Comment by jmandivarapu1** [comment]
> torch_geometric.utils.subgraph

Thank you for your quick reply. Can you help me with the below error og edge_weights


```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-59-00762e44edae> in <module>()
     25 
     26 for epoch in range(1, 401):
---> 27     loss = train()
     28     print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}')

5 frames
/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/gcn_conv.py in gcn_norm(edge_index, edge_weight, num_nodes, improved, add_self_loops, dtype)
     60 
     61         row, col = edge_index[0], edge_index[1]
---> 62         deg = scatter_add(edge_weight, col, dim=0, dim_size=num_nodes)
     63         deg_inv_sqrt = deg.pow_(-0.5)
     64         deg_inv_sqrt.masked_fill_(deg_inv_sqrt == float('inf'), 0)

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_scatter/scatter.py", line 22, in scatter_add
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
RuntimeError: index 2544 is out of bounds for dimension 0 with size 568
```

**Comment by rusty1s** [comment]
You need to pass `relabel_nodes=True` to the `subgraph` call. Sorry to have missed that :)
