### ISSUE TITLE
Using ToSparseTensor in GNN leads to RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2834646]] is at version 5; expected version 3 instead.

### ISSUE THREAD

**Issue by pohjie** [rusty1s/pytorch_geometric#1722]
❓ Questions & Help

I am using T.ToSparseTensor() in this manner: 
```
GCNData_pro = T.ToSparseTensor(remove_edge_index=False)(DATA.Data(x=torch.Tensor(target_features),
                       edge_index=torch.LongTensor(target_edge_index).transpose(1, 0),
                       y=torch.FloatTensor([labels])))

```
and using `adj_t` accordingly. However, when I reach global pooling `xt = gep(xt, target_batch)`, I run into this error:

```
  File "training_5folds.py", line 69, in <module>
    train(model, device, train_loader, optimizer, epoch + 1)
  File "/home/pohjie/DGraphDTA/utils.py", line 110, in train
    loss.backward()
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2834646]] is at version 5; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
Not using ToSparseTensor will avoid this problem, so I'm guessing it's ToSparseTensor that is leading to some changes. Thank you.

**Comment by rusty1s** [comment]
Can you show me your model to reproduce this?

**Comment by pohjie** [comment]
Sure. Thanks for the extremely prompt response as always. I hope you don't mind me linking you to the model on [GitHub](https://github.com/pohjie/DGraphDTA/blob/speedup/gnn.py)- I thought of copying parts of the model over here but I may miss what is causing the issue.

If I modify 'target_edge_index` in line 43 to use `data_pro.edge_index` and not call ToSparseTensor in another file (`utils.py`) then the training runs smoothly.

**Comment by rusty1s** [comment]
Your code looks correct to me. Can you apply the suggestion and see which op fails to compute gradients?
```
Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by pohjie** [comment]
Hello here's what I got:

```
[W python_anomaly_mode.cpp:60] Warning: Error detected in torch::autograd::CppNode<SPMMSum>. Traceback of forward call that caused the error:
  File "training_5folds.py", line 69, in <module>
    train(model, device, train_loader, optimizer, epoch + 1)
  File "/home/pohjie/DGraphDTA/utils.py", line 108, in train
    output = model(data_mol, data_pro)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pohjie/DGraphDTA/gnn.py", line 83, in forward
    xt = self.pro_conv2(xt, target_edge_index)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 169, in forward
    size=None)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 225, in propagate
    out = self.message_and_aggregate(edge_index, **msg_aggr_kwargs)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 180, in message_and_aggregate
    return matmul(adj_t, x, reduce=self.aggr)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch_sparse/matmul.py", line 116, in matmul
    return spmm(src, other, reduce)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch_sparse/matmul.py", line 66, in spmm
    return spmm_sum(src, other)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch_sparse/matmul.py", line 23, in spmm_sum
    csr2csc, other)
 (function print_stack)
Traceback (most recent call last):
  File "training_5folds.py", line 69, in <module>
    train(model, device, train_loader, optimizer, epoch + 1)
  File "/home/pohjie/DGraphDTA/utils.py", line 110, in train
    loss.backward()
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/pohjie/anaconda3/envs/fyp/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2834646]] is at version 5; expected version 3 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

I'm not sure how to fix this; I really appreciate your help thank you!

**Comment by rusty1s** [comment]
Can you do me a favor and try out `SAGEConv` instead of `GCNConv` and see if that succeeds?

**Comment by pohjie** [comment]
I found the bug- both `SAGEConv` and `GCNConv` work provided that `add_self_loops` is not set to `True`.

**Comment by smorad** [comment]
I am getting a similar error that setting `add_self_loops=False` does not seem to fix.

The offending code:
```
self.gcn0 = torch_geometric.nn.GCNConv(self.obs_dim, self.gcn_h_size, add_self_loops=False)
self.gcn1 = torch_geometric.nn.GCNConv(self.gcn_h_size, self.gcn_outsize, add_self_loops=False)
...
edge_list, _ = torch_geometric.utils.dense_to_sparse(adj_mat)
# TODO: GCN causing in-place issue
out = F.relu(self.gcn0(nodes, edge_list))
out = F.relu(self.gcn1(out, edge_list))
```
And `torch.autograd.set_anomaly` backtrace:
```
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/execution/train_ops.py", line 63, in __call__
    info = do_minibatch_sgd(
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/utils/sgd.py", line 133, in do_minibatch_sgd
    batch_fetches = (local_worker.learn_on_batch(
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 871, in learn_on_batch
    info_out[pid] = policy.learn_on_batch(batch)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/policy/torch_policy.py", line 356, in learn_on_batch
    grads, fetches = self.compute_gradients(postprocessed_batch)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/policy/torch_policy.py", line 389, in compute_gradients
    self._loss(self, self.model, self.dist_class, train_batch))
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/agents/ppo/ppo_torch_policy.py", line 46, in ppo_surrogate_loss
    logits, state = model.from_batch(train_batch, is_training=True)
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/modelv2.py", line 245, in from_batch
    ret = self.__call__(input_dict, states, input_dict.get("seq_lens"))
  File "/usr/local/lib/python3.8/dist-packages/ray/rllib/models/modelv2.py", line 215, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/root/vnav/src/models/ray_graph.py", line 170, in forward
    out = F.relu(self.gcn0(nodes, edge_list))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/nn/conv/gcn_conv.py", line 178, in forward
    x = torch.matmul(x, self.weight)
```

**Comment by smorad** [comment]
For anyone else running into this issue, I solved the problem by using `tensor.data`:

```
self.gcn0 = torch_geometric.nn.GCNConv(self.obs_dim, self.gcn_h_size, add_self_loops=False)
self.gcn1 = torch_geometric.nn.GCNConv(self.gcn_h_size, self.gcn_outsize, add_self_loops=False)
...
edge_list, _ = torch_geometric.utils.dense_to_sparse(adj_mat)
# TODO: GCN causing in-place issue
out = F.relu(self.gcn0(nodes.data, edge_list))
out = F.relu(self.gcn1(out, edge_list))
```

**Comment by rusty1s** [comment]
This works for me without any problem:
```python
import torch
import torch_geometric


class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.gcn0 = torch_geometric.nn.GCNConv(16, 16)
        self.gcn1 = torch_geometric.nn.GCNConv(16, 16)

    def forward(self, nodes, adj_mat):
        edge_list, _ = torch_geometric.utils.dense_to_sparse(adj_mat)
        out = self.gcn0(nodes, edge_list).relu()
        out = self.gcn1(out, edge_list).relu()
        return out


nodes = torch.randn(100, 16)
adj_mat = torch.randn(100, 100)

model = Net()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

out = model(nodes, adj_mat)
loss = torch.nn.functional.mse_loss(out, torch.randn(100, 16))
loss.backward()
```
Can you confirm that this works for you? Otherwise, this might be already fixed in PyG master:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by smorad** [comment]
Your snippet runs correctly for me. I'm running this within `rllib` which likely contributes to this. I have various other `torch.nn` layers that seem to work fine:

```
(Pdb) self.variables
<bound method TorchModelV2.variables of RayObsGraph(
  (simple): SlimFC(
    (_model): Sequential(
      (0): Linear(in_features=2052, out_features=6, bias=True)
    )
  )
  (gcn0): GraphConv(2052, 256)
  (gcn1): GraphConv(256, 1024)
  (logit_branch): SlimFC(
    (_model): Sequential(
      (0): Linear(in_features=1024, out_features=6, bias=True)
    )
  )
  (value_branch): SlimFC(
    (_model): Sequential(
      (0): Linear(in_features=1024, out_features=1, bias=True)
    )
  )
  (edge_predictor): Sequential(
    (0): Linear(in_features=2048, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=1, bias=True)
    (3): Tanh()
  )
)>
```

It's not clear to my why `autograd` reports `matmul(x, weight)` as the culprit, it seems like a differentiable operation. I'll do some digging and see what I find.
