### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found

### ISSUE THREAD

**Issue by AvisP** [rusty1s/pytorch_geometric#1740]
Hi,

I followed the instruction mentioned in the main [page](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html)

OS : Windows 10 (Anaconda)
Python version: 3.7.5
Cuda : 10.2 ( although multiple versions installed)

Including the outputs of the checks

` print(torch.__version__)`
`1.6.0.dev20200518`

`print(torch.version.cuda)`
`10.2`

` print(torch.cuda.is_available())`
`True`

Based on this I did the following installation 

`pip install torch-scatter==latest+cu102 torch-sparse==latest+cu102 torch-cluster==latest+cu102 torch-spline-conv==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html`

`pip install torch-geometric==1.6.0`

Everything installed successfully but I am getting the following error. Sorry the following formatting is messed up. Kindly help.

Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch_geometric.data import Data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch_sparse\__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "C:\Users\ME\Anaconda3\envs\tf-gpu5\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

**Comment by rusty1s** [comment]
This is a weird PyTorch error, and I already encountered it by myself. There are also a lot of users reporting [similar problems](https://discuss.pytorch.org/t/winerror-126-when-import-torch/80249/8). I personally fixed it by just setting up a fresh miniconda environment.

**Comment by PochiiBoy** [comment]
> This is a weird PyTorch error, and I already encountered it myself. There are also a lot of users reporting [similar problems](https://discuss.pytorch.org/t/winerror-126-when-import-torch/80249/8). I personally fixed it by just setting up a fresh miniconda environment.

how would one go about doing that?
