### ISSUE TITLE
Installation error on Cuda 11.0

### ISSUE THREAD

**Issue by Atomwh** [rusty1s/pytorch_geometric#1746]
## 📚 Installation

<!-- 
I follow the installation steps of the official [website](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-via-binaries), and there is no errors. But when I import this library, an error occurs:
`
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_sparse/__init__.py", line 35, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_sparse/tensor.py", line 11, in <module>
    class SparseTensor(object):
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch/jit/_script.py", line 924, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch/jit/_script.py", line 64, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
Expected a default value of type Tensor (inferred) on parameter "tensor".Because "tensor" was not annotated with an explicit type it is assumed to be type 'Tensor'.:
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_sparse/tensor.py", line 126
    def type_as(self, tensor=torch.Tensor):
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        value = self.storage.value()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if value is None or tensor.dtype == value.dtype:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            return self
            ~~~~~~~~~~~
        return self.from_storage(self.storage.type_as(tensor))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

` 
I can not find similar solutions and need your help!
 -->

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7.4
* PyTorch version: 1.8.0.dev20201011+cu110
* CUDA/cuDNN version:  Build cuda_11.0_bu.TC445_37.28540450_0
* GCC version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):  Installation from Source obey the official steps [here ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-via-binaries).
* Any other relevant information:
GPU: RTX 3080
Nvidia-driver: 455.23.04
The basic info of GPU by run  `/usr/local/cuda/extras/demo_suite/deviceQuery`:
`
/usr/local/cuda/extras/demo_suite/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce RTX 3080"
  CUDA Driver Version / Runtime Version          11.1 / 11.0
  CUDA Capability Major/Minor version number:    8.6
  Total amount of global memory:                 10017 MBytes (10503323648 bytes)
MapSMtoCores for SM 8.6 is undefined.  Default to use 64 Cores/SM
MapSMtoCores for SM 8.6 is undefined.  Default to use 64 Cores/SM
  (68) Multiprocessors, ( 64) CUDA Cores/MP:     4352 CUDA Cores
  GPU Max Clock rate:                            1800 MHz (1.80 GHz)
  Memory Clock rate:                             9501 Mhz
  Memory Bus Width:                              320-bit
  L2 Cache Size:                                 5242880 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.1, CUDA Runtime Version = 11.0, NumDevs = 1, Device0 = GeForce RTX 3080
Result = PASS
`


## Checklist

- [ Yes] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [Yes ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [Yes ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ Yes] I do have multiple CUDA versions on my machine.

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by Atomwh** [comment]
The error info when I import pytorch_geometric:

Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_sparse/__init__.py", line 35, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_sparse/tensor.py", line 11, in <module>
    class SparseTensor(object):
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch/jit/_script.py", line 924, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch/jit/_script.py", line 64, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
Expected a default value of type Tensor (inferred) on parameter "tensor".Because "tensor" was not annotated with an explicit type it is assumed to be type 'Tensor'.:
  File "/home/haowei/anaconda3/envs/cellDet/lib/python3.7/site-packages/torch_sparse/tensor.py", line 126
    def type_as(self, tensor=torch.Tensor):
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        value = self.storage.value()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if value is None or tensor.dtype == value.dtype:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            return self
            ~~~~~~~~~~~
        return self.from_storage(self.storage.type_as(tensor))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

Need your help !

**Comment by Atomwh** [comment]
I got it!
It is the error of torch_sparse and the solution is [here](https://github.com/rusty1s/pytorch_sparse/issues/87) 

Just alter the line 126 in the file tensor.py from:
`def type_as(self, tensor=torch.Tensor):` to 
`def type_as(self, tensor:torch.Tensor):`
