### ISSUE TITLE
Can Not Load The Model On Android Mobile Phone

### ISSUE THREAD

**Issue by zhangxiann** [rusty1s/pytorch_geometric#1756]
## To Reproduce

1. save the gcn model to pt file 
    ```
    script_model = torch.jit.trace(model, [data.edge_index, data.pos, data.x, data.y])
    script_model.save("gcn.pt")
    ```
2. load the `gcn.pt` using pytorch mobile in Anroid Studio.
    ```
    model = Module.load("gcn.pt");
    ```

3. An error occurs:
```
2020-10-24 16:04:09.873 22468-22468/com.heu.model E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.heu.model, PID: 22468
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.heu.model/com.heu.model.MainActivity}: com.facebook.jni.CppException: 
    undefined value unchecked_cast:
    at code/__torch__/torch_scatter/scatter.py:42:18
        index: Tensor,
        dim: int=-1,
        out: Optional[Tensor]=None,
        dim_size: Optional[int]=None) -> Tensor:
      _6 = __torch__.torch_scatter.utils.broadcast
      index0 = _6(index, src, dim, )
      if torch.__is__(out, None):
        size = torch.size(src)
        if torch.__isnot__(dim_size, None):
          dim_size1 = unchecked_cast(int, dim_size)
                      ~~~~~~~~~~~~~~ <--- HERE
          _8 = torch._set_item(size, dim, dim_size1)
        else:
          if torch.eq(torch.numel(index0), 0):
            _9 = torch._set_item(size, dim, 0)
          else:
            _10 = torch.add(int(torch.max(index0)), 1)
            _11 = torch._set_item(size, dim, _10)
        out1 = torch.zeros(size, dtype=ops.prim.dtype(src), layout=None, device=ops.prim.device(src), pin_memory=None)
        _7 = torch.scatter_add_(out1, dim, index0, src)
    Compiled from code 'scatter_sum' is being compiled since it was called from 'scatter_mean'
    at code/__torch__/torch_scatter/scatter.py:14:2
        out: Optional[Tensor]=None,
        dim_size: Optional[int]=None) -> Tuple[Tensor, Tensor]:
      _0, _1 = ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
      return (_0, _1)
    def scatter_mean(src: Tensor,
        index: Tensor,
        dim: int=-1,
        out: Optional[Tensor]=None,
        dim_size: Optional[int]=None) -> Tensor:
      _2 = __torch__.torch_scatter.scatter.scatter_sum
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      _3 = __torch__.torch_scatter.utils.broadcast
      out0 = _2(src, index, dim, out, dim_size, )
      dim_size0 = torch.size(out0, dim)
      if torch.lt(dim, 0):
        index_dim = torch.add(dim, torch.dim(src))
      else:
        index_dim = dim
      if torch.le(torch.dim(index), index_dim):
        index_dim0 = torch.sub(torch.dim(index), 1)
    Compiled from code 'scatter_mean' is being compiled since it was called from '__torch__.torch.nn.modules.module.Module.forward'
    at code/__torch__/torch/nn/modules/module.py:14:4
      mu : Tensor
      training : bool
      sigma : Tensor
      bias : Tensor
      root : Tensor
      def forward(self: __torch__.torch.nn.modules.module.Module,
        x: Tensor,
        edge_index: Tensor,
        pseudo: Tensor) -> Tensor:
        _0 = __torch__.torch_scatter.scatter.scatter_mean
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        _1 = self.bias
        _2 = self.root
        _3 = self.sigma
        _4 = self.mu
        _5 = self.g
        N = ops.prim.NumToTensor(torch.size(x, 0))
        _6 = int(N)
        tensor = torch.view(torch.matmul(x, _5), [_6, 4, 64])
        x_j = torch.index_select(tensor, 0, torch.select(edge_index, 0, 0))
    Compiled from code 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: com.facebook.jni.CppException: 
    undefined value unchecked_cast:
    at code/__torch__/torch_scatter/scatter.py:42:18
        index: Tensor,
        dim: int=-1,
        out: Optional[Tensor]=None,
        dim_size: Optional[int]=None) -> Tensor:
      _6 = __torch__.torch_scatter.utils.broadcast
      index0 = _6(index, src, dim, )
      if torch.__is__(out, None):
2020-10-24 16:04:09.874 22468-22468/com.heu.model E/AndroidRuntime:     size = torch.size(src)
        if torch.__isnot__(dim_size, None):
          dim_size1 = unchecked_cast(int, dim_size)
                      ~~~~~~~~~~~~~~ <--- HERE
          _8 = torch._set_item(size, dim, dim_size1)
        else:
          if torch.eq(torch.numel(index0), 0):
            _9 = torch._set_item(size, dim, 0)
          else:
            _10 = torch.add(int(torch.max(index0)), 1)
            _11 = torch._set_item(size, dim, _10)
        out1 = torch.zeros(size, dtype=ops.prim.dtype(src), layout=None, device=ops.prim.device(src), pin_memory=None)
        _7 = torch.scatter_add_(out1, dim, index0, src)
    Compiled from code 'scatter_sum' is being compiled since it was called from 'scatter_mean'
    at code/__torch__/torch_scatter/scatter.py:14:2
        out: Optional[Tensor]=None,
        dim_size: Optional[int]=None) -> Tuple[Tensor, Tensor]:
      _0, _1 = ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
      return (_0, _1)
    def scatter_mean(src: Tensor,
        index: Tensor,
        dim: int=-1,
        out: Optional[Tensor]=None,
        dim_size: Optional[int]=None) -> Tensor:
      _2 = __torch__.torch_scatter.scatter.scatter_sum
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      _3 = __torch__.torch_scatter.utils.broadcast
      out0 = _2(src, index, dim, out, dim_size, )
      dim_size0 = torch.size(out0, dim)
      if torch.lt(dim, 0):
        index_dim = torch.add(dim, torch.dim(src))
      else:
        index_dim = dim
      if torch.le(torch.dim(index), index_dim):
        index_dim0 = torch.sub(torch.dim(index), 1)
    Compiled from code 'scatter_mean' is being compiled since it was called from '__torch__.torch.nn.modules.module.Module.forward'
    at code/__torch__/torch/nn/modules/module.py:14:4
      mu : Tensor
      training : bool
      sigma : Tensor
      bias : Tensor
      root : Tensor
      def forward(self: __torch__.torch.nn.modules.module.Module,
        x: Tensor,
        edge_index: Tensor,
        pseudo: Tensor) -> Tensor:
        _0 = __torch__.torch_scatter.scatter.scatter_mean
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        _1 = self.bias
        _2 = self.root
        _3 = self.sigma
        _4 = self.mu
        _5 = self.g
        N = ops.prim.NumToTensor(torch.size(x, 0))
        _6 = int(N)
        tensor = torch.view(torch.matmul(x, _5), [_6, 4, 64])
        x_j = torch.index_select(tensor, 0, torch.select(edge_index, 0, 0))
    Compiled from code 
        at org.pytorch.Module$NativePeer.initHybrid(Native Method)
        at org.pytorch.Module$NativePeer.<init>(Module.java:70)
        at org.pytorch.Module.<init>(Module.java:25)
        at org.pytorch.Module.load(Module.java:21)
        at com.heu.model.MainActivity.onCreate(MainActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        	... 11 more
```    

## Expected behavior

The model should be loaded successfully.

## Environment

* OS: Windows10
* Python version: 3.6.1
* PyTorch version: 1.3.1
* CUDA/cuDNN version: None
* GCC version: None
* Any other relevant information: The error message seems that the pytorch mobile can not load the functions like `torch_scatter` . How could I use graph model on Android mobile phone?

**Comment by rusty1s** [comment]
Did you try to also install the `torch-scatter` C++ API, see [here](https://github.com/rusty1s/pytorch_scatter#c-api)?

**Comment by zhangxiann** [comment]
Thanks, I will try
