### ISSUE TITLE
graph_sage example code

### ISSUE THREAD

**Issue by moonwalker12138** [rusty1s/pytorch_geometric#1770]
## ❓ Questions & Help

Hello, when I run the graph_sage example code (copy from `pytorch_geometric/examples/graph_sage_unsup.py`), somthing goes wrong, may I ask if this is caused by a version problem?

```
Traceback (most recent call last):
  File "/home/yf/code/gnn_explainer/examples/graphsage_Cora.py", line 117, in <module>
    loss = train()
  File "/home/yf/code/gnn_explainer/examples/graphsage_Cora.py", line 83, in train
    for batch_size, n_id, adjs in train_loader:
  File "/home/yf/app/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/yf/app/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/yf/app/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/yf/code/gnn_explainer/examples/graphsage_Cora.py", line 38, in sample
    return super(NeighborSampler, self).sample(batch)
  File "/home/yf/app/anaconda3/lib/python3.6/site-packages/torch_geometric/data/sampler.py", line 109, in sample
    adj, n_id = self.adj.sample_adj(n_id, size, replace=False)
AttributeError: 'SparseTensor' object has no attribute 'sample_adj'
```

Versions
```
python: 3.6.6
pytorch: 1.4.0
cuda: 10.0
torch_sparse: 0.6.1
torch_geometric: 1.6.1
```

**Comment by rusty1s** [comment]
You need to update `torch-sparse` to version `0.6.4` at least.

**Comment by moonwalker12138** [comment]
Got it! Thank you very much for your reply ^-^

**Comment by moonwalker12138** [comment]
Sorry to bother you again, but after I update `torch-sparse` to version `0.6.7` and run `import torch_sparse` in python interpreter, another problem arose.

```
RuntimeError: 
Tried to access nonexistent attribute or method 'dtype' of type 'int'.:
  File "/home/yf/app/anaconda3/envs/pyg/lib/python3.6/site-packages/torch_sparse/storage.py", line 284
        row = idx // num_cols
        col = idx % num_cols
        assert row.dtype == torch.long and col.dtype == torch.long
               ~~~~~~~~~ <--- HERE

        return SparseStorage(row=row, rowptr=None, col=col, value=self._value,
```

updated versions
```
torch: 1.4.0+cu100
torch-cluster: 1.5.4
torch-geometric: 1.6.1
torch-scatter: 2.0.4
torch-sparse: 0.6.7
torch-spline-conv: 1.2.0  
```

**Comment by rusty1s** [comment]
Yeah, that's caused by PyTorch 1.4.0 and `torch-sparse>=0.6.1`. You can replace
```python
row = idx // num_cols
```
with
```python
row = idx / num_cols
```
in `/home/yf/app/anaconda3/envs/pyg/lib/python3.6/site-packages/torch_sparse/storage.py` line 282. That should fix this error on PyTorch 1.4.0.

**Comment by moonwalker12138** [comment]
Thanks again for your help, but unfortunately another problem appeared when I replace ` row = idx // num_cols ` with ` row = idx / num_cols `(no other changes) and run ` import torch_sparse `
```
RuntimeError: 
Unknown type name 'torch.device':
  File "/home/yf/app/anaconda3/envs/pyg/lib/python3.6/site-packages/torch_sparse/tensor.py", line 77
    @classmethod
    def eye(self, M: int, N: Optional[int] = None, has_value: bool = True,
            dtype: Optional[int] = None, device: Optional[torch.device] = None,
                                                          ~~~~~~~~~~~~ <--- HERE
            fill_cache: bool = False):
```

**Comment by rusty1s** [comment]
I see. What happens if you remove the `@torch.jit.script` annotations in `torch_sparse/storage.py` and `torch_sparse/tensor.py`? Removing this should lead to backward compatibility.

**Comment by moonwalker12138** [comment]
It worked!!! Thanksssssss😊
