### ISSUE TITLE
Changes to reddit.py so that it will run on Windows 10

### ISSUE THREAD

**Issue by chrisba73** [rusty1s/pytorch_geometric#1774]
## 🐛 Bug

I needed to make the following changes to reddit.py, for it to run on Windows:
* num_workers =1, for train_loader and subgraph_loader, so:
```
from sys import platform
num_workers = 1 if platform == "win32" else 12
train_loader = NeighborSampler(data.edge_index, node_idx=data.train_mask,
                               sizes=[25, 10], batch_size=1024, shuffle=True,
                               num_workers=num_workers)
subgraph_loader = NeighborSampler(data.edge_index, node_idx=None, sizes=[-1],
                                  batch_size=1024, shuffle=False,
                                  num_workers=num_workers)
```

* At the bottom, encase within `if __name__ == "__main__":`
```
if __name__ == "__main__":
    for epoch in range(1, 11):
        loss, acc = train(epoch)
        print(f'Epoch {epoch:02d}, Loss: {loss:.4f}, Approx. Train: {acc:.4f}')
        train_acc, val_acc, test_acc = test()
        print(f'Train: {train_acc:.4f}, Val: {val_acc:.4f}, '
            f'Test: {test_acc:.4f}')
```

* OS: Windows 10
* Python version: 3.8
* PyTorch version: 1.6
* CUDA/cuDNN version: 10.1

**Comment by rusty1s** [comment]
Thanks for the feedback. Any reason why `num_workers` does not work on Windows? What's the error message?

**Comment by chrisba73** [comment]
Here's the error message.  I'm running out of memory or virtual memory:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Anaconda3\envs\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Anaconda3\envs\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\envs\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Anaconda3\envs\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Anaconda3\envs\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Anaconda3\envs\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\PyTorch\pytorch_geometric\examples\reddit.py", line 19, in <module>
    subgraph_loader = NeighborSampler(data.edge_index, node_idx=None, sizes=[-1],
  File "C:\Anaconda3\envs\Python38\lib\site-packages\torch_geometric\data\sampler.py", line 85, in __init__
    adj = adj.t() if flow == 'source_to_target' else adj
  File "C:\Anaconda3\envs\Python38\lib\site-packages\torch_sparse\transpose.py", line 34, in <lambda>
    SparseTensor.t = lambda self: t(self)
  File "C:\Anaconda3\envs\Python38\lib\site-packages\torch_sparse\transpose.py", line 8, in t
    csr2csc = src.storage.csr2csc()
  File "C:\Anaconda3\envs\Python38\lib\site-packages\torch_sparse\storage.py", line 348, in csr2csc
    csr2csc = idx.argsort()
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 916927136 bytes. Buy new RAM!
```
Playing with this some more (I was in a hurry last night), a better fix is to encase all initialization under `if __name__ == "__main__":`
```
if __name__ == "__main__":
    path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'Reddit')
    dataset = Reddit(path)
    data = dataset[0]

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = SAGE(dataset.num_features, 256, dataset.num_classes)
    model = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

    x = data.x.to(device)
    y = data.y.squeeze().to(device)

    num_workers = 1 if platform == "win32" else 12
    train_loader = NeighborSampler(data.edge_index, node_idx=data.train_mask,
                                sizes=[25, 10], batch_size=1024, shuffle=True,
                                num_workers=num_workers)
    subgraph_loader = NeighborSampler(data.edge_index, node_idx=None, sizes=[-1],
                                    batch_size=1024, shuffle=False,
                                    num_workers=num_workers)
    for epoch in range(1, 11):
        loss, acc = train(epoch)
        print(f'Epoch {epoch:02d}, Loss: {loss:.4f}, Approx. Train: {acc:.4f}')
        train_acc, val_acc, test_acc = test()
        print(f'Train: {train_acc:.4f}, Val: {val_acc:.4f}, '
            f'Test: {test_acc:.4f}')
```
Using this approach, I see the following performance for various `num_workers` (times are per-epoch; (4)=(1)-(3), (5)=(2)-(3); I'm calling "Loader Init Time" the time that tqdm sits at 0%):

num_workers | (1) Train Tm [s] | (2) Test Tm [s] | (3) Loader Init Time | (4) Train Exec Tm [s] | (5) Test Exec Tm [s]
-- | -- | -- | -- | -- | --
1 | 27 | 89 | 8 | 19 | 81
2 | 24 | 70 | 13 | 11 | 57
3 | 27 | 74 | 19 | 8 | 55
4 | 32 | 82 | 25 | 7 | 57
12 | 77 | 172 | 70 | 7 | 102


I think it's related to [this](https://github.com/pytorch/pytorch/issues/12831), but it may not be exactly the same. I think this problem is somewhat for common PyTorch Windows users; for better performance, I've set `num_workers=1` often for open-source projects that were developed under Linux, even when things couldn't be addressed by putting everything under `if __name__ == "__main__"` .
