### ISSUE TITLE
Batch dimension does not match node dimension in DataParallel

### ISSUE THREAD

**Issue by vymao** [rusty1s/pytorch_geometric#1810]
## 🐛 Bug

I am trying to incorporate Pytorch Geometric's DataParallel module in order to parallelize training on multiple GPUs (here I use 2). I tried running the following: 
```
train_loader = DataListLoader(train_dataset, batch_size=args.batch_size, 
                      shuffle=True, num_workers=args.num_workers)
model = WLGNN_model(args, train_dataset, dataset, hidden_channels=args.hidden_channels, num_layers=args.num_layers, 
                  max_z=max_z, k=args.sortpool_k, use_feature=args.use_feature, 
                  node_embedding=emb).to(device)
model = DataParallel(model)
def train():
    model.train()

    total_loss = 0
    pbar = tqdm(train_loader)
    for data in pbar:
        optimizer.zero_grad()
        #print(data)
        #print(args)
        out = model(data)
        y = torch.cat([d.y.to(torch.float) for d in data]).to(out.device)
```
where in the model (Net.py), there is this forward function: 
```
def forward(self, data):
        x = data.x if self.args.use_feature else None
        z1, z2, w, edge_index, batch, x, edge_weight, node_id = data.z1, data.z2, data.w, data.edge_index, data.batch, x, data.edge_weight, None
        print(data)
        z1_emb = self.z1_embedding(z1)
        z2_emb = self.z2_embedding(z2)
        w_emb = self.w_embedding(w)

        z_emb = torch.cat([w_emb, z1_emb], 1)
        z_emb = torch.cat([z_emb, z2_emb], 1)

        if self.use_feature and x is not None:
            x = torch.cat([z_emb, x.to(torch.float)], 1)
        else:
            x = z_emb
        if self.node_embedding is not None and node_id is not None:
            n_emb = self.node_embedding(node_id)
            x = torch.cat([x, n_emb], 1)
        xs = [x]
        for conv in self.convs:
            xs += [torch.tanh(conv(xs[-1], edge_index, edge_weight))]
        x = torch.cat(xs[1:], dim=-1)

        # Global pooling.
        x = global_sort_pool(x, batch, self.k)
```
However, I am getting an error that looks like this: 

```
Batch(batch=[659], edge_index=[2, 57270], edge_weight=[57270], node_id=[3057], w=[3057], x=[3057, 256], y=[17], z1=[3057], z2=[3057])
Batch(batch=[775], edge_index=[2, 514997], edge_weight=[514997], node_id=[9442], w=[9442], x=[9442, 256], y=[15], z1=[9442], z2=[9442])
Traceback (most recent call last):
  File "/path/to/run.py", line 290, in <module>
    loss = train()
  File "/path/to/run.py", line 63, in train
    out = model(data)
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 60, in forward
    outputs = self.parallel_apply(replicas, inputs, None)
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/path/to/Net.py", line 115, in forward
    x = global_sort_pool(x, batch, self.k)
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch_geometric/nn/glob/sort.py", line 22, in global_sort_pool
    batch_x, _ = to_dense_batch(x, batch, fill_value)
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch_geometric/utils/to_dense_batch.py", line 37, in to_dense_batch
    dim_size=batch_size)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch_scatter/scatter.py", line 31, in scatter_add
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    return scatter_sum(src, index, dim, out, dim_size)
           ~~~~~~~~~~~ <--- HERE
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch_scatter/scatter.py", line 12, in scatter_sum
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    index = broadcast(index, src, dim)
            ~~~~~~~~~ <--- HERE
    if out is None:
        size = src.size()
  File "/n/home01/vym1/.local/lib/python3.7/site-packages/torch_scatter/utils.py", line 13, in broadcast
    for _ in range(src.dim(), other.dim()):
        src = src.unsqueeze(-1)
    src = src.expand_as(other)
          ~~~~~~~~~~~~~ <--- HERE
    return src
RuntimeError: The expanded size of the tensor (3057) must match the existing size (659) at non-singleton dimension 0.  Target sizes: [3057].  Tensor sizes: [659]
```

I think it is the batch size not matching the number of total nodes (to my understanding, the batch attribute should describe the corresponding graph for each node), as you can see from the initial printed output. This seems like a backend issue, unless I am mistaken?

**Comment by vymao** [comment]
Figured it out
