### ISSUE TITLE
the most difficult package I have ever installed for python

### ISSUE THREAD

**Issue by lihuiknight** [rusty1s/pytorch_geometric#1841]
## ❓ Questions & Help

It's clear that this package is useful but it's really difficult for many researchers and developers to install this package even in standard linux system. 

I strongly suggest you can make this package more useful. Thanks.

**Comment by rusty1s** [comment]
Well, I'm happy to help you to install this package, but I cannot do that without any further information from your side. Please let me know about any issues you encountered!

In general, the installation got a lot smoother over the past with the provided binaries, and it is IMO pretty straightforward to install on a standard linux system. In fact, most installation issues stem from the user-side, *e.g.*, incompatible CUDA and PyTorch cudatoolkit versions.

**Comment by lihuiknight** [comment]
Thanks for your reply. I have seen many developers to discuss the installation issues.  If you can make it more friendly, it will really helpful.


I have follow the instruction from [https://github.com/rusty1s/pytorch_scatter/issues/7](url), [https://github.com/rusty1s/pytorch_geometric#pytorch-170](url) and many other tutorials. However, it doesn't work. 

I list the key environments:
System: Ubuntu 20.04
Python Version: python 3.6
pytorch Version: torch 3.7+cpu


I install the pytorch_geometric as follows:

`
sudo pip3.6 install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
sudo pip3.6 install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
sudo pip3.6 install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
sudo pip3.6 install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
sudo pip3.6 install torch-geometric

`

**Comment by rusty1s** [comment]
As other issues have pointed out, an error such as `undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs` is caused by a duplicated versions (maybe you have an older version of `torch-scatter` installed that is compiled for PyTorch 1.6.0?). There's really not much I can do about it except for finding its cause on your side. Please try out the following things:

1. Repeatedly call `pip uninstall torch-geometric torch-sparse torch-scatter torch-spline-conv torch-cluster` to ensure that all packages are uninstalled. Repeat this until `pip` no longer finds any package to uninstall.
2. Ensure that PyTorch 1.7.0 is called (in case you have duplicated PyTorch versions): `python -c "import torch; print(torch.__version__)"`
3. Install `torch-scatter` again and import it in a Python REPL to see if it works.

**Comment by lihuiknight** [comment]
thanks for the quick reply. However, the above solutions doesn't work for me. I list the detailed command and log as follows.

1. as you said, make sure all the packages are uninstalled:
```

ken@ubuntu:~$ sudo pip3.6 uninstall torch-geometric
WARNING: Skipping torch-geometric as it is not installed.
ken@ubuntu:~$ sudo pip3.6 uninstall torch-sparse
WARNING: Skipping torch-sparse as it is not installed.
ken@ubuntu:~$ sudo pip3.6 uninstall torch-scatter
WARNING: Skipping torch-scatter as it is not installed.
ken@ubuntu:~$ sudo pip3.6 uninstall torch-spline-conv
WARNING: Skipping torch-spline-conv as it is not installed.
ken@ubuntu:~$ sudo pip3.6 uninstall torch-cluster
WARNING: Skipping torch-cluster as it is not installed.


ken@ubuntu:~$ sudo pip uninstall torch-geometric
WARNING: Skipping torch-geometric as it is not installed.
ken@ubuntu:~$ sudo pip uninstall torch-sparse
WARNING: Skipping torch-sparse as it is not installed.
ken@ubuntu:~$ sudo pip uninstall torch-scatter
WARNING: Skipping torch-scatter as it is not installed.
ken@ubuntu:~$ sudo pip uninstall torch-spline-conv
WARNING: Skipping torch-spline-conv as it is not installed.
ken@ubuntu:~$ sudo pip uninstall torch-cluster
WARNING: Skipping torch-cluster as it is not installed.

ken@ubuntu:~$ sudo pip3 uninstall torch-geometric
WARNING: Skipping torch-geometric as it is not installed.
ken@ubuntu:~$ sudo pip3 uninstall torch-sparse
WARNING: Skipping torch-sparse as it is not installed.
ken@ubuntu:~$ sudo pip3 uninstall torch-scatter
WARNING: Skipping torch-scatter as it is not installed.
ken@ubuntu:~$ sudo pip3 uninstall torch-spline-conv
WARNING: Skipping torch-spline-conv as it is not installed.
ken@ubuntu:~$ sudo pip3 uninstall torch-cluster
WARNING: Skipping torch-cluster as it is not installed.
````

2. then I install all the packages again, all of them are installed successfully.

```

ken@ubuntu:~$ sudo pip3.6 install torch-geometric
Processing /root/.cache/pip/wheels/74/95/12/5470c026904562cb9f8be72a62f90541c0d8a89526e863eaff/torch_geometric-1.6.1-py3-none-any.whl
Requirement already satisfied: ase in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (3.20.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (4.52.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (0.23.2)
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (1.7.0+cpu)
Requirement already satisfied: googledrivedownloader in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (0.4)
Requirement already satisfied: numba in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (0.51.2)
Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (2.10.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (1.5.3)
Requirement already satisfied: rdflib in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (5.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (2.11.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from torch-geometric) (2.22.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (0.23.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (2.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torch-geometric) (1.16.4)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from ase->torch-geometric) (3.3.3)
Requirement already satisfied: pytz>=2011k in /usr/lib/python3/dist-packages (from pandas->torch-geometric) (2019.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/lib/python3/dist-packages (from pandas->torch-geometric) (2.7.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.6/dist-packages (from torch->torch-geometric) (3.7.4.3)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from torch->torch-geometric) (0.7)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from torch->torch-geometric) (0.18.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba->torch-geometric) (45.2.0)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.6/dist-packages (from numba->torch-geometric) (0.34.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from h5py->torch-geometric) (1.14.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.6/dist-packages (from rdflib->torch-geometric) (2.4.7)
Requirement already satisfied: isodate in /usr/local/lib/python3.6/dist-packages (from rdflib->torch-geometric) (0.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2->torch-geometric) (1.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->torch-geometric) (0.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->torch-geometric) (2.1.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx->torch-geometric) (4.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=2.0.0->ase->torch-geometric) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=2.0.0->ase->torch-geometric) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=2.0.0->ase->torch-geometric) (8.0.1)
Installing collected packages: torch-geometric
Successfully installed torch-geometric-1.6.1
ken@ubuntu:~$ sudo pip3.6 install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0.html
Collecting torch-scatter==latest+cpu
  Using cached https://pytorch-geometric.com/whl/torch-1.7.0/torch_scatter-latest%2Bcpu-cp36-cp36m-linux_x86_64.whl (9.6 MB)
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.5
ken@ubuntu:~$ sudo pip3.6 install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0.html
Collecting torch-sparse==latest+cpu
  Using cached https://pytorch-geometric.com/whl/torch-1.7.0/torch_sparse-latest%2Bcpu-cp36-cp36m-linux_x86_64.whl (23.5 MB)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from torch-sparse==latest+cpu) (1.5.3)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.6/dist-packages (from scipy->torch-sparse==latest+cpu) (1.16.4)
Installing collected packages: torch-sparse
Successfully installed torch-sparse-0.6.8
ken@ubuntu:~$ sudo pip3.6 install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0.html
Collecting torch-cluster==latest+cpu
  Using cached https://pytorch-geometric.com/whl/torch-1.7.0/torch_cluster-latest%2Bcpu-cp36-cp36m-linux_x86_64.whl (20.0 MB)
Installing collected packages: torch-cluster
Successfully installed torch-cluster-1.5.8
ken@ubuntu:~$ sudo pip3.6 install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0.html
Collecting torch-spline-conv==latest+cpu
  Using cached https://pytorch-geometric.com/whl/torch-1.7.0/torch_spline_conv-latest%2Bcpu-cp36-cp36m-linux_x86_64.whl (6.2 MB)
Installing collected packages: torch-spline-conv
Successfully installed torch-spline-conv-1.2.0

````

3.  for the pytorch version, it's exact 1.7.0
```
ken@ubuntu:~$ python3.6 -c "import torch; print(torch.__version__)"
1.7.0+cpu
```

4. then I execute the following code:
```
import torch
print(torch.__version__)
from torch_geometric.nn import MetaLayer, MessagePassing
```

there are similar errors:
```
/usr/bin/python3.6 /home/ken/project/symbolic_deep_learning/test.py
1.7.0+cpu
Traceback (most recent call last):
  File "/home/ken/project/symbolic_deep_learning/test.py", line 71, in <module>
    from torch_geometric.nn import MetaLayer, MessagePassing
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/home/ken/.local/lib/python3.6/site-packages/torch_scatter/__init__.py", line 12, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ken/.local/lib/python3.6/site-packages/torch_scatter/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Process finished with exit code 1

```

**Comment by rusty1s** [comment]
Thanks for reporting. It would be great if you could try to install it in a fresh miniconda environment and see if that works for you. Is that possible for you?

**Comment by lihuiknight** [comment]
how to make a fresh miniconda environment? could you give some suggestions. If so, i will have a try.

**Comment by lihuiknight** [comment]
Hi,

Step 1: I install a miniconda environment by the following Dockerfile:
```
FROM ubuntu:20.04

#  $ docker build . -t continuumio/miniconda3:latest -t continuumio/miniconda3:4.5.11
#  $ docker run --rm -it continuumio/miniconda3:latest /bin/bash
#  $ docker push continuumio/miniconda3:latest
#  $ docker push continuumio/miniconda3:4.5.11

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH
COPY sources.list /etc/apt/sources.list

RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY Miniconda3-4.5.11-Linux-x86_64.sh /root/miniconda.sh
RUN /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda install -y python==3.6.12
ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini

ENTRYPOINT [ "/usr/bin/tini", "--" ]
CMD [ "/bin/bash" ]

```

Step 2:  run docker container with above image, and then execute the following commands:
```

pip install torch-geometric
pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html


```

Step 3:  Run `python` in terminal and `from torch_geometric.nn import MetaLayer, MessagePassing`, the same error occurs:
```
root@3cbe4b598243:/files# python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch_geometric.nn import MetaLayer, MessagePassing
/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 4, in <module>
    from .conv import *  # noqa
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/nn/conv/__init__.py", line 6, in <module>
    from .gravnet_conv import GravNetConv
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/nn/conv/gravnet_conv.py", line 11, in <module>
    from torch_cluster import knn
  File "/opt/conda/lib/python3.6/site-packages/torch_cluster/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/opt/conda/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.6/site-packages/torch_cluster/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev

```

**Comment by rusty1s** [comment]
A docker container is not necessary, but shouldn't hurt :)

I guess you need to install PyTorch before installing the packages (the default one installed by `torch-geometric` does **not** install the correct CPU version). Please try to simply install `torch+cpu` and `torch-scatter+cpu` and see if that works.

**Comment by lihuiknight** [comment]
It doesn't work.

**Step 1:** I uninstall all the related packages again and again as follows, i can make sure all the packages are uninstalled.

```
pip3.6 uninstall torch 
pip3.6 uninstall torch-geometric
pip3.6 uninstall torch-sparse
pip3.6 uninstall torch-scatter
pip3.6 uninstall torch-spline-conv
pip3.6 uninstall torch-cluster
```

**Step 2:**  Then I only install `torch+cpu` and `torch-scatter+cpu`:

See log:
```
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 uninstall torch-geometric
WARNING: Skipping torch-geometric as it is not installed.
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 uninstall torch-sparse
WARNING: Skipping torch-sparse as it is not installed.
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 uninstall torch-scatter
WARNING: Skipping torch-scatter as it is not installed.
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 uninstall torch-spline-conv
WARNING: Skipping torch-spline-conv as it is not installed.
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 uninstall torch-cluster
WARNING: Skipping torch-cluster as it is not installed.
ken@ubuntu:~/Documents/docker/files$ 
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.0+cpu
  Using cached https://download.pytorch.org/whl/cpu/torch-1.7.0%2Bcpu-cp36-cp36m-linux_x86_64.whl (159.3 MB)
Requirement already satisfied: torchvision==0.8.1+cpu in /usr/local/lib/python3.6/dist-packages (0.8.1+cpu)
Requirement already satisfied: torchaudio==0.7.0 in /usr/local/lib/python3.6/dist-packages (0.7.0)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from torch==1.7.0+cpu) (0.18.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.6/dist-packages (from torch==1.7.0+cpu) (3.7.4.3)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from torch==1.7.0+cpu) (0.7)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torch==1.7.0+cpu) (1.16.4)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision==0.8.1+cpu) (8.0.1)
Installing collected packages: torch
Successfully installed torch-1.7.0+cpu
ken@ubuntu:~/Documents/docker/files$ sudo pip3.6 install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0.html
Collecting torch-cluster==latest+cpu
  Using cached https://pytorch-geometric.com/whl/torch-1.7.0/torch_cluster-latest%2Bcpu-cp36-cp36m-linux_x86_64.whl (20.0 MB)
Installing collected packages: torch-cluster
Successfully installed torch-cluster-1.5.8

```


**Step 3:** test whether torch-cluster is well in my system using the example from [https://github.com/rusty1s/pytorch_cluster#voxelgrid](url)
```

import torch
from torch_cluster import grid_cluster

pos = torch.tensor([[0., 0.], [11., 9.], [2., 8.], [2., 2.], [8., 3.]])
size = torch.Tensor([5, 5])

cluster = grid_cluster(pos, size)

```

the similar error occurs：
`OSError: /home/ken/.local/lib/python3.6/site-packages/torch_cluster/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`

**Comment by rusty1s** [comment]
I feel your frustration, but it seems like you are once again installing using the system python (which I suggested to avoid to track down the error). In particular, it looks like you did not install PyTorch in your miniconda example. You can do the following:
1. Download miniconda from [here](https://docs.conda.io/en/latest/miniconda.html)
2. Execute the script
3. Add `.../miniconda3/bin` to your `$PATH` (replace `.../miniconda3` with the correct path)
4. Ensure that you are using the miniconda python by running `which python`
5. Run `conda install pytorch torchvision torchaudio cpuonly -c pytorch`
6. Run `pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html`
7. Test via `python -c "import torch_scatter; print(torch_scatter.__version__)"

**Comment by lihuiknight** [comment]
There is a different errors shown as follows:

```
(base) ken@ubuntu:~/miniconda3/bin$ python -c "import torch_scatter; print(torch_scatter.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'torch_scatter' has no attribute 'version'

```

**Comment by rusty1s** [comment]
Awesome :) You can now install the other packages which should work just as fine.

**Comment by lihuiknight** [comment]
Thanks. I think if these packages could be installed via standard pip, it'll be much helpful. you can close this issue now.

thanks.

**Comment by unikcc** [comment]
Yes it's so so so hard to config it. I had to pinch my nose to install because I have to run the code of a paper. I swear I won't take the initiative to use it!

**Comment by rusty1s** [comment]
That‘s fine, this package is free to use for anyone. Nonetheless, you should at least consider giving (constructive) feedback on how to improve. Remember that we are all just little developers working on it for free.

**Comment by unikcc** [comment]
> That‘s fine, this package is free to use for anyone. Nonetheless, you should at least consider giving (constructive) feedback on how to improve. Remember that we are all just little developers working on it for free.

Yeah, thanks for your hard work and volunteer contribution for open-source community and it really benefited many people.
Anyway, I succeeded installed it yesterday even though experienced countless failure. Now I have to try to reinstall it because the author of that paper didn't declare the right version.
I apologize for my extreme speech.

**Comment by unikcc** [comment]
> That‘s fine, this package is free to use for anyone. Nonetheless, you should at least consider giving (constructive) feedback on how to improve. Remember that we are all just little developers working on it for free.

Yeah, thanks for your hard work and volunteer contribution for open-source community and it really benefited many people.
Anyway, I succeeded installed it yesterday even though experienced countless failures. Now I have to try to reinstall it because the author of that paper didn't declare the right version.
I apologize for my extreme speech.

**Comment by RokiaAbdeen** [comment]
Hello, I hope anyone can help me to solve this issue
I have torch version 1.4.0  cuda 10.0
I run this command to install torch-sparse , torch-geometric and torch-scatter
pip install torch-geometric torch-sparse torch-scatter torch-cluster -f https://pytorch-geometric.com/whl/torch-1.4.9+cu100.html
I got this error
Failed building wheel for torch-sparse
Failed building wheel for torch-scatter
Failed building wheel for torch-cluster
what would be the wrong here please
thanks in advance..
