### ISSUE TITLE
DenseSAGEConv forward function argument error for the proteins_diff_pool.py example

### ISSUE THREAD

**Issue by YingtongDou** [rusty1s/pytorch_geometric#1878]
## 🐛 Bug

Traceback (most recent call last):
  File "/hdisk2/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4d28c3f11429>", line 1, in <module>
    runfile('/hdisk2/FN-GNN/Detector/Homo/proteins_diff_pool.py', wdir='/hdisk2/FN-GNN/')
  File "/home/filetrans/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/filetrans/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/hdisk2/FN-GNN/Detector/Homo/proteins_diff_pool.py", line 147, in <module>
    train_loss = train(epoch)
  File "/hdisk2/FN-GNN/Detector/Homo/proteins_diff_pool.py", line 125, in train
    output, _, _ = model(data.x, data.adj, data.mask)
  File "/hdisk2/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hdisk2/FN-GNN/Detector/Homo/proteins_diff_pool.py", line 95, in forward
    s = self.gnn1_pool(x, adj, mask)
  File "/hdisk2/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hdisk2/FN-GNN/Detector/Homo/proteins_diff_pool.py", line 65, in forward
    x1 = self.bn(1, F.relu(self.conv1(x0, adj, mask, self.add_loop)))
  File "/hdisk2/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
**TypeError: forward() takes from 3 to 4 positional arguments but 5 were given**

## To Reproduce

1. Download the [proteins_diff_pool.py](https://github.com/rusty1s/pytorch_geometric/blob/1.6.1/examples/proteins_diff_pool.py) from pytorch_geometric/examples/
2. Run the default code

## Expected behavior

The forward pass **self.conv1(x0, adj, mask, self.add_loop)** has four arguments and the code should work without the above error message.

## Environment

* OS: Ubuntu 18.04.5
* Python version: 3.7
* PyTorch version: 1.6
* CUDA/cuDNN version: 10.2
* GCC version: 7.5.0
* PyG version: 1.6.1
* torch-cluster version: 1.5.8
* torch-geometric: 1.6.1
* torch-scatter: 2.0.5
* torch-sparse: 0.6.8
* torch-spline-conv: 1.2.0

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in the example.
