### ISSUE TITLE
Error when loading the COLOR-3 dataset from TUDataset

### ISSUE THREAD

**Issue by LindaSt** [rusty1s/pytorch_geometric#1915]
## 🐛 Bug
Hi! 

When I am trying to load `dataset = TUDataset(root='../tmp/COLOR-3', name='COLOR-3')` I get the following error:

```
Downloading https://www.chrsmrrs.com/graphkerneldatasets/COLOR-3.zip
Extracting ../tmp/COLOR-3/COLOR-3/COLOR-3.zip
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/HOME/studerl/.conda/envs/gale/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 65, in __init__
    pre_filter)
  File "/HOME/studerl/.conda/envs/gale/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/HOME/studerl/.conda/envs/gale/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 89, in __init__
    self._download()
  File "/HOME/studerl/.conda/envs/gale/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 141, in _download
    self.download()
  File "/HOME/studerl/.conda/envs/gale/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 131, in download
    os.rename(osp.join(folder, self.name), self.raw_dir)
FileNotFoundError: [Errno 2] No such file or directory: '../tmp/COLOR-3/COLOR-3/COLOR-3' -> '../tmp/COLOR-3/COLOR-3/raw'
```

I'm on a linux GPU cluster using python 3.7 and torch-geometric version 1.6.1.

Thanks.

**Comment by LindaSt** [comment]
I also had a look at the manual download from the TU website, and there it seems that no graph_labels.txt file comes with it. I'm guessing the graph_attributes.txt file contains the labels, maybe that's causing an additional issue?

**Comment by rusty1s** [comment]
The name of the dataset is `COLORS-3` (with an upper S).

**Comment by LindaSt** [comment]
My bad, I'm apparently not capable to read haha. I've found something else, that's not really a bug but causes some inconsistencies on my end. For all the other datasets, the `data.num_classes` returns an `int`, but for this dataset I get a `float` (11.0). This causes issues when it's directly passer forward to set the number of neurons for the classification layer.

**Comment by LindaSt** [comment]
All the classes encodings are also in `float` format, which then gives me issues with the loss calculation. This was never an issue with any of the other TUDataset data object.

**Comment by rusty1s** [comment]
Thanks for letting me know. This is not easily fixable though, because this error is already present in the raw data. Therefore, the workaround to simply convert your `data.y` to int is needed.
