### ISSUE TITLE
 Segmentation fault and other issues with NeighborSampler when using node_idx

### ISSUE THREAD

**Issue by evancofer** [rusty1s/pytorch_geometric#1917]
## 🐛 Bug

For some reason, when I used `node_idx` with the `NeighborSampler`, I have been getting a segmentation fault or occasionally an index out of bound error. It may also be worth noting that when I remove the `node_idx` parameter from the `NeighborSampler`, I find that it only iterates over 1750 of the 1767 nodes in the graph. I am not sure what could be causing this either.

## To Reproduce

The following script is producing the issue:
```py
import numpy
import torch
import torch_geometric

#s = 123
s = 111
numpy.random.seed(s)
torch.random.manual_seed(s)
data = torch_geometric.datasets.PPI(root='data/PPI')[0]

# Look at 80% of the data w/ a 70/30 train/test split of nodes.
shuf = numpy.random.choice(numpy.arange(data.x.shape[0]), data.x.shape[0], replace=False)
n_train = int(0.8 * 0.7 * shuf.shape[0])
n_test = int(0.8 * 0.3 * shuf.shape[0])
train_mask = torch.tensor([i in set(shuf[:n_train].tolist()) for i in numpy.arange(data.x.shape[0])], dtype=torch.bool)
test_mask = torch.tensor([i in set(shuf[n_train:(n_train+n_test)].tolist()) for i in numpy.arange(data.x.shape[0])], dtype=torch.bool)
holdout_mask = torch.tensor([i in set(shuf[(n_train+n_test):].tolist()) for i in numpy.arange(data.x.shape[0])], dtype=torch.bool)
print("Training on", sum(train_mask), "of",  shuf.shape[0])
print("Testing on", sum(test_mask), "of", shuf.shape[0])
print("Reserving", sum(holdout_mask), "of", shuf.shape[0])


# Assign labels based on edges per node.
cnts = data.edge_index[0].unique(return_counts=True)
node_counts = torch.zeros(data.x.shape[0], dtype=torch.long)
node_counts = node_counts.scatter_(0, cnts[0], cnts[1])
node_counts = node_counts.unsqueeze(-1)

# Create labels based on edge count, and otherwise random covariates.
x_random = torch.rand((node_counts.shape[0], 5))
y_simple = (node_counts > 15).float()
x_simple = torch.cat((x_random.float(), node_counts.float()), dim=1)

# Create dataset.
simple_data = torch_geometric.data.Data(edge_index=data.edge_index.clone(),
                                        x=x_simple,
                                        y=y_simple,
                                        train_mask=train_mask,
                                        test_mask=test_mask)
print(simple_data)


# (batch_size, ids of all nodes, [(edge_index or bipartite edges between source and targets, e_id or ids of original edges, size or shape of bipartite graph)])
train_loader = torch_geometric.data.NeighborSampler(simple_data.edge_index,
                                                    node_idx=torch.arange(simple_data.train_mask.shape[0])[simple_data.train_mask].long(),
                                                    sizes=[1],
                                                    batch_size=1,
                                                    shuffle=False,
                                                    num_workers=0)


# Iterate over data.
for epoch in range(1):
    seen = 0
    for batch_size, n_id, adjs in train_loader:
        seen += batch_size
    print(seen, flush=True)

```

When I try debugging a bit with gdb, I get the following output:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
sample_adj_cpu (rowptr=..., col=..., rowcount=..., idx=..., num_neighbors=5, replace=false) at /home/travis/build/rusty1s/pytorch_sparse/csrc/cpu/sample_cpu.cpp:105
```

Finally, when I do occasionally see indexing errors instead of segfaults, this is the output. Note that the problematic index isn't always 33241, and seems to be somewhat random.

```
Training on tensor(989) of 1767
Testing on tensor(424) of 1767
Reserving tensor(354) of 1767
Data(edge_index=[2, 32318], test_mask=[1767], train_mask=[1767], x=[1767, 6], y=[1767, 1])
Traceback (most recent call last):
  File "test_script.py", line 55, in <module>
    for batch_size, n_id, adjs in train_loader:
  File "/home/ecofer/anaconda3/envs/gnn-stable/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ecofer/anaconda3/envs/gnn-stable/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ecofer/anaconda3/envs/gnn-stable/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ecofer/anaconda3/envs/gnn-stable/lib/python3.8/site-packages/torch_geometric/data/sampler.py", line 151, in sample
    adj_t, n_id = self.adj_t.sample_adj(n_id, size, replace=False)
  File "/home/ecofer/anaconda3/envs/gnn-stable/lib/python3.8/site-packages/torch_sparse/sample.py", line 35, in sample_adj
    value = value[e_id]
IndexError: index 33241 is out of bounds for dimension 0 with size 32318
```

## Expected behavior

Ideally, nothing should happen. In the code provided there isn't any additional logic being added by me. I should be able to iterate over the `NeighborSampler` without a segfault or indexing error.

## Environment
I am running this on CPU w/ CentOS 8. 

Conda environment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ase                       3.20.1                   pypi_0    pypi
astroid                   2.4.2                    py38_0  
blas                      1.0                         mkl  
ca-certificates           2020.12.8            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
chardet                   3.0.4                    pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cycler                    0.10.0                   pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
googledrivedownloader     0.4                      pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
intel-openmp              2020.2                      254  
isodate                   0.6.0                    pypi_0    pypi
isort                     5.6.4                      py_0  
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.17.0                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.4.3            py38h27cfd23_2  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuv                     1.40.0               h7b6447c_0  
llvmlite                  0.35.0                   pypi_0    pypi
lz4-c                     1.9.2                heb0550a_3  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
mccabe                    0.6.1                    py38_1  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                      pypi_0    pypi
ninja                     1.10.2           py38hff7bd54_0  
numba                     0.52.0                   pypi_0    pypi
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
olefile                   0.46                       py_0  
openssl                   1.1.1i               h27cfd23_0  
pandas                    1.1.5                    pypi_0    pypi
pillow                    8.0.1            py38he98fc37_0  
pip                       20.3.1           py38h06a4308_0  
pylint                    2.6.0                    py38_0  
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                    pypi_0    pypi
python-louvain            0.14                     pypi_0    pypi
pytorch                   1.7.0               py3.8_cpu_0  [cpuonly]  pytorch
pytz                      2020.4                   pypi_0    pypi
rdflib                    5.0.0                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.25.0                   pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                51.0.0           py38h06a4308_2  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
torch-cluster             1.5.8                    pypi_0    pypi
torch-geometric           1.6.3                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.8                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchaudio                0.7.0                      py38    pytorch
torchvision               0.8.1                  py38_cpu  [cpuonly]  pytorch
tqdm                      4.54.1                   pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
urllib3                   1.26.2                   pypi_0    pypi
wheel                     0.36.1             pyhd3eb1b0_0  
wrapt                     1.11.2           py38h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

## Additional context

For context, I have just been using the simple dataset to try out node classification architectures. The labels are just determined based on the number of edges connected to a node. After removing pretty much all training code from the script, I found that the error persisted.

**Comment by rusty1s** [comment]
I see. The `PPI` dataset has some isolated nodes, and therefore the `num_nodes` of the graph is not correctly identified via `edge_index`. Fixable by passing the correct number of nodes to the `loader`:
```python
train_loader = torch_geometric.data.NeighborSampler(
    simple_data.edge_index, node_idx=..., sizes=[1], batch_size=1,
    num_nodes=data.num_nodes, shuffle=False, num_workers=0)
```

**Comment by evancofer** [comment]
This seems to fix the problem! Thank you so much for your help! Should documentation for `NeighborSampler` be updated to reflect this issue or would it be redundant? [There's documentation](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Data.num_nodes) for this behavior for `Data`, but not for other classes.

**Comment by rusty1s** [comment]
That's a good idea. I will implement it ASAP.

**Comment by rusty1s** [comment]
`num_nodes` is now determined by the maximum index in `edge_index` and `node_idx`, which should eliminate this issue.
