### ISSUE TITLE
The error about diffpool

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1932]
## 🐛 Bug

Hello:
when i run the code in path: rusty1s/pytorch_geometric/benchmark/kernel/main,
DD、PROTEINS、NCI1、FRAKENSTEIN datasets cannot work with diffpool,
it will rise the " ValueError: Found input variables with inconsistent numbers of samples: [xxxx, ####] "
Do you know why is it? Thank you.

**Comment by jiaruHithub** [comment]
If I use dataset NCI109,The new error has been reported:
```NCI109 - DiffPool
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    logger=None,
  File "/home/pyg/pyg/benchmark/kernel1/train_eval.py", line 43, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "/home/pyg/pyg/benchmark/kernel1/train_eval.py", line 114, in train
    out = model(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyg/pyg/benchmark/kernel1/diff_pool.py", line 65, in forward
    s = self.pool_block1(x, adj, mask, add_loop=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyg/pyg/benchmark/kernel1/diff_pool.py", line 27, in forward
    x1 = F.relu(self.conv1(x, adj, mask, add_loop))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given
```
How can I fix this error?

**Comment by rusty1s** [comment]
See https://github.com/rusty1s/pytorch_geometric/issues/1154#issuecomment-748405622.
