### ISSUE TITLE
GCNConv error?

### ISSUE THREAD

**Issue by vymao** [rusty1s/pytorch_geometric#1934]
Not sure how else to explain this error but to post it here. I am using GCNConv but am running into this error randomly at higher epoch count: 

```
Run: 01, Epoch: 316, Loss: 61.6280, Valid MSE: 215.70%, Test MSE: 305.34%
100%|██████████| 2301/2301 [01:32<00:00, 24.98it/s]
100%|██████████| 203/203 [00:07<00:00, 25.86it/s]
100%|██████████| 204/204 [00:08<00:00, 25.34it/s]
MSE
Run: 01, Epoch: 317, Loss: 63.0244, Valid MSE: 215.28%, Test MSE: 310.71%
100%|██████████| 2301/2301 [01:31<00:00, 25.15it/s]
100%|██████████| 203/203 [00:07<00:00, 25.45it/s]
100%|██████████| 204/204 [00:07<00:00, 25.72it/s]
MSE
Run: 01, Epoch: 318, Loss: 63.0782, Valid MSE: 220.16%, Test MSE: 312.79%
100%|██████████| 2301/2301 [01:33<00:00, 24.58it/s]
100%|██████████| 203/203 [00:07<00:00, 26.03it/s]
100%|██████████| 204/204 [00:08<00:00, 24.93it/s]
MSE
Run: 01, Epoch: 319, Loss: 62.9604, Valid MSE: 211.49%, Test MSE: 312.12%
100%|██████████| 2301/2301 [01:35<00:00, 24.19it/s]
100%|██████████| 203/203 [00:07<00:00, 27.58it/s]
100%|██████████| 204/204 [00:07<00:00, 26.32it/s]
MSE
Run: 01, Epoch: 320, Loss: 61.7545, Valid MSE: 212.12%, Test MSE: 298.78%
100%|██████████| 2301/2301 [01:31<00:00, 25.05it/s]
100%|██████████| 203/203 [00:07<00:00, 27.63it/s]
100%|██████████| 204/204 [00:07<00:00, 26.85it/s]
MSE
Run: 01, Epoch: 321, Loss: 62.5692, Valid MSE: 214.07%, Test MSE: 301.77%
100%|█████████▉| 2300/2301 [01:33<00:00, 24.54it/s]
Traceback (most recent call last):
  File "/path/to/run4.py", line 476, in <module>
    loss = train_model()
  File "/path/to/run4.py", line 69, in train_model
    else: out = model(data).view(-1)
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/path/to/GNN.py", line 107, in forward
    xs += [torch.tanh(GCNConv(xs[-1], edge_index))]
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 161, in forward
    self.improved, self.add_self_loops, dtype=x.dtype)
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 52, in gcn_norm
    edge_weight = torch.ones((edge_index.size(1), ), dtype=dtype,
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

This seems random and I'm not sure how to fix it? The model worked fine for the first 300 or so epochs.

**Comment by rusty1s** [comment]
Can you show me the shape of `edge_index` for which this error occurs?
