### ISSUE TITLE
torch-geometric packages don't work with python 3.9

### ISSUE THREAD

**Issue by rynecjohnston** [rusty1s/pytorch_geometric#1970]
I'm trying to install torch-geometric's packages but I'm running into an issue where they don't play nice with python 3.9. Any ideas on how to proceed. I can't downgrade to 3.8 because a separate package (rdkit) I intend to use with pytorch/torch-geometric won't install with python 3.8. Am I just SOL?

```
06:20:38 AM  ~$ pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html
Collecting torch-scatter
  Using cached torch_scatter-2.0.5.tar.gz (20 kB)
    ERROR: Command errored out with exit status -6:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-install-xxw448v8/torch-scatter_425bbb012a5740fea128a31488bd7d54/setup.py'"'"'; __file__='"'"'/private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-install-xxw448v8/torch-scatter_425bbb012a5740fea128a31488bd7d54/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-pip-egg-info-22lv5gxs
         cwd: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-install-xxw448v8/torch-scatter_425bbb012a5740fea128a31488bd7d54/
    Complete output (2 lines):
    OMP: Error #13: Assertion failure at kmp_csupport.cpp(597).
    OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
    ----------------------------------------
ERROR: Command errored out with exit status -6: python setup.py egg_info Check the logs for full command output.
```

**Comment by rusty1s** [comment]
We currently do not provide any wheels for Python 3.9, so manual compilation is required. It's hard to tell from the output what went wrong though. Can you rerun via `pip install --verbose torch-scatter`.

**Comment by rynecjohnston** [comment]
Thanks for the quick reply.

```
07:58:49 AM  ~$ pip install --verbose torch-scatter
Using pip 20.3.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-ephem-wheel-cache-kp5fw7z8
Created temporary directory: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o
Initialized build tracking at /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o
Created build tracker: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o
Entered build tracker: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o
Created temporary directory: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-install-v6ds0b4t
1 location(s) to search for versions of torch-scatter:
* https://pypi.org/simple/torch-scatter/
Fetching project page and analyzing links: https://pypi.org/simple/torch-scatter/
Getting page https://pypi.org/simple/torch-scatter/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/torch-scatter/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/torch-scatter/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/29/96/566ac314e796d4b07209a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.org/simple/torch-scatter/), version: 0.3.0
  Found link https://files.pythonhosted.org/packages/6a/b0/ecffacddf573c147c70c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.org/simple/torch-scatter/), version: 1.0.2
  Found link https://files.pythonhosted.org/packages/08/09/07b106f3e74246f4ecf6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.org/simple/torch-scatter/), version: 1.0.3
  Found link https://files.pythonhosted.org/packages/2d/70/df2bc259d9606f00854ca43b6839f9047ec44900563435e0067584c93864/torch_scatter-1.0.4.tar.gz#sha256=ec004d687e47da9d5477407849d815629fc8b571ee87aeeebf6af8ed6f16defc (from https://pypi.org/simple/torch-scatter/), version: 1.0.4
  Found link https://files.pythonhosted.org/packages/2f/97/c50a6aeaedc6924180c6f5810d2a7405ce11aa9b82ba4284badad549d665/torch_scatter-1.1.0.tar.gz#sha256=e534cc2ecb2f9d9b559b1513cd411737d26ea5585d1d65ff571fec55f42a49de (from https://pypi.org/simple/torch-scatter/), version: 1.1.0
  Found link https://files.pythonhosted.org/packages/91/5f/eb1d3ef3810cb1165859d40db4d9ee6d7f1dfef97d7e5c34010055f43d95/torch_scatter-1.1.1.tar.gz#sha256=9db7f2c0a5cddf6cfde633e33db7c2c94eaab163e9f8edb46460d6414cc97917 (from https://pypi.org/simple/torch-scatter/), version: 1.1.1
  Found link https://files.pythonhosted.org/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a (from https://pypi.org/simple/torch-scatter/), version: 1.1.2
  Found link https://files.pythonhosted.org/packages/07/c0/f7ac424496f4a3bcb31aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz#sha256=3a0259105d07d264c740eec8e4267260a5c144cf55472abd26022fff4fd73281 (from https://pypi.org/simple/torch-scatter/), version: 1.2.0
  Found link https://files.pythonhosted.org/packages/24/b7/680c3b392a4b55a0ebfb480aabb0d5c188e94bb21790104175c8cd614947/torch_scatter-1.3.0.tar.gz#sha256=bf7d561b8ef12b39a99f5797c90b989a0ce2c3ee4de74dff3b170f2d8566e1d4 (from https://pypi.org/simple/torch-scatter/), version: 1.3.0
  Found link https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.org/simple/torch-scatter/), version: 1.3.1
  Found link https://files.pythonhosted.org/packages/30/d9/1d5fd4d183dabd9e0a1f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz#sha256=890e8f9da2d57431912182960b71bf6c56397de42c2464907a6e9c583164bf06 (from https://pypi.org/simple/torch-scatter/), version: 1.3.2
  Found link https://files.pythonhosted.org/packages/b8/c3/8bad887ffa55c86f120ef5ae252dc0e357b3bd956d9fbf45242bacc46290/torch_scatter-1.4.0.tar.gz#sha256=5999ef256154e5a99445118c1a53f95cf0f95ef7b5cd8d3b256101125479cc2e (from https://pypi.org/simple/torch-scatter/), version: 1.4.0
  Found link https://files.pythonhosted.org/packages/28/f7/fa4e61587169924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz#sha256=49d3059b7be93d3f2c328fdc6daa3a8479e3dc4a50c8247aef913177122db671 (from https://pypi.org/simple/torch-scatter/), version: 2.0.2
  Found link https://files.pythonhosted.org/packages/36/2a/ef3d841ec577e2231662ef86af983c6c7c7d509a0e1d9f12949d0218b492/torch_scatter-2.0.3.tar.gz#sha256=1c4b9cb0f6a195c20d8c4b6230d086cae6965b7eb08f80bd2ec050a094b8e563 (from https://pypi.org/simple/torch-scatter/) (requires-python:>=3.6), version: 2.0.3
  Found link https://files.pythonhosted.org/packages/98/a9/47cd92673b6ba251240d587815c763baac2099b07bb76fecdb3b7ae5cece/torch_scatter-2.0.4.tar.gz#sha256=db6c9eca919b86f3eb6102dd0e1215af72e39ed3a4e8d142e6a21d3f20d5c244 (from https://pypi.org/simple/torch-scatter/) (requires-python:>=3.6), version: 2.0.4
  Found link https://files.pythonhosted.org/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz#sha256=148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f (from https://pypi.org/simple/torch-scatter/) (requires-python:>=3.6), version: 2.0.5
Given no hashes to check 16 links for project 'torch-scatter': discarding no candidates
Collecting torch-scatter
  Created temporary directory: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-unpack-dhzaq0it
  Looking up "https://files.pythonhosted.org/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz" in the cache
  Current age based on date: 5953
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 5953
  Using cached torch_scatter-2.0.5.tar.gz (20 kB)
  Added torch-scatter from https://files.pythonhosted.org/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz#sha256=148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f to build tracker '/private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o'
    Running setup.py (path:/private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-install-v6ds0b4t/torch-scatter_279d66df098a47b1a57d2d30f0f60692/setup.py) egg_info for package torch-scatter
    Created temporary directory: /private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-pip-egg-info-zv9v4d3p
    Running command python setup.py egg_info
    OMP: Error #13: Assertion failure at kmp_csupport.cpp(597).
    OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
ERROR: Command errored out with exit status -6: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
    return [
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
    return [
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 257, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status -6: python setup.py egg_info Check the logs for full command output.
Removed torch-scatter from https://files.pythonhosted.org/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz#sha256=148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f from build tracker '/private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o'
Removed build tracker: '/private/var/folders/r7/rnj5vh6j0dq2n3k7sf9q6rf40000gn/T/pip-req-tracker-avwsnj4o'
```

**Comment by rusty1s** [comment]
`OMP: Error #13: Assertion failure at kmp_csupport.cpp(597)` suggests that this is an issue with PyTorch/OpenMP. Not yet sure how to fix it though.

**Comment by rusty1s** [comment]
Python 3.9 wheels are now included :)
