### ISSUE TITLE
Problem with using spspmm_cuda in torch_sparse library

### ISSUE THREAD

**Issue by shreygadiya** [rusty1s/pytorch_geometric#20]
Hi, I have been using the MNIST example and received the following error when I use CUDA, 

Traceback (most recent call last):
  File "MNIST.py", line 7, in <module>
    from torch_geometric.datasets import MNISTSuperpixels
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_geometric/datasets/__init__.py", line 1, in <module>
    from .tu_dataset import TUDataset
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 5, in <module>
    from torch_geometric.data import InMemoryDataset, download_url, extract_zip
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_geometric/data/__init__.py", line 3, in <module>
    from .data import Data
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_geometric/data/data.py", line 2, in <module>
    from torch_geometric.utils import (contains_isolated_nodes,
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_geometric/utils/__init__.py", line 3, in <module>
    from .undirected import is_undirected, to_undirected
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_geometric/utils/undirected.py", line 2, in <module>
    from torch_sparse import coalesce
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_sparse/__init__.py", line 4, in <module>
    from .spspmm import spspmm
  File "/home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/torch_sparse/spspmm.py", line 7, in <module>
    import spspmm_cuda
ImportError: /home/Drive2/shrey/shrey/venv2/local/lib/python2.7/site-packages/spspmm_cuda.so: undefined symbol: cusparseDcsrgemm

Although when I set os.environ["CUDA_VISIBLE_DEVICES"]="" the problem disappears. Since the CPU implementation is too slow, can you suggest how to solve this issue? 

I am using virtualenv and Pytorch 0.4.1
Thanks

**Comment by rusty1s** [comment]
Hi, this refers to https://github.com/rusty1s/pytorch_sparse/issues/1.

Please follow the suggested workaround:
> You can clone torch-sparse locally, remove the spspmm import in torch_sparse/init.py and run python setup.py install. Sparse sparse matrix multiplication currently has no use case in torch_geometric, but this may change in the near future.
