### ISSUE TITLE
Gated Graph batch size doesn'e match.

### ISSUE THREAD

**Issue by RuihongQiu** [rusty1s/pytorch_geometric#205]
## ❓ Questions & Help

Substituting `GCNConv` and `GATConv` with a `GatedGraphConv` causes this error in some batch (after some correct batchs computation).
For definition:

    self.gated = GatedGraphConv(self.hidden_size, num_layers=1)
    hidden2 = self.gated(embedding, edge_index)

For running result:

    2019-04-13 21:20:39,193 train.py[line:23] 1
    2019-04-13 21:20:39,241 train.py[line:23] 2
    2019-04-13 21:20:39,292 train.py[line:23] 3
    2019-04-13 21:20:39,341 train.py[line:23] 4
    2019-04-13 21:20:39,391 train.py[line:23] 5

    Traceback (most recent call last):
      File "/home/test/Downloads/SR-GCN/src/main.py", line 74, in <module>
        main()
      File "/home/test/Downloads/SR-GCN/src/main.py", line 68, in main
        train_flag=True)
      File "/home/test/Downloads/SR-GCN/src/train.py", line 27, in forward
        scores = model(batch.to(device))
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 
    489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/test/Downloads/SR-GCN/src/model.py", line 78, in forward
        hidden2 = self.gated(embedding, edge_index)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 
    489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/test/pt-1.0/lib/python3.6/site- 
    packages/torch_geometric/nn/conv/gated_graph_conv.py", line 64, in forward
        h = self.rnn(m, h)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 
    489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 796, 
    in forward
        self.check_forward_hidden(input, hx)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 572, 
    in check_forward_hidden
        input.size(0), hidden_label, hx.size(0)))
    RuntimeError: Input batch size 321 doesn't match hidden batch size 322

Could you please help me?
Some of the graphs may contain only 1 node. Would it be the cause of the problem?

**Comment by rusty1s** [comment]
Can you pull from master and see if this fixes your problem?

**Comment by RuihongQiu** [comment]
Cool! Thanks!
