### ISSUE TITLE
module 'av' has no attribute 'logging'

### ISSUE THREAD

**Issue by ldv1** [rusty1s/pytorch_geometric#2059]
## 🐛 Bug

I want to create a modified version of `avg_pool_neighbor_x`. 

## To Reproduce

Run the following

```
import torch
from torch_geometric.utils import add_self_loops
from torch_scatter import scatter
                                
def avg_pool_neighbor_x(x, edge_index, flow='source_to_target'):
    num_nodes = torch.max(torch.max(edge_index)).item() + 1
    edge_index, _ = add_self_loops(edge_index, num_nodes=num_nodes)
    
    row, col = edge_index
    row, col = (row, col) if flow == 'source_to_target' else (col, row)

    y = scatter(x[row], col, dim=0, dim_size=num_nodes, reduce='mean')
    return y

x = torch.tensor( [[ 1.,0],[4.,5],[2,3],[6,-1] ] )
edge_index = torch.tensor( [ [0, 0, 1, 2, 2, 2, 3, 3], 
                             [2, 3, 2, 0, 1, 3, 0, 2 ] ])

print(avg_pool_neighbor_x(x, edge_index))

```

## Expected behavior

It outputs the correct answer.
However, it also spits out
```

Traceback (most recent call last):
  File "av.py", line 2, in <module>
    from torch_geometric.utils import add_self_loops
  File "/usr/lib/python3.6/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.datasets
  File "/usr/lib/python3.6/site-packages/torch_geometric/datasets/__init__.py", line 32, in <module>
    from .willow_object_class import WILLOWObjectClass
  File "/usr/lib/python3.6/site-packages/torch_geometric/datasets/willow_object_class.py", line 14, in <module>
    import torchvision.models as models
  File "/usr/lib64/python3.6/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import datasets
  File "/usr/lib64/python3.6/site-packages/torchvision/datasets/__init__.py", line 22, in <module>
    from .kinetics import Kinetics400
  File "/usr/lib64/python3.6/site-packages/torchvision/datasets/kinetics.py", line 3, in <module>
    from .video_utils import VideoClips
  File "/usr/lib64/python3.6/site-packages/torchvision/datasets/video_utils.py", line 7, in <module>
    from torchvision.io import (
  File "/usr/lib64/python3.6/site-packages/torchvision/io/__init__.py", line 14, in <module>
    from .video import (
  File "/usr/lib64/python3.6/site-packages/torchvision/io/video.py", line 17, in <module>
    av.logging.set_level(av.logging.ERROR)
AttributeError: module 'av' has no attribute 'logging'
```

## Environment

* OS: Linux Open Suse 15.2
* Python version: 3.6.12
* PyTorch version: 1.7.1+cpu
* CUDA/cuDNN version: -
* GCC version: 7.5.0
* Any other relevant information:

**Comment by rusty1s** [comment]
Seems to be a problem with `torchvision`. Can you check that your `torchvision` works as expected?

**Comment by ldv1** [comment]
A stupid error: Torch vision imports av (ffmpeg), and my small piece of code was unfortunately named av.py (short for averaging)...
