### ISSUE TITLE
Question about Graph SAGE implementation

### ISSUE THREAD

**Issue by jianchaoji** [rusty1s/pytorch_geometric#2060]
## ❓ Questions & Help

Thank you for sharing! One quick question, for the graph sage implementation, you posted three examples. I'm a little bit confused, they are supervised learning or unsupervised learning ?

**Comment by jianchaoji** [comment]
As my understanding, all of these examples are supervised learning right. But we can use "examples/reddit.py" and "examples/autoencoder.py" to implement the unsupervised, is that right?

**Comment by rusty1s** [comment]
`examples/reddit.py` is a fully supervised example, while `examples/graph_sage_unsup.py` implements the unsupervised GraphSAGE procedure. Learned embeddings are then evaluated on a down-stream task using logistic regression.

**Comment by jianchaoji** [comment]
Got it! Thank you for your reply!

**Comment by jianchaoji** [comment]
I have some issues when I try to run examples/graph_sage_unsup.py. But I met some issues:
Traceback (most recent call last):
  File "graph_sage_unsup.py", line 115, in <module>
    loss = train()
  File "graph_sage_unsup.py", line 81, in train
    for batch_size, n_id, adjs in train_loader:
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "graph_sage_unsup.py", line 25, in sample
    row, col, _ = self.adj.coo()
AttributeError: 'NeighborSampler' object has no attribute 'adj'

**Comment by jianchaoji** [comment]
But I can run the example/gcn.py correctly.

**Comment by jianchaoji** [comment]
Environment

- Python 3.7.6
- OS Ubuntu 5.4.0
- PyTorch 1.7.1
- Cuda 9.2
- torch-sparse 0.6.8
- torchvision 0.8.2

OS: Ubuntu 16.04
Python version: 3.6
PyTorch version: 1.7
CUDA/cuDNN version: 10.2
GCC version: 5.4.0

**Comment by rusty1s** [comment]
Should be fixable by installing PyG from master:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by jianchaoji** [comment]
Thank you for your reply.I tried that, but it is still not working. And it is the same issue as the last one.
try to run `examples/graph_sage_unsup.py:`
```
Traceback (most recent call last):
  File "graph_sage_unsup.py", line 115, in <module>
    loss = train()
  File "graph_sage_unsup.py", line 81, in train
    for batch_size, n_id, adjs in train_loader:
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "graph_sage_unsup.py", line 25, in sample
    row, col, _ = self.adj.coo()
AttributeError: 'NeighborSampler' object has no attribute 'adj'
```

**Comment by jianchaoji** [comment]
And I reviewed the class 'NeighborSampler' in `examples/graph_sage_unsup.py:`

`class NeighborSampler(RawNeighborSampler):
    def sample(self, batch):
        batch = torch.tensor(batch)
        row, col, _ = self.adj.coo()
        # For each node in `batch`, we sample a direct neighbor (as positive
        # example) and a random node (as negative example):
        pos_batch = random_walk(row, col, batch, walk_length=1,
                                coalesced=False)[:, 1]
        neg_batch = torch.randint(0, self.adj.size(0), (batch.numel(), ),
                                  dtype=torch.long)

        batch = torch.cat([batch, pos_batch, neg_batch], dim=0)
        return super(NeighborSampler, self).sample(batch)`

I also checked class RawNeighborSampler. We didn't have an attribute 'adj' in RawNeighborSampler, but we had an attribute 'adj_t' in RawNeighborSampler. I exchanged 'adj' with 'adj_t'. It could be complied, but I'm not sure it was correctly or not.

Looking forward your reply!

**Comment by rusty1s** [comment]
Indeed, you are right. Can you send a PR with the applied change? Would really appreciate it!

**Comment by jianchaoji** [comment]
Sure,no problem!
