### ISSUE TITLE
DataLoader gives strange error: All input tensors must be on the same device. Received cuda:0 and cpu

### ISSUE THREAD

**Issue by fransilvionGenomica** [rusty1s/pytorch_geometric#2077]
## 🐛 Bug

Hi,

I am trying to train my network with mini-batches using a DataLoader, however, in my for loop I am running into the following error:

RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

Noteworthy, it seems to happen later during the epoch. I am currently using the batch size 20, but this error comes up no matter what size I use (except size 1). The error seems to be with DataLoader, because when I preload all dataset to cuda, and then create DataLoader, this error goes away. 
`
data_list_train = [data.to(device) for data in data_list_train]
loader = DataLoader(data_list_train, batch_size=batch_size, shuffle=True)
`
Obviously, such solution is inefficient and will not work, when I have a huge dataset, which I won't be able to put on my gpu. A better solution is to put everything on cpu, however, it still doesn't cancel the issue with the data loader?

`
data_list_train = [data.to('cpu') for data in data_list_train]
loader = DataLoader(data_list_train, batch_size=batch_size, shuffle=True)
`

## To Reproduce

this is the example of my code:

`
learining_rate = 0.001
n_epochs = 100
batch_size = 20

loader = DataLoader(data_list_train, batch_size=batch_size, shuffle=True) #data_list_train is a list of objects type Data

for epoch in tqdm(range(n_epochs)):
        loss_epoch = 0.0

        #error seems to happen here
        for batch_id, data in enumerate(loader): 

            # fwd pass. To do: Train function.
            data = data.to(device)
            output = net(data.x, data.edge_index, data.edge_attr)
`

Here is the full text of error

> Traceback (most recent call last):

  File "<ipython-input-2-5a2b2227e71b>", line 27, in <module>
    for batch_id, data in enumerate(loader):

  File "/home/gherman/anaconda3/envs/proteinsolver/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()

  File "/home/gherman/anaconda3/envs/proteinsolver/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration

  File "/home/gherman/anaconda3/envs/proteinsolver/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)

  File "/home/gherman/anaconda3/envs/proteinsolver/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 34, in __call__
    return self.collate(batch)

  File "/home/gherman/anaconda3/envs/proteinsolver/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 15, in collate
    return Batch.from_data_list(batch, self.follow_batch)

  File "/home/gherman/anaconda3/envs/proteinsolver/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 141, in from_data_list
    batch[key] = torch.cat(items, ref_data.__cat_dim__(key, item))

RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

## Expected behavior

I expect all data to be on cpu therefore there should not be any conflict when I load the data from the loader. However, it seems not to be the case.

## Environment

* OS: Ubuntu 20.04.1 LTS
* Python version: 3.8.6
* PyTorch version: 1.7.0
* CUDA/cuDNN version: 11.2
* GCC version: 9.3.0
* Any other relevant information:
* pytorch_geometric: 1.6.3

**Comment by rusty1s** [comment]
Mh, I'm not exactly sure what's causing this and I cannot seem to reproduce this. Do you can give me a minimal example to reproduce? Does the same error happen for any datasets provided by PyG, e.g., `TUDataset`?
