### ISSUE TITLE
PyTorch Geometric TorchScript generation with low level operations from aten library

### ISSUE THREAD

**Issue by adhithadias** [rusty1s/pytorch_geometric#2127]
Hi, I am trying to generate the TorchScript for the https://pytorch-geometric.readthedocs.io/en/latest/notes/jit.html simple graph in this document.

I am printing the model.graph and below is what I get but this code does not include any low-level operations used in the neural network graph, like the functions from aten::mm, aten::add

```
graph(%self : __torch__.models.GCNNet,
      %x.1 : Tensor,
      %edge_index.1 : Tensor):
  %27 : Function = prim::Constant[name="log_softmax"]()
  %25 : int = prim::Constant[value=3]()
  %16 : Function = prim::Constant[name="dropout"]()
  %10 : Function = prim::Constant[name="relu"]()
  %9 : bool = prim::Constant[value=0]()
  %6 : None = prim::Constant()
  %13 : float = prim::Constant[value=0.59999999999999998]() # /src/models.py:15:27
  %24 : int = prim::Constant[value=1]() # /src/models.py:17:36
  %3 : __torch__.GCNConvJittable_bce75b.GCNConvJittable_bce75b = prim::GetAttr[name="conv1"](%self)
  %x.3 : Tensor = prim::CallMethod[name="forward__0"](%3, %x.1, %edge_index.1, %6) # /src/models.py:13:12
  %x.5 : Tensor = prim::CallFunction(%10, %x.3, %9) # /src/models.py:14:12
  %14 : bool = prim::GetAttr[name="training"](%self)
  %x.7 : Tensor = prim::CallFunction(%16, %x.5, %13, %14, %9) # /src/models.py:15:12
  %18 : __torch__.GCNConvJittable_bce75b.___torch_mangle_0.GCNConvJittable_bce75b = prim::GetAttr[name="conv2"](%self)
  %x.9 : Tensor = prim::CallMethod[name="forward__0"](%18, %x.7, %edge_index.1, %6) # /src/models.py:16:12
  %28 : Tensor = prim::CallFunction(%27, %x.9, %24, %25, %6) # /src/models.py:17:15
  return (%28)
```

But it doesn't print out the low level operations used from the aten library?
Is there a way to generate those as well? Like the below torchscript which I got from a different non pytorch geometric code.

```
graph(%self : __torch__.LSTMCell,
 %input.1 : Tensor,
 %state.1 : (Tensor, Tensor)):
%23 : int = prim::Constant[value=4]() # ../eg.py:24:60
%24 : int = prim::Constant[value=1]() # ../eg.py:24:63
%hx.1 : Tensor, %cx.1 : Tensor = prim::TupleUnpack(%state.1)
%7 : Tensor = prim::GetAttr[name="weight_ih"](%self)
%8 : Tensor = **_aten::t_**(%7) # ../eg.py:22:33
%9 : Tensor = _**aten::mm**_(%input.1, %8) # ../eg.py:22:17
%10 : Tensor = prim::GetAttr[name="bias_ih"](%self)
%12 : Tensor = _**aten::add**_(%9, %10, %24) # ../eg.py:22:17
%14 : Tensor = prim::GetAttr[name="weight_hh"](%self)
%15 : Tensor = _**aten::t**_(%14) # ../eg.py:23:30
%16 : Tensor = _**aten::mm**_(%hx.1, %15) # ../eg.py:23:17
%18 : Tensor = _**aten::add**_(%12, %16, %24) # ../eg.py:22:17
%19 : Tensor = prim::GetAttr[name="bias_hh"](%self)
%gates.1 : Tensor = _**aten::add**_(%18, %19, %24) # ../eg.py:22:17
...

```

**Comment by rusty1s** [comment]
It looks like `model.graph` prints only top-level ops. Something like `print(torch.jit.script(model.lin).graph)` prints out the expected result for a `Linear` layer. For GNN layers, you need to make typing explicit though, as otherwise PyTorch cannot print the model graph:
```
print(torch.jit.script(model.conv1.jittable('(Tensor, Tensor, OptTensor) -> Tensor')).graph)

**Comment by adhithadias** [comment]
I tried as mentioned in your reply @rusty1s but I am unable to print it. 

I get this error for 
`print(torch.jit.script(model.conv1.jittable('(Tensor, Tensor, OptTensor) -> Tensor')).graph)`

```
Traceback (most recent call last):
  File "src/gcn.py", line 63, in <module>
    print(torch.jit.script(model.conv1.jittable('(Tensor, Tensor, OptTensor) -> Tensor')).graph)
TypeError: 'NoneType' object is not callable
```

I also tried 
```
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


class GCNNet(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(GCNNet, self).__init__()
        self.conv1 = torch.jit.script(GCNConv(input_dim, 16).jittable())
        self.conv2 = torch.jit.script(GCNConv(16, output_dim).jittable())

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)
```
By adding torch.jit.script() where self.conv1 and self.conv2 is set. I get a different error for this scenario.
```
Traceback (most recent call last):
  File "src/gcn.py", line 63, in <module>
    print(model.conv1.graph)
  File "/GNN/projects/scratchpyg/venv/lib/python3.8/site-packages/torch/jit/_script.py", line 558, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/GNN/projects/scratchpyg/venv/lib/python3.8/site-packages/torch/jit/_script.py", line 288, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/GNN/projects/scratchpyg/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'graph'
```

I am not sure what I am doing wrong here. Any help would be highly appreciated.


Below are the 2 files that I am trying to run which I got from pytorch geometric torchscript examples
**models.py**
```
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


class GCNNet(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(GCNNet, self).__init__()
        self.conv1 = torch.jit.script(GCNConv(input_dim, 16).jittable())
        self.conv2 = torch.jit.script(GCNConv(16, output_dim).jittable())

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)
```
And the script to run it. **gcn.py**
```
import os.path as osp

import torch
import torch.nn.functional as F
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T
from models import GCNNet

jit_enabled = True

@torch.no_grad()
def test():
    model.eval()
    logits, accs = model(data.x, data.edge_index), []
    for _, mask in data('train_mask', 'val_mask', 'test_mask'):
        pred = logits[mask].max(1)[1]
        acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()
        accs.append(acc)
    return accs


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

dataset = 'Cora'
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', '..', 'data',
                dataset)
dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())

data = dataset[0].to(device)

model = GCNNet(dataset.num_node_features, dataset.num_classes).to(device)
if jit_enabled:
    model = torch.jit.script(model)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)


def train():
    model.train()
    optimizer.zero_grad()
    out = model(data.x, data.edge_index)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    return loss.detach().item()


for epoch in range(1, 201):
    loss = train()
    train_acc, val_acc, test_acc = test()
    print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, '
          f'Train: {train_acc:.4f}, Val: {val_acc:.4f}, Test: {test_acc:.4f}')

file = 'gcn.pt'
model_path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'model', file)

model.eval()
if jit_enabled:
    torch.jit.save(model, model_path)
    print("\n\n-------MODEL-------\n")
    print(model)
    print("\n\n-------MODEL GRAPH-------\n")
    print(model.graph)
    # print(model.conv1.graph)  -------------------------- error line
    print("\n\n-------MODEL CODE-------\n")
    print(model.code)
else:
    torch.save(model.state_dict(), model_path)

print(model)
```

**Comment by rusty1s** [comment]
The following works for me:
```python
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


class GCN(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(GCN, self).__init__()
        conv1 = GCNConv(input_dim, 16)
        self.conv1 = conv1.jittable('(Tensor, Tensor, OptTensor) -> Tensor')
        conv2 = GCNConv(16, output_dim)
        self.conv2 = conv2.jittable('(Tensor, Tensor, OptTensor) -> Tensor')

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=-1)


model = GCN(128, 128)

print(torch.jit.script(model).graph)
print('--------')
print(torch.jit.script(model.conv1).graph)
```

**Comment by adhithadias** [comment]
It works. Thanks a bunch, @rusty1s
