### ISSUE TITLE
torch-scatter failing to install

### ISSUE THREAD

**Issue by David-Balcells** [rusty1s/pytorch_geometric#2140]
## Environment

* OS: Ubuntu 18.04
* Python version: 3.6
* PyTorch version: 1.7.1
* CUDA/cuDNN version: 10.1
* GCC version: 7.5.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): With pip3
* Any other relevant information:

## Checklist

- [yes] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [yes] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [yes] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [yes] I do have multiple CUDA versions on my machine.

## Additional context

I installed torch 1.7.1 with

pip3 install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

successfully

Then torch-scatter with

pip3 install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html

also successfully

but then, for torch-sparse, 

pip3 install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html

I get this error message

Could not find a version that satisfies the requirement scipy (from torch-sparse) (from versions: )
No matching distribution found for scipy (from torch-sparse)

**Comment by rusty1s** [comment]
You can try to manually install `scipy` before installing `torch-sparse`. This should fix this issue.

**Comment by David-Balcells** [comment]
Sure, here is the full log:

Ignoring indexes: https://pypi.python.org/simple
Collecting torch-sparse
  1 location(s) to search for versions of torch-sparse:
  * https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
  Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html (from -f); unsupported archive format: .html
  Getting page https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
  Looking up "https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html" in the cache
  Current age based on date: 129
  Freshness lifetime from max-age: 300
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 129
  Analyzing links from page https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_cluster-1.5.8-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_cluster-1.5.8-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_cluster-1.5.8-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_cluster-1.5.8-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_cluster-1.5.8-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_cluster-1.5.8-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.5-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.5-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.5-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.5-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.5-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Found link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html), version: 0.6.8
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); it is not compatible with this Python
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); it is not compatible with this Python
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); it is not compatible with this Python
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); it is not compatible with this Python
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); it is not compatible with this Python
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_spline_conv-1.2.0-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_spline_conv-1.2.0-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_spline_conv-1.2.0-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_spline_conv-1.2.0-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_spline_conv-1.2.0-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_spline_conv-1.2.0-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not torch-sparse)
  Using version 0.6.8 (newest of versions: 0.6.8)
  Looking up "https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp36-cp36m-linux_x86_64.whl" in the cache
  Current age based on date: 62
  Freshness lifetime from max-age: 86400
  The response is "fresh", returning cached response
  86400 > 62
  Using cached https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp36-cp36m-linux_x86_64.whl
  Downloading from URL https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html)
Collecting scipy (from torch-sparse)
  1 location(s) to search for versions of scipy:
  * https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
  Getting page https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
  Looking up "https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html" in the cache
  Current age based on date: 130
  Freshness lifetime from max-age: 300
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 130
  Analyzing links from page https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
    Skipping link https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.8-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html); wrong project name (not scipy)
  Could not find a version that satisfies the requirement scipy (from torch-sparse) (from versions: )
Cleaning up...
No matching distribution found for scipy (from torch-sparse)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for scipy (from torch-sparse)

**Comment by rusty1s** [comment]
Can you confirm that `scipy` is already installed on your system? It seems that later versions of `scipy` require Python >= 3.7, which might be the cause of this issue.

**Comment by David-Balcells** [comment]
Yes, scipy is installed (version 1.5.4). For the installation, I used pip3. The python version is 3.6

**Comment by rusty1s** [comment]
Can you try to run without the `--no-index` option?
```
pip3 install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```

**Comment by David-Balcells** [comment]
Working now. I had problems with the torch-geometric package that seemed to be related with some confusing issues with llvmlite, but I fixed this by upgrading pip3 to version 21.0.1. Then, last problem seemed to be having different cuda versions (10.2 for torch vs. 10.1 for torch-sparse but I could fix this by reinstalling torch with version 1.7.0 and cuda 10.1). Seems to work well now when running the examples of your tutorials. Thanks for your support and for the amazing tool you have developed for ML with graphs.
