### ISSUE TITLE
Loading data raises CUDA error

### ISSUE THREAD

**Issue by suxuann** [rusty1s/pytorch_geometric#2169]
## 🐛 Bug

I have a GraphSAINTRandomWalkSampler data loader. When I put data on CPU, everything runs smoothly. When I put the tensors onto cuda, it raises the following bug:

```
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main()
  File "main.py", line 40, in main
    loss = training.train(model, data_loader, optimizer)
  File "training.py", line 16, in train
    for data in loader:
  File "lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lib/python3.8/site-packages/torch_geometric/data/graph_saint.py", line 93, in __getitem__
    node_idx = self.__sample_nodes__(self.__batch_size__).unique()
  File "lib/python3.8/site-packages/torch_geometric/data/graph_saint.py", line 214, in __sample_nodes__
    node_idx = self.adj.random_walk(start.flatten(), self.walk_length)
  File "lib/python3.8/site-packages/torch_sparse/rw.py", line 8, in random_walk
    return torch.ops.torch_sparse.random_walk(rowptr, col, start, walk_length)
RuntimeError: start.device().is_cuda() INTERNAL ASSERT FAILED at "/home/travis/build/rusty1s/pytorch_sparse/csrc/cuda/rw_cuda.cu":35, please report a bug to PyTorch. start must be CUDA tensor
```

## To Reproduce

```
# data is a tensor on GPU
def get_minibatch_loader(data):
    sampler = GraphSAINTRandomWalkSampler(
        data,
        batch_size=TrainingConfig.training_batch_size,
        walk_length=TrainingConfig.walk_length,
        num_steps=TrainingConfig.num_steps,
        sample_coverage=0,
        save_dir=Config.dataset_dir
    )
    return sampler

loader = get_minibatch_loader(data)
for d in loader:
    # The above raises the bug
```

## Environment

* OS: Linux 18.04
* Python version: 3.8.5
* PyTorch version: 1.7.1
* CUDA/cuDNN version: 9.0.176
* GCC version: 7.5.0
* Any other relevant information:

**Comment by rusty1s** [comment]
Yes, `GraphSAINT` data loading routines are designed to work on CPU, while each mini-batch is then passed to the GPU for further processing. I added a check that input data to GraphSAINT needs to be stored on the CPU.

**Comment by suxuann** [comment]
What about other samplers like RandomNodeSampler and RandomEdgeSampler?
