### ISSUE TITLE
Problems when try to read NELL dataset

### ISSUE THREAD

**Issue by jianchaoji** [rusty1s/pytorch_geometric#2208]
## 🐛 Bug

Processing...
Traceback (most recent call last):
  File "graph_sage_unsup.py", line 19, in <module>
    dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/planetoid.py", line 56, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/planetoid.py", line 109, in process
    data = read_planetoid_data(self.raw_dir, self.name)
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/io/planetoid.py", line 84, in read_planetoid_data
    x[test_index] = x[sorted_test_index]
IndexError: index 34468 is out of bounds for dimension 0 with size 9891

## To Reproduce
I download the nell dataset on the github:"https://github.com/ShengyuPei/planetoid_datasets". And try to use it on graph_sage_unsup.py. I met some problems in this procedure. Can I get some help?
 
1.Download NELL 
2.Tried to used this dataset on graph_sage_unsup.py

## Environment

Python 3.7.6
OS Ubuntu 5.4.0
PyTorch 1.7.1
Cuda 9.2
torch-sparse 0.6.8
torchvision 0.8.2

**Comment by rusty1s** [comment]
Can you show me an example to reproduce? How did you read in the `NELL` dataset? In addition, please ensure that your `data` is correct, e.g., `data.edge_index.max() < data.num_nodes`.

**Comment by jianchaoji** [comment]
I used the function in io.py
"""
def read_planetoid_data(folder, prefix):
    names = ['x', 'tx', 'allx', 'y', 'ty', 'ally', 'graph', 'test.index']
    items = [read_file(folder, prefix, name) for name in names]
    x, tx, allx, y, ty, ally, graph, test_index = items
    train_index = torch.arange(y.size(0), dtype=torch.long)
    val_index = torch.arange(y.size(0), y.size(0) + 500, dtype=torch.long)
    sorted_test_index = test_index.sort()[0]

    if prefix.lower() == 'citeseer':
        # There are some isolated nodes in the Citeseer graph, resulting in
        # none consecutive test indices. We need to identify them and add them
        # as zero vectors to `tx` and `ty`.
        len_test_indices = (test_index.max() - test_index.min()).item() + 1

        tx_ext = torch.zeros(len_test_indices, tx.size(1))
        tx_ext[sorted_test_index - test_index.min(), :] = tx
        ty_ext = torch.zeros(len_test_indices, ty.size(1))
        ty_ext[sorted_test_index - test_index.min(), :] = ty

        tx, ty = tx_ext, ty_ext

    x = torch.cat([allx, tx], dim=0)
    y = torch.cat([ally, ty], dim=0).max(dim=1)[1]

    x[test_index] = x[sorted_test_index]
    y[test_index] = y[sorted_test_index]

    train_mask = index_to_mask(train_index, size=y.size(0))
    val_mask = index_to_mask(val_index, size=y.size(0))
    test_mask = index_to_mask(test_index, size=y.size(0))

    edge_index = edge_index_from_dict(graph, num_nodes=y.size(0))

    data = Data(x=x, edge_index=edge_index, y=y)
    data.train_mask = train_mask
    data.val_mask = val_mask
    data.test_mask = test_mask

    return data
"""

**Comment by rusty1s** [comment]
Yes, that sadly does not work. You can see [this](https://github.com/tkipf/gcn/issues/14) thread on how to load the `NELL` dataset. I will work on adding this dataset to the library.

**Comment by jianchaoji** [comment]
Thank you for your reply! I tried that one but it had some problems. I will tell you if I fix it!

```
    dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/planetoid.py", line 56, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/planetoid.py", line 109, in process
    data = read_planetoid_data(self.raw_dir, self.name)
  File "/home/jj635/anaconda3/lib/python3.7/site-packages/torch_geometric/io/planetoid.py", line 84, in read_planetoid_data
    x = torch.cat([allx, tx], dim=0)
TypeError: expected Tensor as element 1 in argument 0, but got lil_matrix
```

**Comment by rusty1s** [comment]
The `NELL` dataset is now available in master, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/nell.py).
