### ISSUE TITLE
Data error in benchmark/kernal

### ISSUE THREAD

**Issue by vjleung** [rusty1s/pytorch_geometric#2258]
## 🐛 Bug

MUTAG - EdgePool
Val Loss: 0.5314, Test Accuracy: 0.702 ± 0.110, Duration: 1.561
Val Loss: 0.5185, Test Accuracy: 0.744 ± 0.111, Duration: 1.615
Val Loss: 0.5009, Test Accuracy: 0.750 ± 0.074, Duration: 1.777
Val Loss: 0.4920, Test Accuracy: 0.713 ± 0.069, Duration: 2.219
Val Loss: 0.5232, Test Accuracy: 0.718 ± 0.081, Duration: 2.077
Val Loss: 0.4872, Test Accuracy: 0.729 ± 0.084, Duration: 2.380
Val Loss: 0.4902, Test Accuracy: 0.729 ± 0.091, Duration: 3.162
Val Loss: 0.4817, Test Accuracy: 0.735 ± 0.064, Duration: 5.940
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    loss, acc, std = cross_validation_with_val_set(
  File "/Users/vjleung/Desktop/exagraph/pytorch_geometric-master/benchmark/kernel/train_eval.py", line 43, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "/Users/vjleung/Desktop/exagraph/pytorch_geometric-master/benchmark/kernel/train_eval.py", line 114, in train
    out = model(data)
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/vjleung/Desktop/exagraph/pytorch_geometric-master/benchmark/kernel/edge_pool.py", line 42, in forward
    x, edge_index, _, batch, _, _ = pool(x, edge_index,
ValueError: not enough values to unpack (expected 6, got 4)

## To Reproduce

1. in benchmark/kernal
1. run python main.py
1.

MUTAG - EdgePool
Val Loss: 0.5314, Test Accuracy: 0.702 ± 0.110, Duration: 1.561
Val Loss: 0.5185, Test Accuracy: 0.744 ± 0.111, Duration: 1.615
Val Loss: 0.5009, Test Accuracy: 0.750 ± 0.074, Duration: 1.777
Val Loss: 0.4920, Test Accuracy: 0.713 ± 0.069, Duration: 2.219
Val Loss: 0.5232, Test Accuracy: 0.718 ± 0.081, Duration: 2.077
Val Loss: 0.4872, Test Accuracy: 0.729 ± 0.084, Duration: 2.380
Val Loss: 0.4902, Test Accuracy: 0.729 ± 0.091, Duration: 3.162
Val Loss: 0.4817, Test Accuracy: 0.735 ± 0.064, Duration: 5.940
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    loss, acc, std = cross_validation_with_val_set(
  File "/Users/vjleung/Desktop/exagraph/pytorch_geometric-master/benchmark/kernel/train_eval.py", line 43, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "/Users/vjleung/Desktop/exagraph/pytorch_geometric-master/benchmark/kernel/train_eval.py", line 114, in train
    out = model(data)
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/vjleung/Desktop/exagraph/pytorch_geometric-master/benchmark/kernel/edge_pool.py", line 42, in forward
    x, edge_index, _, batch, _, _ = pool(x, edge_index,
ValueError: not enough values to unpack (expected 6, got 4)

## Expected behavior

No error

## Environment

* OS: macOS High Sierra
* Python version: 3.8.5
* PyTorch version: latest
* CUDA/cuDNN version: 
* GCC version: Apple version 10.0.0
* Any other relevant information:

**Comment by rusty1s** [comment]
Indded. Should be fixed in master.
