### ISSUE TITLE
Infomax error

### ISSUE THREAD

**Issue by PeijiYang** [rusty1s/pytorch_geometric#228]

**Comment by PeijiYang** [comment]
hello，i run the infomax.py, and get error as follow:
Traceback (most recent call last):
  File "infomax.py", line 64, in <module>
    acc = test()
  File "infomax.py", line 57, in test
    max_iter=150)
  File "/data/ldf/anaconda3/lib/python3.6/site-packages/torch_geometric-1.1.3-py3.6.egg/torch_geometric/nn/models/deep_graph_infomax.py", line 86, in test
  File "/data/ldf/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py", line 1222, in fit
    self.dual)
  File "/data/ldf/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py", line 434, in _check_solver_option
    "ovr, got %s" % multi_class)
ValueError: multi_class should be either multinomial or ovr, got auto

**Comment by PeijiYang** [comment]
update sklearn，solve it
