### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by shxzhao** [rusty1s/pytorch_geometric#2304]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

When I run the program after I install the pytorch_geometric, there is  a error.
Traceback (most recent call last):
  File "/home/zhao/PycharmProjects/My_GNN_1/test_geometric_2.py", line 4, in <module>
    from torch_geometric.nn import GATConv
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'

**Comment by rusty1s** [comment]
How did you try to install `torch-scatter`? In general, this suggests that the corresponding CUDA/CPU shared libraries are not properly installed.

**Comment by rusty1s** [comment]
You might want to check if there exists any `*.so` files in `/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_sparse`.

**Comment by shxzhao** [comment]
Thanks for your reply! @rusty1s  Yes，I have installed torch-scatter ,I failed install the cpu version.But I succeed in installing the CUDA version.

**Comment by w29593617** [comment]
> You might want to check if there exists any `*.so` files in `/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_sparse`.

Hi @rusty1s, a similar issue occurred to me when I run the following commands in Pyython cli, 
```python
import torch
import torch_geometric
```
Traceback indicates
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 4, in <module>
    from .conv import *  # noqa
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/site-packages/torch_geometric/nn/conv/__init__.py", line 6, in <module>
    from .gravnet_conv import GravNetConv
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/site-packages/torch_geometric/nn/conv/gravnet_conv.py", line 11, in <module>
    from torch_cluster import knn
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/site-packages/torch_cluster/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
```

But as your instructions above, I check my `xxx/site-packages/torch_cluster` folder and the files exists
```bash
.
|-- __init__.py
|-- __pycache__
|   |-- __init__.cpython-37.pyc
|   |-- fps.cpython-37.pyc
|   |-- graclus.cpython-37.pyc
|   |-- grid.cpython-37.pyc
|   |-- knn.cpython-37.pyc
|   |-- nearest.cpython-37.pyc
|   |-- radius.cpython-37.pyc
|   |-- rw.cpython-37.pyc
|   `-- sampler.cpython-37.pyc
|-- _fps_cpu.so
|-- _graclus_cpu.so
|-- _grid_cpu.so
|-- _knn_cpu.so
|-- _nearest_cpu.so
|-- _radius_cpu.so
|-- _rw_cpu.so
|-- _sampler_cpu.so
|-- _version_cpu.so
|-- fps.py
|-- graclus.py
|-- grid.py
|-- knn.py
|-- nearest.py
|-- radius.py
|-- rw.py
`-- sampler.py
```

I also tried to reinstall `torch_cluster`, but did not work. My current env has `Python 3.7, torch 1.6.0, and CUDA 10.1`. 

Would you please kindly help to solve my issue? 

Best Regards

**Comment by JiayuanDing100** [comment]
I met with the same issue. As you suggested, I checked there exists *.so files in anaconda3/envs/pytorch_3.7/lib/python3.7/site-packages/torch_sparse/.

add.py           convert.py       __init__.py       mul.py       reduce.py        saint.py        spmm.py         transpose.py
bandwidth.py     _diag_cpu.so     masked_select.py  narrow.py    _relabel_cpu.so  _sample_cpu.so  _spspmm_cpu.so  utils.py
cat.py           diag.py          matmul.py         padding.py   _rw_cpu.so       sample.py       spspmm.py       _version_cpu.so
coalesce.py      eye.py           _metis_cpu.so     permute.py   rw.py            select.py       storage.py
_convert_cpu.so  index_select.py  metis.py          __pycache__  _saint_cpu.so    _spmm_cpu.so    tensor.py

**Comment by rusty1s** [comment]
https://github.com/rusty1s/pytorch_sparse/issues/127

**Comment by jingzhengli** [comment]
> You might want to check if there exists any `*.so` files in `/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_sparse`.

It exists, what is the "*.so" means?  then what should I do
