### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by tricktreat** [rusty1s/pytorch_geometric#2315]
## To Reproduce

```bash
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html 
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-geometric  
```

```bash
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shenyl/miniconda/envs/cuda111/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/shenyl/miniconda/envs/cuda111/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/shenyl/miniconda/envs/cuda111/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/shenyl/miniconda/envs/cuda111/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/shenyl/miniconda/envs/cuda111/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/shenyl/miniconda/envs/cuda111/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```

## Environment

* OS: ubuntu 20.04
* Python version: 3.8.8
* PyTorch version: 1.8.1
* CUDA/cuDNN version: 11.1
* GCC version: 5.4.0
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Can you try to install via
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
```
Using `torch-1.8.1` is a dead link, and you can use the same wheels for PyTorch 1.8.1 as for PyTorch 1.8.0.

**Comment by tricktreat** [comment]
It's solved, thank you!

**Comment by malabikasen** [comment]
> Using torch-1.8.1+*.html is a dead link, and you can use the same wheels for PyTorch 1.8.1 as for PyTorch 1.8.0.

@rusty1s I think it is important to update this on the docs. I faced the same problem and had to waste a few hours when in fact I could have just used the link for torch 1.8.0.
I am happy to update it on the docs. What do you think?

**Comment by rusty1s** [comment]
Sure, please feel free to do so. Thanks:)
