### ISSUE TITLE
Error report in Installation of torch-scatter in Win10 cpu

### ISSUE THREAD

**Issue by Wanyu42** [rusty1s/pytorch_geometric#2357]
## Environment

* OS: Windows 10
* Python version: 3.9.1
* PyTorch version: 1.7.1
* CUDA/cuDNN version: cpu
* GCC version: gcc 8.1.0 (MinGW)
* How did you try to install PyTorch Geometric and its extensions (wheel, source): I tried to install torch-scatter through the wheel:  pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
* Any other relevant information:
The Error message is as follows:
....
segment_coo_cpu.cpp
    C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(389): warning C4101: “e ”: 未引用的局部变量
    C:\Users\wanyu\AppData\Local\Temp\pip-install-e87q2jle\torch-scatter_14f809ae2a84415880b1f9b1a838031c\csrc\cpu\segment_coo_cpu.cpp : fatal error C1083: 无法打开编译器生成的文件: “”: Invalid argument
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached

## Checklist

- [ ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Can you try to install via
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
```

**Comment by Wanyu42** [comment]
It seems that there is no version

`pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/Torch-1.7.0+cpu.html`

ERROR: Could not find a version that satisfies the requirement torch-scatter
ERROR: No matching distribution found for torch-scatter

**Comment by rusty1s** [comment]
Please use a lowercase `t`:
```
https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
```

**Comment by Wanyu42** [comment]
Sorry, it is just a typo in the last comment.
With lowercase `t` it still gets the errors. 
Would it be possible that the problem comes from python 3.9?

**Comment by Wanyu42** [comment]
It seems that the problem is due to python3.9. I successfully downloaded torch_geometric with python3.8. However, when I tested with `import torch_geometric`, I encountered another error with `_scatter_cpu.pyd` ddl ( OSError: [WinError 127] The specified procedure could not be found.) :

>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\data\data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_sparse\__init__.py", line 36, in <module>
    from .storage import SparseStorage  # noqa
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_sparse\storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_scatter\__init__.py", line 13, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch\_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "C:\Users\wanyu\anaconda3\envs\graph\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

I wonder whether this error is caused by cpu version instead of cuda.

**Comment by rusty1s** [comment]
Yes, we currently do not yet provide wheels for Python 3.9, sorry! Do you have a PyTorch+CUDA installation? Then you will need to install the `torch-scatter` CUDA package as well. You should also verify that you do not have any previous `torch-scatter` installations by repeatedly running:
```
pip uninstall torch-scatter
```

**Comment by IceCereal** [comment]
To anyone in the future reading this and getting a: `fatal error C1083: Cannot open compiler generated file: '': Invalid argument` similar to this and the one referenced in issue #1958, there's a chance that this is happening: [VS 2015 Cannot open compiler generated file: '': Invalid argument](https://stackoverflow.com/questions/34074925/vs-2015-cannot-open-compiler-generated-file-invalid-argument). The SO answer says, "Seems that I was bumping into the path/filename length limitation of Visual Studio. The error message was not particularly descriptive, but reducing the hierarchy solved the problem"; this means that whatever file path was being passed while trying to install is over 260 characters long, the default Windows sets. The log says that it happens at this part:

`ERROR: Command errored out with exit status 1: 'd:\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-fsjcjgdf\\torch-scatter_1703e1f783e247f484059bc080a5aaa4\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-fsjcjgdf\\torch-scatter_1703e1f783e247f484059bc080a5aaa4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-yl965_fd\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python39\Include\torch-scatter' `

You can try to change the Windows registry value to allow long paths (guide [here](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/)) but that didn't work for me.

### Solution that worked for me:
If you tried to install it using pip following the instructions as provided on the PyTorch geometric [installation](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) page under the **Install via Binaries** section and this error happened, try to manually download the wheels from the https://pytorch-geometric.com/whl/ part that corresponds to your torch version & cuda version and do a pip install on the downloaded files (which is essentially the **Installation from Source** section below) . 

Also, like @rusty1s mentioned above, python3.9 isn't supported so make sure you're using python3.8 (at least for now until 3.9 support comes in). I realized that after downloading the wheels.

Tried doing too many things for a good two hours trying to figure out why I was repeatedly getting the same error when I just realized that this was just so much easier.

**Comment by HuangDDU** [comment]
> It seems that the problem is due to python3.9. I successfully downloaded torch_geometric with python3.8. However, when I tested with `import torch_geometric`, I encountered another error with `_scatter_cpu.pyd` ddl ( OSError: [WinError 127] The specified procedure could not be found.) :
> 
> > > > import torch_geometric
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric__init__.py", line 2, in 
> > > > import torch_geometric.nn
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\nn__init__.py", line 2, in 
> > > > from .data_parallel import DataParallel
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in 
> > > > from torch_geometric.data import Batch
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\data__init__.py", line 1, in 
> > > > from .data import Data
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_geometric\data\data.py", line 8, in 
> > > > from torch_sparse import coalesce, SparseTensor
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_sparse__init__.py", line 36, in 
> > > > from .storage import SparseStorage  # noqa
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_sparse\storage.py", line 5, in 
> > > > from torch_scatter import segment_csr, scatter_add
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_scatter__init__.py", line 13, in 
> > > > torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_ops.py", line 104, in load_library
> > > > ctypes.CDLL(path)
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\ctypes__init__.py", line 381, in **init**
> > > > self._handle = _dlopen(self._name, mode)
> > > > OSError: [WinError 127] 找不到指定的程序。
> 
> I wonder whether this error is caused by cpu version instead of cuda.

@ [wanyu42](https://github.com/wanyu42) I also met the question， 
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\site-packages\torch_ops.py", line 104, in load_library
> > > > ctypes.CDLL(path)
> > > > File "C:\Users\wanyu\anaconda3\envs\graph\lib\ctypes__init__.py", line 381, in **init**
> > > > self._handle = _dlopen(self._name, mode)
> > > > OSError: [WinError 127] 找不到指定的程序。
how do you deal with that？
