### ISSUE TITLE
Fail to download the dataset

### ISSUE THREAD

**Issue by hzcheney** [rusty1s/pytorch_geometric#2383]
## To Reproduce

1. Go to examples folder
2. Run `python gcn.py`

## Expected behavior

Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Traceback (most recent call last):
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 926, in connect
    self._tunnel()
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 900, in _tunnel
    (version, code, message) = response._read_status()
  File "/home/hzcheney/miniconda3/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gcn.py", line 17, in <module>
    dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())
  File "/home/hzcheney/miniconda3/lib/python3.8/site-packages/torch_geometric/datasets/planetoid.py", line 55, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "/home/hzcheney/miniconda3/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    super(InMemoryDataset, self).__init__(root, transform, pre_transform,
  File "/home/hzcheney/miniconda3/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 89, in __init__
    self._download()
  File "/home/hzcheney/miniconda3/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 141, in _download
    self.download()
  File "/home/hzcheney/miniconda3/lib/python3.8/site-packages/torch_geometric/datasets/planetoid.py", line 105, in download
    download_url('{}/{}'.format(self.url, name), self.raw_dir)
  File "/home/hzcheney/miniconda3/lib/python3.8/site-packages/torch_geometric/data/download.py", line 34, in download_url
    data = urllib.request.urlopen(url, context=context)
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/hzcheney/miniconda3/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Remote end closed connection without response>
## Environment

* OS: Linux labManjaro 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64 GNU/Linux
* Python version: 3.8.5
* PyTorch version: 1.7.1 + CPU
* CUDA/cuDNN version: NONE
* GCC version: gcc version 10.2.0 (GCC)
* Any other relevant information: http_proxy used

## Additional context

I tried to download the datasets through browser in the same network environment and it works fine, is this a protection strategy of github website when requests module open a url without headers ?Or this bug depends on the network environment that i am using?
Thank youu very much for your time!

**Comment by rusty1s** [comment]
I'm not sure what exactly is causing it, as it works fine for me. I'm happy to fix it in case you find the reason for why
```
urllib.request.urlopen(https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x)
```
fails on your side. Alternatively, you can simply download the data by yourself and put them into the `raw` directory.

**Comment by hzcheney** [comment]
Thanks a lot !I now believe that this is caused by the http_proxy variable.If I unset the http_proxy then everything becomes normal.
