### ISSUE TITLE
How to make a graph classification take by ClusterData?

### ISSUE THREAD

**Issue by Riofd** [rusty1s/pytorch_geometric#2406]
Hello, thank you for your great contributions!
 I have a question about ClusterData and ClusterLoader when I use them for a graph classification task. My dataset is with 30000 samples and each sample has around 2000 nodes.  I used a similar operation on PPI [dataset](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cluster_gcn_ppi.py) using ClusterData and ClusterLoader, but CUDA errors would occur:
```
train_dataset = dataset[:int(0.8 * num_samples)]
train_data = Batch.from_data_list(train_dataset)
cluster_data = ClusterData(train_data, num_parts=20, recursive=False,
                             save_dir=train_dataset.processed_dir)
train_loader = ClusterLoader(cluster_data, batch_size=batch_size, shuffle=True,
                               num_workers=12)
for data in train_loader:
    print(data)
```

  File "D:\Users\zrf\zdsw\ClusterGCN.py", line 21, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59

I have confirmed there was no problem with my GPU device, and I can normally train my model without ClusterData and ClusterLoader by GCN.

**Comment by rusty1s** [comment]
I'm not sure what's causing this error exactly. However, `ClusterData` is not really designed for graph classification in mind. In your case, it is best to use traditional mini-batching capabilities:
```python
loader = DataLoader(train_dataset, batch_size=..., shuffle=True)

for data in loader:
    print(data)
```

**Comment by Riofd** [comment]
Thank you for your reply.
But when I try this example [(cluster_gcn_ppi.py)](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cluster_gcn_ppi.py) and it also have errors: 
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\zrf\zdsw\PPI.py", line 11, in <module>
    torch.cuda.set_device(1)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\cuda\__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
Traceback (most recent call last):
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\utils\data\dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\multiprocessing\queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Users/zrf/zdsw/PPI.py", line 26, in <module>
    for data in train_loader:
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\utils\data\dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\utils\data\dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\ZhangRunfeng\anaconda3\envs\zrf\lib\site-packages\torch\utils\data\dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 28196, 30200, 10640, 27020, 12952, 25160, 15708, 4236, 16768, 11956, 28280, 30248) exited unexpectedly.

**Comment by rusty1s** [comment]
Can you check whether this works with `num_workers=0`?

**Comment by Riofd** [comment]
It works well when `num_workers=0`. Thank you!
