### ISSUE TITLE
AttributeError: 'GAE' object has no attribute 'decoder'

### ISSUE THREAD

**Issue by youjinChung** [rusty1s/pytorch_geometric#241]
## ❓ Questions & Help
Hello I was trying to decode of autoencoder, starting with checking test_autoencoder.py file under test/nn/models.
and is the error code:
```
Traceback (most recent call last):
  File "test_autoencoder.py", line 78, in <module>
    test_gae()
  File "test_autoencoder.py", line 15, in test_gae
    adj = model.decoder.forward_all(z)
  File "/home/paperspace/miniconda2/envs/thesis/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'GAE' object has no attribute 'decoder'
```
Even if I commend the adj part, I still get another error that says

```
Traceback (most recent call last):
  File "test_autoencoder.py", line 75, in <module>
    test_gae()
  File "test_autoencoder.py", line 20, in test_gae
    value = model.decode(z, edge_index)
  File "/home/paperspace/miniconda2/envs/thesis/lib/python3.6/site-packages/torch_geometric/nn/models/autoencoder.py", line 47, in decode
    return torch.sigmoid(adj) if sigmoid else adj
RuntimeError: bool value of Tensor with more than one value is ambiguous
```
and here's the code of test_autoencoder.py
```
def test_gae():
    model = GAE(encoder=lambda x: x)
    model.reset_parameters()

    x = torch.Tensor([[1, -1], [1, 2], [2, 1]])
    z = model.encode(x)
    assert z.tolist() == x.tolist()

    adj = model.decoder.forward_all(z)
    assert adj.tolist() == torch.sigmoid(
        torch.Tensor([[+2, -1, +1], [-1, +5, +4], [+1, +4, +5]])).tolist()
    # print("adj",adj.tolist())

    edge_index = torch.tensor([[0, 1], [1, 2]])
    value = model.decode(z, edge_index)
    assert value.tolist() == torch.sigmoid(torch.Tensor([-1, 4])).tolist()
    # print("value",value.tolist())

    edge_index = torch.tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                               [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
    data = Data(edge_index=edge_index)
    data.num_nodes = edge_index.max().item() + 1
    data = model.split_edges(data, val_ratio=0.2, test_ratio=0.3)

    assert data.val_pos_edge_index.size() == (2, 2)
    assert data.val_neg_edge_index.size() == (2, 2)
    assert data.test_pos_edge_index.size() == (2, 3)
    assert data.test_neg_edge_index.size() == (2, 3)
    assert data.train_pos_edge_index.size() == (2, 5)
    assert data.train_neg_adj_mask.size() == (11, 11)
    assert data.train_neg_adj_mask.sum().item() == (11**2 - 11) / 2 - 4 - 6 - 5

    z = torch.randn(11, 16)
    loss = model.recon_loss(z, data.train_pos_edge_index)
    assert loss.item() > 0

    auc, ap = model.test(z, data.val_pos_edge_index, data.val_neg_edge_index)
    assert auc >= 0 and auc <= 1 and ap >= 0 and ap <= 1

```
Ultimately, I want to know the proper way to decode to edgelist of the graph.

**Comment by rusty1s** [comment]
I guess you use the latest stable build from PyPi? The autoencoder model recently changed to allow customizable decoders. You therefore need to install PyG from master. I will draft a new PyPi version early next week.

**Comment by youjinChung** [comment]
yes it worked when I uninstalled pypi version and installed with git repo. Thank you so much!
