### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by dragonbook** [rusty1s/pytorch_geometric#247]
## 🐛 Bug

When I run [pointnet++](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet%2B%2B.py) example, it throws a run time error:
```
Traceback (most recent call last):
  File "examples/pointnet++.py", line 93, in <module>
    train(epoch)
  File "examples/pointnet++.py", line 75, in train
    loss = F.nll_loss(model(data), data.y)
  File "/home/maiqi/yalong/software/anaconda3/envs/pytorch-geometry/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "examples/pointnet++.py", line 50, in forward
    x = F.relu(self.local_sa2(x, (pos, pos[idx]), edge_index))
  File "/home/maiqi/yalong/software/anaconda3/envs/pytorch-geometry/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/maiqi/yalong/project/more-personal/deep-3d/pytorch_geometric/torch_geometric/nn/conv/point_conv.py", line 57, in forward
    return self.propagate(edge_index, x=x, pos=pos)
  File "/home/maiqi/yalong/project/more-personal/deep-3d/pytorch_geometric/torch_geometric/nn/conv/message_passing.py", line 116, in propagate
    out = scatter_(self.aggr, out, edge_index[i], dim_size=size[i])
  File "/home/maiqi/yalong/project/more-personal/deep-3d/pytorch_geometric/torch_geometric/utils/scatter.py", line 33, in scatter_
    out[out == fill_value] = 0
RuntimeError: copy_if failed to synchronize: device-side assert triggered
```
I think it may be a bug from PointConv or MessagePassing caused by recent commits since it's good to run pointnet++ few days ago.

## To Reproduce

It can be reproduced by running [examples/pointnet++.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet%2B%2B.py) example.

## Environment

* OS: ubuntu 16.04
* Python version: 3.6.8
* PyTorch version: 1.0.0
* CUDA/cuDNN version: cuda92, cudnn7.4.1
* GCC version: 5.4.0
* Any other relevant information: Anaconda python environment

**Comment by dragonbook** [comment]
The problem is at [line 55 of point_conv.py](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/point_conv.py#L55). The add_self_loops function:
```
    edge_index = add_self_loops(edge_index, num_nodes=x.size(0))
```
will result in an invalid edge_index for a bipartite graph(when the input 'pos' is a tuple).

When logged like this:
```
        if torch.is_tensor(x):
            log = True
            if log:
                print('--input:')
                print('pos0: {}'.format(pos[0].shape))
                print('pos1: {}'.format(pos[1].shape))

                row, col = edge_index
                print('edge_index: {}'.format(edge_index.shape))
                print('row max: {}, min: {}'.format(row.max(), row.min()))
                print('col max: {}, min: {}'.format(col.max(), col.min()))

            edge_index, _ = remove_self_loops(edge_index)

            if log:
                print('--after remove:')
                row, col = edge_index
                print('edge_index: {}'.format(edge_index.shape))
                print('row max: {}, min: {}'.format(row.max(), row.min()))
                print('col max: {}, min: {}'.format(col.max(), col.min()))

            edge_index = add_self_loops(edge_index, num_nodes=x.size(0))

            if log:
                print('--after add:')
                row, col = edge_index
                print('edge_index: {}'.format(edge_index.shape))
                print('row max: {}, min: {}'.format(row.max(), row.min()))
                print('col max: {}, min: {}'.format(col.max(), col.min()))
```

The log shows that some col index are larger than pos1.shape[0]:
```
--input:
pos0: torch.Size([16384, 3])
pos1: torch.Size([4096, 3])
edge_index: torch.Size([2, 71824])
row max: 16383, min: 0
col max: 4095, min: 0
--after remove:
edge_index: torch.Size([2, 71809])
row max: 16383, min: 0
col max: 4095, min: 0
--after add:
edge_index: torch.Size([2, 88193])
row max: 16383, min: 0
col max: 16383, min: 0
```

And a question is: why need to add self loops to input graph in point_conv?

**Comment by rusty1s** [comment]
Good catch, this is on me. Will fix it ASAP. We add self-loops to the graph to preserve central node information. However, this is not needed for bipartite graphs, but the if call does not capture this appropriately.

**Comment by rusty1s** [comment]
Fixed in master. Thank you very much!
