### ISSUE TITLE
Batched Data usage problem.

### ISSUE THREAD

**Issue by RuihongQiu** [rusty1s/pytorch_geometric#252]
## ❓ Questions & Help

Hello. I came across a strange bug when manipulating the batched Data. I can print the `data` and assign it to a variable. But when I print the attribute of it, it failed. Though some other datas don't have this bug. Could you help me?

    In[3]: data
    Out[3]: Batch(batch=[176], edge_attr=[137], edge_index=[2, 137], in_degree_inv=[137], 
    out_degree_inv=[137], sequence=[282], sequence_len=[100], x=[176, 1], y=[100])
    In[4]: x = data.x
    In[5]: print(x)
    Traceback (most recent call last):
      File "/home/test/pt-1.0/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line
    3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-5-fc17d851ef81>", line 1, in <module>
        print(x)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/tensor.py", line 66, in __repr__
        return torch._tensor_str._str(self)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/_tensor_str.py", line 277, in _str
        tensor_str = _tensor_str(self, indent)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/_tensor_str.py", line 195, in 
    _tensor_str
        formatter = _Formatter(get_summarized_data(self) if summarize else self)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/_tensor_str.py", line 80, in __init__
        value_str = '{}'.format(value)
      File "/home/test/pt-1.0/lib/python3.6/site-packages/torch/tensor.py", line 378, in __format__
        return self.item().__format__(format_spec)
    RuntimeError: CUDA error: device-side assert triggered

**Comment by rusty1s** [comment]
To me this does not look like a PyG bug, but it is hard to say what may be the cause of this error. You can print `data` because it only requests `data.x.size()`. I'm pretty sure that `print(x.size())` does not throw an error either, but accessing the real data does.

**Comment by RuihongQiu** [comment]
Yeah! You are right. `x.size()` is also valid. So it is a data generation bug? Do you have any idea about how to debug? I have tested every single graph when generating the `InMemoryDataset`?

**Comment by rusty1s** [comment]
Is only `x` not printable? Can you run the code with `CUDA_LAUNCH_BLOCKING=1`?

**Comment by RuihongQiu** [comment]
It is my code's bug with index out of range for getting embedding weight. Thank you for your advice!
