### ISSUE TITLE
GraphSAINTSampler incompatibility with Pytorch Lightning multi-GPU (DistributedSampler)

### ISSUE THREAD

**Issue by JeroendenBoef** [rusty1s/pytorch_geometric#2528]
## 🐛 Bug

The GraphSAINTSampler dataloader seems to be incompatible with the multi-GPU functionality of Pytorch Lightning. I have wrapped a GraphSAGE model with a GraphSAINTRandomwalkSampler train dataloader in Pytorch Lightning based upon the GraphSAGE lightning example. Single GPU runs as expected with accuracy results similar to previous runs but using 2 GPUs  yields some confusing errors. I have provided code to reproduce the errors, error messages and things I attempted to fix this below. Thanks for looking into this!

## To Reproduce

1. Run the provided snippet with given settings to trigger MisconfigurationError
2. Add self.save_dir = save_dir to the GraphSAINTRandomwalkSampler class after def __init__ to trigger AssertionError on assert data.edge_index is not None
3. Remove self.data.edge_index = None in GraphSAINTSampler class to trigger TypeError: __init__() got multiple values for keyword argument 'collate_fn' (adding extra arguments to the input of __collate__ dit not fix this for me)

### Code of Pytorch Lightning GraphSAINT:
```
import argparse
import os.path as osp
from typing import Optional, List, NamedTuple

import torch
from torch import Tensor
import torch.nn.functional as F
from torch.nn import ModuleList

from torch_sparse import SparseTensor

import pytorch_lightning as pl
from pytorch_lightning.metrics import Accuracy
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning import LightningDataModule, LightningModule, Trainer

from torch_geometric.data import NeighborSampler, Data#, GraphSAINTRandomWalkSampler
from torch_geometric.datasets import Flickr as PyGFlickr
from torch_geometric.nn import SAGEConv
import torch_geometric.transforms as T
from torch_geometric.utils import degree, subgraph

from samplers import GraphSAINTRandomWalkSampler
parser = argparse.ArgumentParser(description='Flickr Pytorch Lightning GraphSAINT')
parser.add_argument('--batch_size', type=int, default=1000)
parser.add_argument('--walk_length', type=int, default=3)
parser.add_argument('--lr', type=float, default=0.01)
parser.add_argument('--num_steps', type=int, default=5)
parser.add_argument('--epochs', type=int, default=50)
parser.add_argument('--eval_steps', type=int, default=2)
parser.add_argument('--num_workers', type=int, default=2)
args = parser.parse_args()
print(args)

class Batch(NamedTuple):
    x: Tensor
    y: Tensor
    adjs_t: List[SparseTensor]

class Flickr(LightningDataModule):
    def __init__(self, data_dir: str, batch_size: int,
                 in_memory: bool = False):
        super().__init__()
        self.data_dir = data_dir
        self.batch_size = batch_size
        self.transform = T.ToSparseTensor(remove_edge_index=False) #have both sparse tensor and edge index for neighborsampler and graphsaint

    @property
    def num_features(self) -> int:
        return 500

    @property
    def num_classes(self) -> int:
        return 7

    def prepare_data(self):
        PyGFlickr(self.data_dir, pre_transform=self.transform)

    def setup(self, stage: Optional[str] = None):
        self.data = PyGFlickr(self.data_dir)[0]
        row, col = self.data.edge_index
        self.data.edge_weight = 1. / degree(col, self.data.num_nodes)[col]  # Norm by in-degree.
        train_index, train_weight = subgraph(self.data.train_mask, self.data.edge_index, self.data.edge_weight, relabel_nodes=True) #sample subgraph for graphsaint loader, relabel nodes
        self.train_data = Data(edge_index=train_index, edge_weight=train_weight, x=self.data.x[self.data.train_mask], y=self.data.y[self.data.train_mask])
        

    def train_dataloader(self):
        return GraphSAINTRandomWalkSampler(self.train_data, batch_size=self.batch_size, walk_length=args.walk_length,
                                    num_steps=args.num_steps, sample_coverage=0,
                                    num_workers=args.num_workers)
                                    #save_dir=osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'Flickr-normalization'))

    def val_dataloader(self):
        return NeighborSampler(self.data.adj_t, node_idx=self.data.val_mask, sizes=[25, 10], 
                                transform=self.convert_batch, batch_size=self.batch_size, 
                                num_workers=args.num_workers, 
                                persistent_workers=True)
    
    def test_dataloader(self):
        return NeighborSampler(self.data.adj_t, node_idx=self.data.test_mask, sizes=[25, 10], 
                                transform=self.convert_batch, batch_size=self.batch_size, 
                                num_workers=args.num_workers, 
                                persistent_workers=True)

    def convert_batch(self, batch_size, n_id, adjs):
        return Batch(
            x=self.data.x[n_id],
            y=self.data.y[n_id[:batch_size]],
            adjs_t=[adj_t for adj_t, _, _ in adjs],
        )

class SaintGCN(LightningModule):
    def __init__(self, in_channels: int, out_channels: int,
                 hidden_channels: int = 256, num_layers: int = 2,
                 dropout: float = 0.5):
        super().__init__()
        self.save_hyperparameters()
        self.dropout = dropout

        self.convs = ModuleList()
        self.convs.append(SAGEConv(in_channels, hidden_channels))
        for _ in range(num_layers - 2):
            self.convs.append(SAGEConv(hidden_channels, hidden_channels))
        self.convs.append(SAGEConv(hidden_channels, out_channels))
        
        self.train_acc = Accuracy()
        self.val_acc = Accuracy()
        self.test_acc = Accuracy()

    def forward(self, x, edge_index, edge_weight=None):
        #training loop on edge index long tensors   
        if type(edge_index) != list: 
            for conv in self.convs[:-1]:
                x = conv(x, edge_index, edge_weight)
                x = F.relu(x)
                x = F.dropout(x, p=self.dropout, training=self.training)
            x = self.convs[-1](x, edge_index, edge_weight)
        
        #inference is on pairs of sparse tensors
        elif isinstance(edge_index[0], SparseTensor):
            for i, adj_t in enumerate(edge_index):
                x = self.convs[i]((x, x[:adj_t.size(0)]), adj_t)
                if i < len(edge_index) - 1:
                    x = x.relu_()

        return x

    def training_step(self, batch, batch_idx: int):
        y_hat = self(batch.x, batch.edge_index)
        train_loss = F.cross_entropy(y_hat, batch.y)
        train_acc = self.train_acc(y_hat.softmax(dim=-1), batch.y)
        self.log('train_acc', train_acc, prog_bar=True, on_step=False,
                 on_epoch=True)
        return train_loss

    def validation_step(self, batch, batch_idx: int):
        x, y, edge_index = batch
        y_hat = self(x, edge_index)
        val_acc = self.val_acc(y_hat.softmax(dim=-1), y)
        self.log('val_acc', val_acc, prog_bar=True, on_step=False,
                 on_epoch=True)
        return val_acc

    def test_step(self, batch, batch_idx: int):
        x, y, edge_index = batch
        y_hat = self(x, edge_index)
        test_acc = self.test_acc(y_hat.softmax(dim=-1), y)
        self.log('test_acc', test_acc, prog_bar=True, on_step=False,
                 on_epoch=True)
        return test_acc

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.001)

def main():
    path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'Flickr')
    datamodule = Flickr(path, batch_size=args.batch_size)
    model = SaintGCN(datamodule.num_features, datamodule.num_classes)
    checkpoint_callback = ModelCheckpoint(monitor='val_acc', save_top_k=1)
    #trainer = Trainer(gpus=[0], max_epochs=10, callbacks=[checkpoint_callback])

    # Uncomment to train on multiple GPUs:
    trainer = Trainer(gpus=2, accelerator='ddp', max_epochs=10,
                      callbacks=[checkpoint_callback])

    trainer.fit(model, datamodule=datamodule)
    trainer.test()


if __name__ == "__main__":
    main()
```

### First error(MisconfigurationError):
```
Traceback (most recent call last):                                                                                                                                                                          
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 170, in <module>
Traceback (most recent call last):
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 170, in <module>
    main()
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 165, in main
    main()
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 165, in main
    trainer.fit(model, datamodule=datamodule)
    trainer.fit(model, datamodule=datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self._results = trainer.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.train_loop.reset_train_val_dataloaders(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 214, in reset_train_dataloader
    self.trainer.reset_train_dataloader(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 214, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 114, in auto_add_sampler
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 114, in auto_add_sampler
    dataloader = self.replace_sampler(dataloader, sampler)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 169, in replace_sampler
    dataloader = self.replace_sampler(dataloader, sampler)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 169, in replace_sampler
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: ("Trying to inject DistributedSampler within GraphSAINTRandomWalkSampler class.This would fail as your DataLoader doesn't expose all its __init__ parameters as attributes. Missing attributes are {'save_dir'}. HINT: If you wrote the GraphSAINTRandomWalkSampler class, add the `__init__` arguments as attributes or ", 'manually add DistributedSampler as GraphSAINTRandomWalkSampler(dataset, ..., sampler=DistributedSampler(dataset, ...)).')
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: ("Trying to inject DistributedSampler within GraphSAINTRandomWalkSampler class.This would fail as your DataLoader doesn't expose all its __init__ parameters as attributes. Missing attributes are {'save_dir'}. HINT: If you wrote the GraphSAINTRandomWalkSampler class, add the `__init__` arguments as attributes or ", 'manually add DistributedSampler as GraphSAINTRandomWalkSampler(dataset, ..., sampler=DistributedSampler(dataset, ...)).')
```
### Second error (AssertionError):
```
Validation sanity check:   0%|                                                                                                                                                        | 0/2 [00:00<?, ?it/s]Data(edge_index=[2, 218140], edge_weight=[218140], x=[44625, 500], y=[44625])
Data(edge_index=[2, 218140], edge_weight=[218140], x=[44625, 500], y=[44625])                                                                                                                               
Data(edge_weight=[218140], x=[44625, 500], y=[44625])
Traceback (most recent call last):
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 171, in <module>
    main()
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 166, in main
    trainer.fit(model, datamodule=datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 214, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 114, in auto_add_sampler
    dataloader = self.replace_sampler(dataloader, sampler)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 181, in replace_sampler
    dataloader = type(dataloader)(**dl_args)
  File "/home/jdenboef/GraphPOPE/samplers.py", line 210, in __init__
    super(GraphSAINTRandomWalkSampler,
  File "/home/jdenboef/GraphPOPE/samplers.py", line 50, in __init__
    assert data.edge_index is not None
AssertionError
Data(edge_weight=[218140], x=[44625, 500], y=[44625])
Traceback (most recent call last):
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 171, in <module>
    main()
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 166, in main
    trainer.fit(model, datamodule=datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 214, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 114, in auto_add_sampler
    dataloader = self.replace_sampler(dataloader, sampler)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 181, in replace_sampler
    dataloader = type(dataloader)(**dl_args)
  File "/home/jdenboef/GraphPOPE/samplers.py", line 210, in __init__
    super(GraphSAINTRandomWalkSampler,
  File "/home/jdenboef/GraphPOPE/samplers.py", line 50, in __init__
    assert data.edge_index is not None
AssertionError
```
### Third error (TypeError):
```
Validation sanity check:  50%|████████████████████████████████████████████████████████████████████████                                                                        | 1/2 [00:06<00:06,  6.20s/it]Data(edge_index=[2, 218140], edge_weight=[218140], x=[44625, 500], y=[44625])
Data(edge_index=[2, 218140], edge_weight=[218140], x=[44625, 500], y=[44625])                                                                                                                               
Data(edge_index=[2, 218140], edge_weight=[218140], x=[44625, 500], y=[44625])
Data(edge_index=[2, 218140], edge_weight=[218140], x=[44625, 500], y=[44625])
Traceback (most recent call last):
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 171, in <module>
    main()
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 166, in main
    trainer.fit(model, datamodule=datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 214, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 114, in auto_add_sampler
    dataloader = self.replace_sampler(dataloader, sampler)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 181, in replace_sampler
    dataloader = type(dataloader)(**dl_args)
  File "/home/jdenboef/GraphPOPE/samplers.py", line 210, in __init__
    super(GraphSAINTRandomWalkSampler,
  File "/home/jdenboef/GraphPOPE/samplers.py", line 72, in __init__
    super(GraphSAINTSampler,
TypeError: __init__() got multiple values for keyword argument 'collate_fn'
Traceback (most recent call last):
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 171, in <module>
    main()
  File "/home/jdenboef/GraphPOPE/lightning_bug_report.py", line 166, in main
    trainer.fit(model, datamodule=datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 214, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 114, in auto_add_sampler
    dataloader = self.replace_sampler(dataloader, sampler)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 181, in replace_sampler
    dataloader = type(dataloader)(**dl_args)
  File "/home/jdenboef/GraphPOPE/samplers.py", line 210, in __init__
    super(GraphSAINTRandomWalkSampler,
  File "/home/jdenboef/GraphPOPE/samplers.py", line 72, in __init__
    super(GraphSAINTSampler,
TypeError: __init__() got multiple values for keyword argument 'collate_fn'
```

## Expected behavior
Compatibility with the DistributedSampler utilised by Pytorch Lightning similar to torch.geometric.data.NeighborSampler

## Environment

* OS: Ubuntu 18.04.5 LTS
* Python version: 3.8.6
* PyTorch version: 1.8.0
* PyTorch Geometric version: 1.7.0
* Pytorch Lightning version: 1.2.10
* CUDA/cuDNN version: 11.1
* GCC version: 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
* GPU: NVIDIA GeForce RTX 2060 SUPER, NVIDIA GeForce RTX 3060

## Additional context

Single GPU runs without any issues for this code. Multi GPU runs fine as well for the GraphSAGE example with 3 torch.geometric.data.NeighborSampler dataloaders on this environment.

**Comment by rusty1s** [comment]
Thanks for reporting. This should be fixed in master :)

**Comment by JeroendenBoef** [comment]
Amazing, thanks for looking into it so swiftly!
