### ISSUE TITLE
Question regarding edge_weight Tensor

### ISSUE THREAD

**Issue by fratajcz** [rusty1s/pytorch_geometric#2557]
Hi!

I really enjoy your framework! However, I am now wondering how to use the edge_weight Tensor of the GCNConv and related classes. Me edge_index tensor is of shape (2, -1):

```
tensor([[   0,    1,    2,  ..., 1568, 1569, 1570],
        [   0,    1,    2,  ..., 1568, 1569, 1570]], device='cuda:0')
torch.Size([2, 2874])
```

and my edge_weight tensor is of shape (-1,):

```
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', dtype=torch.float64)
torch.Size([2874])
```

Here is the error message:

```
  0%|                                                                                                                                                                           | 0/120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_pgcn.py", line 223, in <module>
    outputs = model(data.x, data.edge_index, data.edge_weight, data.batch)
  File "/home/XXXXX/anaconda3/envs/graphai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/XXXXX/Projects/COVID-19/COVID-19/src/patient_graphs/pgcn.py", line 139, in forward
    x = self.graph_message_passing(x, edge_index, edge_weight)
  File "/home/XXXXX/Projects/COVID-19/COVID-19/src/patient_graphs/pgcn.py", line 163, in gcn_message_passing
    x = self.gcnconv[i](x, edge_index, edge_weight)
  File "/home/XXXXX/anaconda3/envs/graphai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/XXXXX/anaconda3/envs/graphai/lib/python3.8/site-packages/torch_geometric/nn/conv/gin_conv.py", line 64, in forward
    out = self.propagate(edge_index, x=x, size=size)
  File "/home/XXXXX/anaconda3/envs/graphai/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 233, in propagate
    coll_dict = self.__collect__(self.__user_args__, edge_index, size,
  File "/home/XXXXX/anaconda3/envs/graphai/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 152, in __collect__
    self.__set_size__(size, 1 - dim, data[1 - dim])
  File "/home/XXXXX/anaconda3/envs/graphai/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 120, in __set_size__
    raise ValueError(
ValueError: Encountered tensor with size 1571 in dimension -2, but expected size 1.0.
```

I don't really see what causes the problem here. I also already tried to unsqueeze dim 0 so the edge_weight tensor is of shape (0,-1), but that didnt work, either.

Can you help me out?

**Comment by rusty1s** [comment]
Your code looks correct to me (except that you may want to utilize `torch.float` instead of `torch.float64 for saving `edge_weight). Can you show me a small example to reproduce?

**Comment by fratajcz** [comment]
Thanks for the response, it turned out that I have accidentally used the GINConv layer, which does not support edge weights. Sorry for the confusion!
