### ISSUE TITLE
Symbol not found error with pytorch 1.8.0 but not with 1.7.0

### ISSUE THREAD

**Issue by mathpluscode** [rusty1s/pytorch_geometric#2589]
## Environment

* OS: Mac OS 11.3.1
* Python version: 3.7
* PyTorch version: 1.8.0
* CUDA/cuDNN version: /
* GCC version: see below
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
* Any other relevant information:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

I used conda to install pytorch with the `environment.yml` as follows

```
name: gnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=20.0.2
  - pytorch==1.8.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - pip:
      - -r requirements.txt
```

Then I followed the readme to install pytorch geometric

```
export CUDA=cpu
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+${CUDA}.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+${CUDA}.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+${CUDA}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+${CUDA}.html
pip install torch-geometric 
```

But then when I `import torch_geometric.data`, I got the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_sparse/_convert_cpu.so, 6): Symbol not found: __ZN2at5emptyEN3c108ArrayRefIxEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE
  Referenced from: /Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_sparse/_convert_cpu.so
  Expected in: /Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch/lib/libtorch_cpu.dylib
 in /Users/mathpluscode/miniconda3/envs/gnn/lib/python3.7/site-packages/torch_sparse/_convert_cpu.so
```

I tried `conda install -y clang_osx-64 clangxx_osx-64 gfortran_osx-64` but it doesn't help.

However, I do not have such issue, if I downgrade torch to 1.7.0.

**Comment by rusty1s** [comment]
Mh, I guess there are some incompatibilities with the macOS version we used to built and your version. Does installing from source via `pip install torch-scatter` work for you?

**Comment by mathpluscode** [comment]
> Mh, I guess there are some incompatibilities with the macOS version we used to built and your version. Does installing from source via `pip install torch-scatter` work for you?

Hi thanks for the quick reply.

I tried pip install, but it does not work? I wonder why the log saying `macosx_10_9_x86_64` while the system is 11.x?

```
pip install --no-cache-dir torch-scatter
Collecting torch-scatter
  Downloading torch_scatter-2.0.6.tar.gz (21 kB)
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... done
  Created wheel for torch-scatter: filename=torch_scatter-2.0.6-cp37-cp37m-macosx_10_9_x86_64.whl size=294173 sha256=2028436c23ab3e8106da431a4209d7d162f1459862b7d9a49809fe2103eca0e4
  Stored in directory: /private/var/folders/hs/7ql8kn593j1dwlxfgy_g62xm0000gn/T/pip-ephem-wheel-cache-lwtlf1hk/wheels/30/6f/0c/dbdc62f111a9f09962331fd1c13b05806d6c2a2340d27fc0dc
Successfully built torch-scatter
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.6
```

**Comment by rusty1s** [comment]
What does not work for you here? Is it the same error? The installation log looks correct to me. Otherwise, you can try to install via `pip install --verbose --no-cache-dir torch-scatter` to receive a more meaningful installation log.

**Comment by mathpluscode** [comment]
> pip install --verbose --no-cache-dir torch-scatter

Hi @rusty1s , yes, the same error as above in this issue. I attached the log below

Then I did `pip install --verbose --no-cache-dir torch-geometric`. Still the same error when `import torch_geometric.data`.

I guess I will use docker and have another try.

[log.txt](https://github.com/rusty1s/pytorch_geometric/files/6507257/log.txt)

**Comment by mathpluscode** [comment]
I managed to make it work with docker in VMs, so I personally will not continue pursuing this bug. Thx for the help and please feel free to close this issue :)
