### ISSUE TITLE
AttributeError: 'int' object has no attribute 'dim'

### ISSUE THREAD

**Issue by bousejin** [rusty1s/pytorch_geometric#26]
Hi, there. Thank you so much for this amazing library. I am trying to run the infomax code. This is the output after running infomax.py:

Train deep graph infomax.
Traceback (most recent call last):
  File "infomax.py", line 91, in <module>
    loss = train_infomax(epoch)
  File "infomax.py", line 83, in train_infomax
    loss = infomax(data.x, data.edge_index)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "infomax.py", line 56, in forward
    positive = self.encoder(x, edge_index, corrupt=False)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "infomax.py", line 28, in forward
    x = self.conv(x, edge_index)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 44, in forward
    out = self.prop(out, edge_index, edge_attr)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_geometric/nn/prop/gcn_prop.py", line 30, in forward
    out = spmm(edge_index, edge_attr, x, num_nodes)
  File "/home/n/Documents/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_sparse/spmm.py", line 17, in spmm
    matrix = matrix if matrix.dim() > 1 else matrix.unsqueeze(-1)
AttributeError: 'int' object has no attribute 'dim'

**Comment by rusty1s** [comment]
Please see https://github.com/rusty1s/pytorch_geometric/issues/24

**Comment by rusty1s** [comment]
Fixed in v0.3.1 on pypi.
