### ISSUE TITLE
Errors of using Shadow k-hop Sampler

### ISSUE THREAD

**Issue by ZhuYun97** [rusty1s/pytorch_geometric#2603]
## To Reproduce

``` python
from torch_geometric.data import ShaDowKHopSampler
from torch_geometric.datasets import Planetoid

if __name__ == "__main__":
    dataset = Planetoid(root="./data/Planetoid/Cora", name="Cora")
    
    loader = ShaDowKHopSampler(dataset[0], depth=2, num_neighbors=20, batch_size=512)
    print(loader)
    for idx, g in enumerate(loader):
        print(idx, g)

```
When I run the codes above, some errors happen. It seems that `torch_sparse` is lack of `ego_k_hop_sample_adj`, but I use the latest modules. 
```
<torch_geometric.data.shadow.ShaDowKHopSampler object at 0x7f6d75f8b700>
Traceback (most recent call last):
  File "/home/zhuyun/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhuyun/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhuyun/GraphSSL_EMD/data/buffer.py", line 183, in <module>
    for idx, g in enumerate(loader):
  File "/home/zhuyun/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/zhuyun/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhuyun/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/zhuyun/anaconda3/lib/python3.8/site-packages/torch_geometric/data/shadow.py", line 64, in __collate__
    out = torch.ops.torch_sparse.ego_k_hop_sample_adj(
  File "/home/zhuyun/anaconda3/lib/python3.8/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torch_sparse::ego_k_hop_sample_adj
```

## Environment

* OS: Linux
* Python version: 3.8.3
* PyTorch version: 1.7.0
* CUDA/cuDNN version: 11.0
* GCC version: 7.5.0
* Any other relevant information:
  - torch-geometric: 1.7.0 (all the related packages are lastest, like torch-scatter, torch-sparse, ... )
## Additional context
I wish to have your help. Thanks a lot.

**Comment by ZhuYun97** [comment]
I have already installed `torch-sparse`, but the problem also exists.

```
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
Requirement already satisfied: torch-scatter in /home/XX/anaconda3/lib/python3.8/site-packages (2.0.6)
Requirement already satisfied: torch-sparse in /home/XX/anaconda3/lib/python3.8/site-packages (0.6.9)
Requirement already satisfied: scipy in /home/XX/anaconda3/lib/python3.8/site-packages (from torch-sparse) (1.6.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /home/XX/anaconda3/lib/python3.8/site-packages (from scipy->torch-sparse) (1.20.3)
```

The result:
```
RuntimeError: No such operator torch_sparse::ego_k_hop_sample_adj
```

**Comment by rusty1s** [comment]
Yeah, the wheels from `https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html` do not include such functionality yet. You need to clone the `torch_sparse` repository and run:
```
python setup.py install
```
from there in order to be able to access `ego_k_hop_sample_adj`.

**Comment by ZhuYun97** [comment]
I clone the `torch_sparse` repo, and run `python setup.py install` to compile and install it. The installed path is the same as the python environment that I use. But I can not use the function `ego_k_hop_sample_adj`.

Installment:
```
...
...
torch_sparse.__pycache__._version_cpu.cpython-38: module references __file__
torch_sparse.__pycache__._version_cuda.cpython-38: module references __file__
creating dist
creating 'dist/torch_sparse-0.6.9-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_sparse-0.6.9-py3.8-linux-x86_64.egg
creating /home/zhuyun/anaconda3/lib/python3.8/site-packages/torch_sparse-0.6.9-py3.8-linux-x86_64.egg
Extracting torch_sparse-0.6.9-py3.8-linux-x86_64.egg to /home/zhuyun/anaconda3/lib/python3.8/site-packages
Adding torch-sparse 0.6.9 to easy-install.pth file

Installed /home/zhuyun/anaconda3/lib/python3.8/site-packages/torch_sparse-0.6.9-py3.8-linux-x86_64.egg
Processing dependencies for torch-sparse==0.6.9
Searching for scipy==1.6.3
Best match: scipy 1.6.3
Adding scipy 1.6.3 to easy-install.pth file

Using /home/zhuyun/anaconda3/lib/python3.8/site-packages
Searching for numpy==1.20.3
Best match: numpy 1.20.3
Adding numpy 1.20.3 to easy-install.pth file
Installing f2py script to /home/zhuyun/anaconda3/bin
Installing f2py3 script to /home/zhuyun/anaconda3/bin
Installing f2py3.8 script to /home/zhuyun/anaconda3/bin

Using /home/zhuyun/anaconda3/lib/python3.8/site-packages
Finished processing dependencies for torch-sparse==0.6.9
```

Errors:
```
<torch_geometric.data.shadow.ShaDowKHopSampler object at 0x7f8c7cc427c0>
Traceback (most recent call last):
  File "/home/XX/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/XX/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/XX/GraphSSL_EMD/data/buffer.py", line 183, in <module>
    for idx, g in enumerate(loader):
  File "/home/XX/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/XX/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/XX/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/XX/anaconda3/lib/python3.8/site-packages/torch_geometric/data/shadow.py", line 64, in __collate__
    out = torch.ops.torch_sparse.ego_k_hop_sample_adj(
  File "/home/XX/anaconda3/lib/python3.8/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torch_sparse::ego_k_hop_sample_adj
```

**Comment by rusty1s** [comment]
Did you make sure to uninstall all previous installations of `torch-sparse`?

**Comment by ZhuYun97** [comment]
Thanks a lot, after uninstalling the previous installations of `torch-sparse`, it can run successfully.
