### ISSUE TITLE
Error of Actor dataset

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#2616]
When pre-precessing Actor dataset, the error is reported:
```
Processing...
Traceback (most recent call last):
  File "actor.py", line 4, in <module>
    Actor(path, transform=True, pre_transform=True)
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/datasets/actor.py", line 33, in __init__
    super(Actor, self).__init__(root, transform, pre_transform)
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 55, in __init__
    pre_filter)
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/datasets/actor.py", line 76, in process
    tmp = np.load(f)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 457, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

**Comment by rusty1s** [comment]
Which `numpy` version are you using?

**Comment by jiaruHithub** [comment]
```numpy=1.18.5```

**Comment by rusty1s** [comment]
I see. Thanks. Can you please whether you can load the raw data `numpy` files `*.npz` files via `np.load(path, allow_pickle=True)`?

**Comment by jiaruHithub** [comment]
> I see. Thanks. Can you please check whether you can load the raw data `` numpy``*.npz `` files via `np.load(path, allow_pickle=Tr

> I see. Thanks. Can you please check whether you can load the raw data `` numpy``*.npz `` files via `np.load(path, allow_pickle=True)`?

In ```numpy=1.18.1```, I successfully load the raw data.
But when I use it train on GCN(In ```), the error has reported:
```
Traceback (most recent call last):
  File "gcn.py", line 48, in <module>
    args.early_stopping, permute_masks)
  File "/home/pytorch_geometric-master/pytorch_geometric-master/benchmark/citation1/train_eval.py", line 66, in run
    train(model, optimizer, data)
  File "/home/pytorch_geometric-master/pytorch_geometric-master/benchmark/citation1/train_eval.py", line 105, in train
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
IndexError: The shape of the mask [7600, 10] at index 1 does not match the shape of the indexed tensor [7600, 5] at index 1
```
Would you kindly help me?

**Comment by rusty1s** [comment]
This dataset comes with multiple `masks` against which you can individually train on (in this case `10`). As a result `train_mask` is of shape `[num_nodes, num_masks]`. You therefore need to select the respective mask for each training run, e.g., `F.nll_loss(out[data.train_mask[:, 0]], data.y[data.train_mask[:, 0]])`.

**Comment by jiaruHithub** [comment]
> This dataset comes with multiple `masks` against which you can individually train on (in this case `10`). As a result `train_mask` is of shape `[num_nodes, num_masks]`. You therefore need to select the respective mask for each training run, e.g., `F.nll_loss(out[data.train_mask[:, 0]], data.y[data.train_mask[:, 0]])`.

Thanks a lot! It has been fixed!
