### ISSUE TITLE
benchmark/points/point_cnn.py fails with dim mismatch error

### ISSUE THREAD

**Issue by contactrika** [rusty1s/pytorch_geometric#2904]
## 🐛 Bug

benchmark/points/point_cnn.py example fails with dimension mismatch error

## To Reproduce

1. git clone https://github.com/rusty1s/pytorch_geometric.git
2. cd pytorch_geometric/benchmark
3. pip install -e .
4. cd points
4. Run: `python point_cnn.py`

Output:
```
Downloading http://vision.princeton.edu/projects/2014/3DShapeNets/ModelNet10.zip
Extracting ~/code/pytorch_geometric/benchmark/data/ModelNet10/ModelNet10.zip
Processing...
Done!
Traceback (most recent call last):
  File "point_cnn.py", line 61, in <module>
    run(train_dataset, test_dataset, model, args.epochs, args.batch_size, args.lr,
  File "~/code/pytorch_geometric/benchmark/points/train_eval.py", line 26, in run
    train(model, optimizer, train_loader, device)
  File "~/code/pytorch_geometric/benchmark/points/train_eval.py", line 48, in train
    out = model(data.pos, data.batch)
  File "~/miniconda3/envs/rkhs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "point_cnn.py", line 42, in forward
    x = F.relu(self.conv2(x, pos, batch))
  File "~/miniconda3/envs/rkhs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/miniconda3/envs/rkhs/lib/python3.8/site-packages/torch_geometric/nn/conv/x_conv.py", line 139, in forward
    x = x[col].view(N, K, self.in_channels)
RuntimeError: shape '[12288, 12, 48]' is invalid for input of size 1179648
```

## Environment

* OS: Ubuntu 20.04, also OS X 11.5
* Python version: 3.8
* PyTorch version: 1.9
* CUDA/cuDNN version: 11.1 also cpu
* GCC version:  N/A (not compiling from source)
* torch-geometric==1.7.2 torch-cluster==1.5.9 torch-scatter==2.0.7 torch-sparse==0.6.10

I am not closely familiar with PointCNN paper, so was just trying to run the code in torch_geometric with the existing examples to get started (so I  run the above example without any modifications). Would be great is somebody could take a look as to why this error comes up. Thank you!

**Comment by rusty1s** [comment]
Do you have multiple versions of PyG installed? It seems like you are not actually running PyG from master with the fixed code. I suggest to run
```
pip uninstall torch-geometric
```
multiple times, and install from source again afterwards.

**Comment by DeadlyAbyss** [comment]
I met the same error! I'm afraid they haven't fixed the bug yet.
