### ISSUE TITLE
How to add model graph to TensorBoard?

### ISSUE THREAD

**Issue by acivgin1** [rusty1s/pytorch_geometric#299]
## ❓ Questions & Help

Hi,

I'm trying to trace the model graph for TensorBoard, and I'm wondering if this is supported by this library?

e.g., using the pointnet++.py network (I call the `torch.onnx.export` since both tensorboardx and `torch.utils.tensorboard` use onnx for tracing the graph).

```python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for data in train_loader:
    break
torch.onnx.export(model, (data.pos.to(device), data.batch.to(device)), "pointnet_v2.onnx", verbose=True)

```
I get this Error (full stack trace below):
```
File "~/miniconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 183, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples (VisitNode at /opt/conda/conda-bld/pytorch_1556653114079/work/torch/csrc/jit/passes/lower_tuples.cpp:117)
```

This being the [line](https://github.com/pytorch/pytorch/blob/3afd99680ce23844d7ecccb9c72ea73f159f4d59/torch/csrc/jit/passes/lower_tuples.cpp#L95) that raises the error, and [this](https://github.com/pytorch/pytorch/blob/3afd99680ce23844d7ecccb9c72ea73f159f4d59/torch/csrc/jit/passes/lower_tuples.cpp#L141) is the C++ function that is binded to `torch._C._jit_pass_lower_all_tuples`

Thank you in advance,
Amar

```
~/miniconda3/envs/test/lib/python3.7/site-packages/torch/tensor.py:435: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect.
Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
Traceback (most recent call last):
  File "~/Code/test/test.py", line 71, in <module>
    torch.onnx.export(model, (data.pos.to(device), data.batch.to(device)), "pointnetv2.onnx", verbose=True)
  File "~/miniconda3/envs/test/lib/python3.7/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "~/miniconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "~/miniconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "~/miniconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "~/miniconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 183, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples (VisitNode at /opt/conda/conda-bld/pytorch_1556653114079/work/torch/csrc/jit/passes/lower_tuples.cpp:117)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fcf37576dc5 in ~/miniconda3/envs/test/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xadf7d0 (0x7fcedcef37d0 in ~/miniconda3/envs/test/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #2: <unknown function> + 0xadfa34 (0x7fcedcef3a34 in ~/miniconda3/envs/test/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #3: torch::jit::LowerAllTuples(std::shared_ptr<torch::jit::Graph>&) + 0x13 (0x7fcedcef3a73 in ~/miniconda3/envs/test/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x3f62f4 (0x7fcf37b862f4 in ~/miniconda3/envs/test/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x12d07a (0x7fcf378bd07a in ~/miniconda3/envs/test/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: _PyMethodDef_RawFastCallKeywords + 0x264 (0x561ae06d86e4 in ~/miniconda3/envs/test/bin/python)
frame #7: _PyCFunction_FastCallKeywords + 0x21 (0x561ae06d8801 in ~/miniconda3/envs/test/bin/python)
frame #8: _PyEval_EvalFrameDefault + 0x4e8c (0x561ae07342bc in ~/miniconda3/envs/test/bin/python)
frame #9: _PyEval_EvalCodeWithName + 0x2f9 (0x561ae06754f9 in ~/miniconda3/envs/test/bin/python)
frame #10: _PyFunction_FastCallKeywords + 0x387 (0x561ae06d7a27 in ~/miniconda3/envs/test/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x14ce (0x561ae07308fe in ~/miniconda3/envs/test/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x561ae06754f9 in ~/miniconda3/envs/test/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0x325 (0x561ae06d79c5 in ~/miniconda3/envs/test/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x416 (0x561ae072f846 in ~/miniconda3/envs/test/bin/python)
frame #15: _PyEval_EvalCodeWithName + 0xbb9 (0x561ae0675db9 in ~/miniconda3/envs/test/bin/python)
frame #16: _PyFunction_FastCallKeywords + 0x387 (0x561ae06d7a27 in ~/miniconda3/envs/test/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x14ce (0x561ae07308fe in ~/miniconda3/envs/test/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x561ae06754f9 in ~/miniconda3/envs/test/bin/python)
frame #19: _PyFunction_FastCallDict + 0x400 (0x561ae0676800 in ~/miniconda3/envs/test/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x1e20 (0x561ae0731250 in ~/miniconda3/envs/test/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x561ae06754f9 in ~/miniconda3/envs/test/bin/python)
frame #22: _PyFunction_FastCallKeywords + 0x387 (0x561ae06d7a27 in ~/miniconda3/envs/test/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x14ce (0x561ae07308fe in ~/miniconda3/envs/test/bin/python)
frame #24: _PyEval_EvalCodeWithName + 0x2f9 (0x561ae06754f9 in ~/miniconda3/envs/test/bin/python)
frame #25: PyEval_EvalCodeEx + 0x44 (0x561ae06763c4 in ~/miniconda3/envs/test/bin/python)
frame #26: PyEval_EvalCode + 0x1c (0x561ae06763ec in ~/miniconda3/envs/test/bin/python)
frame #27: <unknown function> + 0x22f874 (0x561ae078e874 in ~/miniconda3/envs/test/bin/python)
frame #28: PyRun_FileExFlags + 0xa1 (0x561ae0798b81 in ~/miniconda3/envs/test/bin/python)
frame #29: PyRun_SimpleFileExFlags + 0x1c3 (0x561ae0798d73 in ~/miniconda3/envs/test/bin/python)
frame #30: <unknown function> + 0x23ae5f (0x561ae0799e5f in ~/miniconda3/envs/test/bin/python)
frame #31: _Py_UnixMain + 0x3c (0x561ae0799f7c in ~/miniconda3/envs/test/bin/python)
frame #32: __libc_start_main + 0xe7 (0x7fcf3b479b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #33: <unknown function> + 0x1e0122 (0x561ae073f122 in ~/miniconda3/envs/test/bin/python)
```

**Comment by rusty1s** [comment]
I will look into this.

**Comment by rusty1s** [comment]
Seems like PyG does not support TensorBoard at the moment. I'm getting
```
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got NoneType
```
errors (see *e.g.* [here](https://github.com/pytorch/pytorch/issues/17858)).

**Comment by acivgin1** [comment]
Thank you for your quick response,

This is with calling the `add_graph` method without passing an input to the model?

i used this:
```python
for data in train_loader:
    break
writer.add_graph(model, (data.pos.to(device), data.batch.to(device)))
```
And I also had to modify the example network, so the `forward` method would work with two `Tensors` instead of one `Batch`.

**Comment by cfd1** [comment]
I have managed to get graphs, summaries and hparams into tensorboard, using a similar solution for the graphs to @acivgin1.
Has anyone managed to get meshes into tensorboard? I've been trying with the ModelNet10 dataset and can get tensoboard to recognise that it has been passed a mesh, but it doesn't show them.

I'm using `tf-nightly` to get tensorboard as the documentation says it is required.

**Comment by cfd1** [comment]
It appears to be an issue with firefox. It works fine using chrome

**Comment by w00zie** [comment]
Hi @cfd1 : can you please share the solution you found?

> I have managed to get graphs, summaries and hparams into tensorboard, using a similar solution for the graphs to @acivgin1.

Thanks!
