### ISSUE TITLE
Package Installed But Runtime Error

### ISSUE THREAD

**Issue by zcaicaros** [rusty1s/pytorch_geometric#3011]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

I installed a legacy version of `torch-geometric==1.6.3`.

I installed all the dependencies with `cu110` since my Pytorch is with `CUDA11.4`.

```
>>> import torch
>>> print(torch.__version__)
1.7.1+cu110
```
Here I check if I installed dependencies successfully:
```
(mtsptwr_env) rongkai@rongkai-U2026:~/manager-worker-mtsptwr/manager$ pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Requirement already satisfied: torch-scatter in /home/rongkai/mtsptwr_env/lib/python3.7/site-packages (2.0.8)
(mtsptwr_env) rongkai@rongkai-U2026:~/manager-worker-mtsptwr/manager$ pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Requirement already satisfied: torch-sparse in /home/rongkai/mtsptwr_env/lib/python3.7/site-packages (0.6.11)
Requirement already satisfied: scipy in /home/rongkai/mtsptwr_env/lib/python3.7/site-packages (from torch-sparse) (1.7.1)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /home/rongkai/mtsptwr_env/lib/python3.7/site-packages (from scipy->torch-sparse) (1.20.3)
(mtsptwr_env) rongkai@rongkai-U2026:~/manager-worker-mtsptwr/manager$ pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Requirement already satisfied: torch-cluster in /home/rongkai/mtsptwr_env/lib/python3.7/site-packages (1.5.9)
(mtsptwr_env) rongkai@rongkai-U2026:~/manager-worker-mtsptwr/manager$ pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
Requirement already satisfied: torch-spline-conv in /home/rongkai/mtsptwr_env/lib/python3.7/site-packages (1.2.1)
(mtsptwr_env) rongkai@rongkai-U2026:~/manager-worker-mtsptwr/manager$
```

There seem no problems. Then I install  `torch-geometric==1.6.3` by running the command: `pip install torch-geometric==1.6.3`. Still no issues. But when I run the program, I got the error:
```
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from torch_geometric.data import Data
  File "/home/rongkai/mtsptwr_env/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/rongkai/mtsptwr_env/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/rongkai/mtsptwr_env/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/rongkai/mtsptwr_env/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/rongkai/mtsptwr_env/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/rongkai/mtsptwr_env/lib/python3.7/site-packages/torch_sparse/__init__.py", line 30, in <module>
    f'Detected that PyTorch and torch_sparse were compiled with '
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 11.0 and torch_sparse has CUDA version 10.0. Please reinstall the torch_sparse that matches your PyTorch install.
(mtsptwr_env) rongkai@rongkai-U2026:~/manager-worker-mtsptwr/manager$
```

Any suggestions?

**Comment by zcaicaros** [comment]
This issue is solved by creating a `docker` container with `cuda 10.1`.

**Comment by rusty1s** [comment]
Glad to see that it's now working for you :)
