### ISSUE TITLE
AWS Sagemaker Training Install

### ISSUE THREAD

**Issue by karldd** [rusty1s/pytorch_geometric#3106]
## 📚 Installation

I'm trying to setup a `requirements.txt` file to be used with AWS Sagemaker. This all happens inside of their docker containers, specifically [this one](https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/1.8/py3/cu111/Dockerfile.gpu). So pytorch, cuda etc are all setup already.

I've configured the `requirements.txt` to force using the provided wheels:
```
-f https://data.pyg.org/whl/torch-1.8.1+cu111.html
--no-index
torch-scatter
torch-sparse
--index-url https://pypi.org/simple
torch-geometric
```

And this works as expected:
```
2021-09-08T13:52:20.381-07:00	/opt/conda/bin/python3.6 -m pip install -r requirements.txt
2021-09-08T13:52:21.381-07:00	Looking in links: https://data.pyg.org/whl/torch-1.8.1+cu111.html
2021-09-08T13:52:21.381-07:00	Collecting torch-scatter Downloading https://data.pyg.org/whl/torch-1.8.0%2Bcu111/torch_scatter-2.0.8-cp36-cp36m-linux_x86_64.whl (10.5 MB)
2021-09-08T13:52:21.381-07:00	Collecting torch-sparse
2021-09-08T13:52:22.382-07:00	Downloading https://data.pyg.org/whl/torch-1.8.0%2Bcu111/torch_sparse-0.6.12-cp36-cp36m-linux_x86_64.whl (3.9 MB)
2021-09-08T13:52:22.382-07:00	Collecting torch-geometric Downloading torch_geometric-1.7.2.tar.gz (222 kB)
```

However, I get the following error when importing PyG:
```
Traceback (most recent call last):
  File "train_graph.py", line 23, in <module>
    from torch_geometric.nn import GATv2Conv, GATConv
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/opt/conda/lib/python3.6/site-packages/torch_sparse/__init__.py", line 16, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/opt/conda/lib/python3.6/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
Traceback (most recent call last): File "train_graph.py", line 23, in <module> from torch_geometric.nn import GATv2Conv, GATConv File "/opt/conda/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module> import torch_geometric.data File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module> from .data import Data File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module> from torch_sparse import coalesce, SparseTensor File "/opt/conda/lib/python3.6/site-packages/torch_sparse/__init__.py", line 16, in <module> f'{library}_{suffix}', [osp.dirname(__file__)]).origin) File "/opt/conda/lib/python3.6/site-packages/torch/_ops.py", line 104, in load_library ctypes.CDLL(path) File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__ self._handle = _dlopen(self._name, mode)
```

And also:
```
OSError: /opt/conda/lib/python3.6/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

I noticed that if I don't force using the provided wheels, the wheels get build and run without issue. Its just very slow and something I would like to speed up if possible.
```
2021-09-08T13:27:41.702-07:00	Building wheels for collected packages: torch-scatter, torch-sparse, torch-geometric, wrapt, configobj, python-louvain, pycollada Building wheel for torch-scatter (setup.py): started
2021-09-08T13:28:45.719-07:00	Building wheel for torch-scatter (setup.py): still running...
2021-09-08T13:30:49.751-07:00	Building wheel for torch-scatter (setup.py): still running...
2021-09-08T13:31:56.769-07:00	Building wheel for torch-scatter (setup.py): still running...
2021-09-08T13:33:25.792-07:00	Building wheel for torch-scatter (setup.py): still running...
2021-09-08T13:34:25.808-07:00	Building wheel for torch-scatter (setup.py): still running...
2021-09-08T13:35:59.832-07:00	Building wheel for torch-scatter (setup.py): still running...
2021-09-08T13:36:20.838-07:00	Building wheel for torch-scatter (setup.py): finished with status 'done' Created wheel for torch-scatter: filename=torch_scatter-2.0.8-cp36-cp36m-linux_x86_64.whl size=3259643 sha256=70b1cafb2168a6e6bd303e0c2a780861797376bf2baa83880640b03ad5e67fc6 Stored in directory: /root/.cache/pip/wheels/1a/f8/0d/55b85126dafd101a8d2fcee9250d08c8f73fb3f2c8a318f848 Building wheel for torch-sparse (setup.py): started
2021-09-08T13:37:23.854-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:39:46.891-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:40:47.907-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:43:09.944-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:44:10.960-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:46:32.999-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:47:36.015-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:48:48.034-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:52:21.090-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:53:22.105-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:54:23.121-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:55:24.137-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:56:27.154-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:58:20.183-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T13:59:26.200-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T14:00:26.216-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T14:01:30.232-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T14:02:31.247-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T14:03:35.264-07:00	Building wheel for torch-sparse (setup.py): still running...
2021-09-08T14:04:20.275-07:00	Building wheel for torch-sparse (setup.py): finished with status 'done' Created wheel for torch-sparse: filename=torch_sparse-0.6.12-cp36-cp36m-linux_x86_64.whl size=2742194 sha256=f4e3b8c7497a6dc08455741bdc3649c5c9e2b0b424d86d55d104c554292a8437 Stored in directory: /root/.cache/pip/wheels/d5/83/f3/83de23cd7ee8d2ed4ae35154c051007a66c5a0c5df84bf425d Building wheel for torch-geometric (setup.py): started Building wheel for torch-geometric (setup.py): finished with status 'done' Created wheel for torch-geometric: filename=torch_geometric-1.7.2-py3-none-any.whl size=388129 sha256=1b8565ebe126ac10f89164e3b5868f16bf8dd774532dad61cf7622fb10732766 Stored in directory: /root/.cache/pip/wheels/ee/06/5d/34ba326d1f011a204f44a0c6d19d7819a02a73785d452973c6 Building wheel for wrapt (setup.py): started

```

Any ideas on how best to proceed? Thanks!

## Environment

* OS: Linux
* Python version: 3.6
* PyTorch version: 1.8.1
* CUDA/cuDNN version: 11.1
* GCC version: 
* How did you try to install PyTorch Geometric and its extensions (wheel, source): See above
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Thanks for reporting. If I'm not mistaken, it looks like AWS provides their own compiled binaries for PyTorch, which might cause this trouble as we are building based on the binaries provided from PyTorch directly. What happens if you change [these lines](https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/1.8/py3/cu111/Dockerfile.gpu#L45-L49) by loading [official PyTorch wheels](https://download.pytorch.org/whl/torch/).

**Comment by karldd** [comment]
Ah yes that could be the case. Right now I am not building the docker container (just running my code in it), so that would definitely be something to try. It's only a minor annoyance right now so I will just keep building the wheels for now.

For the record a `requirements.txt` file as follows is what I'm using (slow but works):
```
torch-scatter
torch-sparse
torch-geometric
```
