### ISSUE TITLE
RecursionError on LastFM dataset

### ISSUE THREAD

**Issue by tetsu9923** [rusty1s/pytorch_geometric#3110]
Hello, thank you for your awesome graph learning library!
I am trying to implement [LightGCN](https://arxiv.org/abs/2002.02126) and use [LastFM dataset](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.LastFM) as its input.
However, I cannot check the contents of this dataset due to the following error.

```
from torch_geometric.datasets.last_fm import LastFM

dataset = LastFM(root="data")
print(dataset[0])
```
```
Traceback (most recent call last):
  File "/home/tetsu9923/LightGCN/lastfm_bug.py", line 4, in <module>
    print(dataset[0])
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 198, in __getitem__
    data = self.get(self.indices()[idx])
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 84, in get
    return copy.copy(self.data)
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/copy.py", line 84, in copy
    return copier(x)
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/torch_geometric/data/data.py", line 360, in __copy__
    out.__dict__['_store'] = copy.copy(self._store)
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/torch_geometric/data/data.py", line 339, in __getattr__
    return getattr(self._store, key)
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/torch_geometric/data/data.py", line 339, in __getattr__
    return getattr(self._store, key)
  File "/home/tetsu9923/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/torch_geometric/data/data.py", line 339, in __getattr__
    return getattr(self._store, key)
  [Previous line repeated 992 more times]
RecursionError: maximum recursion depth exceeded
```

How can I deal with this error?
I installed PyG from master via `pip install git+https://github.com/rusty1s/pytorch_geometric.git`.
Thank you.

**Comment by rusty1s** [comment]
This usually happens if there is already a dataset given at path `data`. Either deleting the `data/processed` folder or running
```python
from torch_geometric.datasets.last_fm import LastFM

dataset = LastFM(root="data/LastFM")
print(dataset[0])
```
should fix this error.

**Comment by tetsu9923** [comment]
Thank you for your quick reply.
`deleting the data/processed folder` fixed this error.
Thank you so much!
