### ISSUE TITLE
undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs on Ubuntu

### ISSUE THREAD

**Issue by james2js** [rusty1s/pytorch_geometric#33]
Everything seems to be installed, no errors... I am using Ubuntu with anaconda  python 3.7 and gcc 7.3.0
I tried to reinstall with different versions of cuda/pytorch but I am getting the same error when importing torch_scatter:

>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yemz/anaconda3/envs/geo/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/yemz/anaconda3/envs/geo/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/yemz/anaconda3/envs/geo/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import scatter_cpu
ImportError: /home/yemz/anaconda3/envs/geo/lib/python3.7/site-packages/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

Can you give me a hand? 
Thanks!

**Comment by james2js** [comment]
I did a fresh reinstall on a clean OS and everything seems to be working fine now, thanks!

**Comment by sharifza** [comment]
I face the same issue. Not sure if doing a fresh OS install is really a solution, I will install pytorch again and test. Any idea what causes this?

**Comment by sharifza** [comment]
Re-installing pytorch and torchvision fixed it.
