### ISSUE TITLE
Error using edges weight with GCN in version 1.2.1 

### ISSUE THREAD

**Issue by Gloufy37** [rusty1s/pytorch_geometric#335]
Hi,

Thank you for this awesome lib, that saved me a lot of time in my work.
Currently, I'm working on a modified GAE with a custom dataset with edge weight.
Everything works greats on version 1.2.0 but doesn't work anymore on version 1.2.1.

Here the error message I got:

```
Traceback (most recent call last):
  File "./train.py", line 16, in <module>
    utils.train(model, dataset_train, dataset_test, device, save_name="GAE", logs_name="GAE/train_"+str(int(time.time())), epochs=3)
  File "/root/dl_bgp/scripts/tools/utils/utils.py", line 172, in train
    test(model, dataset_test, device, logs_name=logs_name+"/test", logs_step=epoch)
  File "/root/dl_bgp/scripts/tools/utils/utils.py", line 45, in test
    z = model.encode(data.x, data.edge_index, data.edge_attr).to(device)
  File "/root/anaconda/lib/python3.7/site-packages/torch_geometric/nn/models/autoencoder.py", line 95, in encode
    return self.encoder(*args, **kwargs)
  File "/root/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/dl_bgp/scripts/tools/models/encoders/gcn_encoder.py", line 28, in forward
    x =  sigmoid(self.gcns[i](x, edge_index, edge_weight))
  File "/root/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 89, in forward
    self.improved, x.dtype)
  File "/root/anaconda/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 74, in norm
    edge_index, edge_weight, fill_value, num_nodes)
  File "/root/anaconda/lib/python3.7/site-packages/torch_geometric/utils/loop.py", line 111, in add_remaining_self_loops
    edge_weight = torch.cat([edge_weight[mask], loop_weight], dim=0)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/generic/THCTensorMath.cu:62
```

Sorry for the fast writing and if this issue has already been reported.

**Comment by rusty1s** [comment]
I will look into it.

**Comment by rusty1s** [comment]
Hi, I tested the `GCNConv` for all kinds of `edge_weights` and it works fine for me. Do you call `add_self_loops` in your script? The API [slightly changed](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/loop.py#L39) in 1.2.1 and additionally returns `edge_weights` now. Can you verify that your edge weights and edge indices have the same number of edges?

**Comment by Gloufy37** [comment]
Hi, thank you for your answer!
When I tried `add_self_loops`, I faced the same error. And finally, I noticed that my `edge_weights` was an `N x 1` tensor instead of the expected `N` dimension tensor. So, my mistake!
