### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by emanhamed** [rusty1s/pytorch_geometric#34]
I tried to test splinecnn on my data but I'm receiving some errors: 
```
Traceback (most recent call last):
  File "test_coress.py", line 115, in <module>
    data = transforms.FaceToEdge()(data)
  File "build/bdist.linux-x86_64/egg/torch_geometric/transforms/face_to_edge.py", line 10, in __call__
  File "build/bdist.linux-x86_64/egg/torch_geometric/utils/undirected.py", line 17, in to_undirected
  File "build/bdist.linux-x86_64/egg/torch_geometric/utils/coalesce.py", line 21, in coalesce
ValueError: too many values to unpack

```
Here is my code, where I was reading the data and processing them: 
```
	vertices, faces, normals, nothin  = read_mesh(data_path+dirs[data_size])
	vertices = vertices.astype(np.float)
	faces = faces.astype(np.int32)
	vertices = torch.tensor(vertices, dtype=torch.float)
	faces = torch.tensor(faces.T, dtype=torch.long)
	data = Data(pos=vertices)
	data.face = faces
	**data = transforms.FaceToEdge()(data)  #This is the line that is causing the error** 
	data.face = None
	data.x = torch.ones((data.num_nodes, 1))
	data = transforms.Cartesian()(data)
	test_loader = DataLoader(data, batch_size=1)
```

can you please help with this issue ?

**Comment by rusty1s** [comment]
Hi,
This seems to be a version conflict between torch-geometric and torch-sparse. Please try to upgrade torch-geometric to current master.
