### ISSUE TITLE
Run example cora get stuck

### ISSUE THREAD

**Issue by freesinger** [rusty1s/pytorch_geometric#347]
Hello rusty!
When I run `cora.py` in the example folder, it gets stuck for about 8 minutes and then gives me the first epoch data. Is that normal?
After the keyboard interrupt, it shows the message as follows:
```
Traceback (most recent call last):
  File "CoraGeom.py", line 62, in <module>
    print(log.format(epoch, *test()))
  File "CoraGeom.py", line 51, in test
    logits, accs = model(), []
  File "/Users/shanewang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "CoraGeom.py", line 30, in forward
    x = F.elu(self.conv1(x, edge_index, edge_attr))
  File "/Users/shanewang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/shanewang/anaconda3/lib/python3.6/site-packages/torch_geometric-1.0.3-py3.6.egg/torch_geometric/nn/conv/spline_conv.py", line 112, in forward
  File "/Users/shanewang/anaconda3/lib/python3.6/site-packages/torch_spline_conv/conv.py", line 62, in apply
    out = SplineWeighting.apply(x[col], weight, *data)
  File "/Users/shanewang/anaconda3/lib/python3.6/site-packages/torch_spline_conv/weighting.py", line 21, in forward
    out = op(x, weight, basis, weight_index)
```
Does it seem something wrong about splineconv used?

**Comment by rusty1s** [comment]
Do you use the CPU version of `SplineConv`? This one is not really optimized and is actually so slow [that we needed to add a warning to prevent users from using it](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/spline_conv.py#L103-L105). You should run `SplineConv` only in the GPU, sorry!

**Comment by freesinger** [comment]
That makes sense.
I run the code on my Mac, so there's no GPU available. I might just use GCN will be enough for cora classification task.
Thanks a lot!
