### ISSUE TITLE
testing pytorch_geometric fails! 

### ISSUE THREAD

**Issue by emanhamed** [rusty1s/pytorch_geometric#4]
I have followed the instructions for installing pytorch_geometric. However, I'm receiving some errors while testing. I have searched a lot but I didn't find solutions. It seems that it is something related to the code. Here is what I'm getting. 
```
`root@Linux-HUETOS:~/pytorch_geometric-master# nosetests
.......E..E..E..EEEE.................
======================================================================
ERROR: test_coalesce_gpu (torch_geometric.nn.functional.pool.coalesce_test.CoalesceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/coalesce_test.py", line 60, in test_coalesce_gpu
    index = coalesce(index)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/coalesce.py", line 15, in coalesce
    _, perm = unique_by_key(e, perm)
  File "/usr/local/lib/python2.7/dist-packages/torch_unique/functions/unique_by_key.py", line 30, in unique_by_key
    func = getattr(ffi, 'uniqueByKey_cuda_{}'.format(typename))
AttributeError: 'module' object has no attribute 'uniqueByKey_cuda_Long'

======================================================================
ERROR: test_auto_backward (torch_geometric.nn.functional.pool.pool_test.PoolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool_test.py", line 86, in test_auto_backward
    test = gradcheck(op, (input, ), eps=1e-6, atol=1e-4)
  File "/home/eman/.local/lib/python2.7/site-packages/torch/autograd/gradcheck.py", line 162, in gradcheck
    output = _differentiable_outputs(func(*inputs))
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool_test.py", line 13, in max_pool_backward
    return _max_pool(input, cluster)
TypeError: _max_pool() takes exactly 3 arguments (2 given)

======================================================================
ERROR: test_avg_forward_gpu (torch_geometric.nn.functional.pool.pool_test.PoolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool_test.py", line 117, in test_avg_forward_gpu
    output, index, position = avg_pool(input, index, position, cluster)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool.py", line 77, in avg_pool
    x = _avg_pool(input, cluster, size, weight_values)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool.py", line 62, in _avg_pool
    x = scatter_mean(cluster, input, dim=0, fill_value=fill)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/mean.py", line 124, in scatter_mean
    return scatter_mean_(output, index, input, dim)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/mean.py", line 74, in scatter_mean_
    scatter(ScatterMean, 'mean', dim, init, index, input, count)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/scatter.py", line 46, in scatter
    return ffi_scatter(name, dim, *data)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/ffi.py", line 31, in scatter
    func = getattr(ffi, 'scatter_{}_{}{}'.format(name, cuda, typename))
AttributeError: 'module' object has no attribute 'scatter_mean_cuda_Float'

======================================================================
ERROR: test_max_forward_gpu (torch_geometric.nn.functional.pool.pool_test.PoolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool_test.py", line 100, in test_max_forward_gpu
    output, index, position = max_pool(input, index, position, cluster)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool.py", line 45, in max_pool
    x = _max_pool(input, cluster, size)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/pool.py", line 37, in _max_pool
    x = scatter_max(cluster, input, dim=0, fill_value=fill)[0]
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/max.py", line 129, in scatter_max
    return scatter_max_(output, index, input, dim)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/max.py", line 78, in scatter_max_
    return scatter(ScatterMax, 'max', dim, output, index, input, arg)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/scatter.py", line 46, in scatter
    return ffi_scatter(name, dim, *data)
  File "/usr/local/lib/python2.7/dist-packages/torch_scatter/functions/ffi.py", line 31, in scatter
    func = getattr(ffi, 'scatter_{}_{}{}'.format(name, cuda, typename))
AttributeError: 'module' object has no attribute 'scatter_max_cuda_Float'

======================================================================
ERROR: Failure: ImportError (cannot import name voxel_max_pool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/pool/voxel_pool_test.py", line 7, in <module>
    from .voxel_pool import voxel_max_pool
ImportError: cannot import name voxel_max_pool

======================================================================
ERROR: test_backward (torch_geometric.nn.functional.spline_conv.spline_conv_test.SplineConvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/spline_conv/spline_conv_test.py", line 139, in test_backward
    K, True,dtype='double')
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/spline_conv/spline_conv_gpu.py", line 185, in get_weighting_backward_kernel
    K=K)
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "/home/eman/pytorch_geometric-master/torch_geometric/utils/cuda.py", line 37, in load_kernel
    kernel_code = cupy.cuda.compile_with_cache(code)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 152, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 70, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
CompileException: /tmp/tmph73gef/kern.cu(44): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

/tmp/tmph73gef/kern.cu(50): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

2 errors detected in the compilation of "/tmp/tmph73gef/kern.cu".

-------------------- >> begin captured stdout << ---------------------

 0.8099  0.1667
 0.6158  0.8041
 0.8828  0.6689
 0.7352  0.4808
[torch.cuda.DoubleTensor of size 4x2 (GPU 0)]


--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_forward (torch_geometric.nn.modules.graph_conv_test.GraphConvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/modules/graph_conv_test.py", line 31, in test_forward
    out = conv(adj, features)
  File "/home/eman/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/modules/graph_conv.py", line 43, in forward
    return graph_conv(x, edge_index, edge_attr, self.weight, self.bias)
  File "/home/eman/pytorch_geometric-master/torch_geometric/nn/functional/graph_conv.py", line 28, in graph_conv
    row, col = edge_index
ValueError: too many values to unpack

----------------------------------------------------------------------
Ran 37 tests in 2.858s

FAILED (errors=7)
`
```

**Comment by rusty1s** [comment]
Hello Eman,

tests are currently failing in the master branch. We are aware of this issue. However, running the examples (e.g. `python3 examples/cora.py`) should work fine.

**Comment by emanhamed** [comment]
Actually not all the examples are working well. core.py is okay .. but some other files are not. For example mnist.py is not : 
```
root@Linux-HUETOS:~/pytorch_geometric-master/examples# python3 mnist.py 
Traceback (most recent call last):
  File "mnist.py", line 102, in <module>
    train(epoch)
  File "mnist.py", line 84, in train
    loss = F.nll_loss(model(data), data.target)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "mnist.py", line 49, in forward
    data, _ = sparse_voxel_max_pool(data, 5, 0, CartesianAdj())
  File "../torch_geometric/nn/functional/pool/voxel_pool.py", line 19, in sparse_voxel_max_pool
    output = sparse_grid_cluster(pos_tensor, size, data.batch, start)
  File "/home/eman/.local/lib/python3.5/site-packages/torch_cluster/functions/grid.py", line 76, in sparse_grid_cluster
    position, size = _preprocess(position, size, batch, start)
  File "/home/eman/.local/lib/python3.5/site-packages/torch_cluster/functions/grid.py", line 25, in _preprocess
    elif start != 0:
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 153, in __bool__
    " objects is ambiguous")
RuntimeError: bool value of non-empty torch.cuda.ByteTensor objects is ambiguous
```
and cora_gat.py is also not working and here is what I'm getting: 

```
root@Linux-HUETOS:~/pytorch_geometric-master/examples# python3 cora_gat.py 
Traceback (most recent call last):
  File "cora_gat.py", line 70, in <module>
    train()
  File "cora_gat.py", line 52, in train
    F.nll_loss(model()[train_mask], data.target[train_mask]).backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "cora_gat.py", line 35, in forward
    x = F.elu(self.att1(data.input, data.index))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "../torch_geometric/nn/modules/gat.py", line 67, in forward
    self.weight, self.att_weight, self.bias)
  File "../torch_geometric/nn/functional/gat.py", line 41, in gat
    alpha_sum = alpha.new(n, k).fill_(0).scatter_add_(0, var_row, alpha)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 67, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'new'
```

**Comment by rusty1s** [comment]
Ok, thanks! I will look into this. Which PyTorch version do you use?

**Comment by emanhamed** [comment]
I have installed pytorch 0.3.0.post4 using this command: 
pip3 install torch torchvision

I have cuda 8.0 and python 3

**Comment by emanhamed** [comment]
Hello again Matthias! 
I have noticed that spline_conv.py and spline_conv_test.py in  
pytorch_geometric/torch_geometric/nn/modules/spline_conv.py
are producing some errors as well like:  
```
root@Linux-HUETOS:~/pytorch_geometric-master/torch_geometric/nn/modules# python3 spline_conv.py
Traceback (most recent call last):
  File "spline_conv.py", line 4, in <module>
    from .utils.inits import uniform
SystemError: Parent module '' not loaded, cannot perform relative import

```
and the same with spline_conv_test.py 
```
root@Linux-HUETOS:~/pytorch_geometric-master/torch_geometric/nn/modules# python3 spline_conv_test.py
Traceback (most recent call last):
  File "spline_conv_test.py", line 3, in <module>
    from .utils.repeat import repeat_to
SystemError: Parent module '' not loaded, cannot perform relative import

```

Would you please help me solve this issue ?

**Comment by emanhamed** [comment]
No problem! Thank you so much for your help and your great contribution to the community.

**Comment by emanhamed** [comment]
Hello , 
I see that the library is building successfully now on the master branch. However, I'm still receiving some errors while running the test files specifically in SplineConv files. Here are the errors : 

 ```
File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /tmp/tmp6ed_ao9f/kern.cu(44): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

/tmp/tmp6ed_ao9f/kern.cu(50): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
```

Here is the whole output on the terminal: 

```root@Linux-HUETOS:~/Pytorch_Installation/pytorch_geometric-master# nosetests3 
...................E..................
======================================================================
ERROR: test_backward (torch_geometric.nn.functional.spline_conv.spline_conv_test.SplineConvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 229, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eman/Pytorch_Installation/pytorch_geometric-master/torch_geometric/nn/functional/spline_conv/spline_conv_test.py", line 139, in test_backward
    in_features, out_features, k_max, K, True, dtype='double')
  File "/home/eman/Pytorch_Installation/pytorch_geometric-master/torch_geometric/nn/functional/spline_conv/spline_conv_gpu.py", line 185, in get_weighting_backward_kernel
    K=K)
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "/home/eman/Pytorch_Installation/pytorch_geometric-master/torch_geometric/utils/cuda.py", line 37, in load_kernel
    kernel_code = cupy.cuda.compile_with_cache(code)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 152, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 70, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /tmp/tmp6ed_ao9f/kern.cu(44): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

/tmp/tmp6ed_ao9f/kern.cu(50): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

2 errors detected in the compilation of "/tmp/tmp6ed_ao9f/kern.cu".


----------------------------------------------------------------------
Ran 38 tests in 13.405s

FAILED (errors=1)
```

**Comment by rusty1s** [comment]
Hello Eman,

all your reported issues of `pytorch_geometric` should be fixed now. Please notice the new installation instructions. However, for the project to run, you need to install `torch-cluster`, `torch-unique`, `torch-scatter` and `torch-spline-conv`. Do you still have problems installing these? If yes, we should shift this discussion to the other repositories.

I'm closing this for now. Thanks for your help!
