### ISSUE TITLE
Example on PointNet2 segmentation does not work with other features than coordinates.

### ISSUE THREAD

**Issue by VaysseRobin** [rusty1s/pytorch_geometric#456]
## 🐛 Bug

Hi, thank you for your awesome work !

I am trying to use your implementation of pointnet2_segmentation on a dataset which have 2 features in addition to the coordinates of the points but it seems that this does not work at the moment. 

Here is the complete error message:
``` 
Traceback (most recent call last):
  File "src/Pytorch/PointNet2_pt.py", line 202, in <module>
    train()
  File "src/Pytorch/PointNet2_pt.py", line 142, in train
    out = model(data)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "src/Pytorch/PointNet2_pt.py", line 118, in forward
    sa1_out = self.sa1_module(*sa0_out)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "src/Pytorch/PointNet2_pt.py", line 59, in forward
    x = self.conv(x, (pos, pos[idx]), edge_index)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch_geometric/nn/conv/point_conv.py", line 66, in forward
    return self.propagate(edge_index, x=x, pos=pos)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 120, in propagate
    out = self.message(*message_args)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch_geometric/nn/conv/point_conv.py", line 73, in message
    msg = self.local_nn(msg)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/work/stages/vaysse/torch_env/lib/python3.6/site-packages/torch/nn/functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [129547 x 6], m2: [3 x 64] at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMathBlas.cu:268
```

So I would like to know if it is a bug or if you think that you implemented the algorithm well and the problem comes from my data.

## Environment

* OS: CentOS 7
* Python version: 3.6
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 10.0
* GCC version: 5.4.0
* Torch geometric version: 1.3.0

**Comment by rusty1s** [comment]
I guess you need to modify the number of input channels?

**Comment by VaysseRobin** [comment]
Ow I'm an idiot sorry. Thanks a lot !
