### ISSUE TITLE
Issue launching example/faust.py

### ISSUE THREAD

**Issue by EoAelinr** [rusty1s/pytorch_geometric#457]
Hello.

I'm getting an error when launching faust.py :
```
Traceback (most recent call last):
  File "faust.py", line 83, in <module>
    train(epoch)
  File "faust.py", line 68, in train
    F.nll_loss(model(data.to(device)), target).backward()
  File "/home/oliviern/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "faust.py", line 41, in forward
    x = F.elu(self.conv1(x, edge_index, pseudo), edge_index)
  File "/home/oliviern/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1025, in elu
    result = torch._C._nn.elu(input, alpha)
TypeError: elu(): argument 'alpha' (position 2) must be Number, not Tensor
```

Here is my (anaconda) setup :
```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_0  
cffi                      1.12.3           py36h2e261b9_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
decorator                 4.4.0                    pypi_0    pypi
intel-openmp              2019.4                      243  
isodate                   0.6.0                    pypi_0    pypi
joblib                    0.13.2                   pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.3                      pypi_0    pypi
ninja                     1.9.0            py36hfd86e86_0  
numpy                     1.16.4           py36h7e9f1db_0  
numpy-base                1.16.4           py36hde5b4d6_0  
openssl                   1.1.1c               h7b6447c_1  
pandas                    0.24.2                   pypi_0    pypi
pip                       19.1.1                   py36_0  
plyfile                   0.7                      pypi_0    pypi
pycparser                 2.19                     py36_0  
pyparsing                 2.4.0                    pypi_0    pypi
python                    3.6.8                h0371630_0  
python-dateutil           2.8.0                    pypi_0    pypi
pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch
pytz                      2019.1                   pypi_0    pypi
rdflib                    4.2.2                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
scikit-learn              0.21.2                   pypi_0    pypi
scipy                     1.2.1            py36h7c811a0_0  
setuptools                41.0.1                   py36_0  
sqlite                    3.28.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torch-cluster             1.4.2                    pypi_0    pypi
torch-scatter             1.2.0                    pypi_0    pypi
torch-sparse              0.4.0                    pypi_0    pypi
torch-spline-conv         1.1.0                    pypi_0    pypi
wheel                     0.33.4                   py36_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3
```

I have no issue with a nearly identical anaconda setup, on Windows. I'm on Linux.
I installed pytorch_geometric with `python setup.py install` in both cases.

What might be causing this ?

**Comment by rusty1s** [comment]
Yes, there was a bug in the example which is fixed in master. There was a weird second argument to the `elu` call. The right way to call it is:
```python
        x = F.elu(self.conv1(x, edge_index, pseudo))
```

**Comment by EoAelinr** [comment]
Thank you, fixing these lines solved it.
