### ISSUE TITLE
'***' object has no attribute 'num_layers'.

### ISSUE THREAD

**Issue by HaiyuZhou** [rusty1s/pytorch_geometric#495]
## To Reproduce

When I try to run the file in 'benchmark/kernel/main.py' on my own dataset, I got a error that happen in some net class files such as 'top_k.py', 'sag_pool.py'. I checked the file and found the reason of the bug, that is when calling the forward function, the net class has not a property 'num_layers' (line43 in file ‘sag_pool.py’），you can fix it by adding a line 'self.num_layers = num_layers' in the init function.

Traceback (most recent call last):
  File "/home/haiyuz/PycharmProjects/pytorch_geometric/benchmark/kernel/main.py", line 74, in <module>
    logger=None)
  File "/home/haiyuz/PycharmProjects/pytorch_geometric/benchmark/kernel/train_eval.py", line 50, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "/home/haiyuz/PycharmProjects/pytorch_geometric/benchmark/kernel/train_eval.py", line 121, in train
    out = model(data)
  File "/usr/local/anaconda3/envs/torch3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haiyuz/PycharmProjects/pytorch_geometric/benchmark/kernel/sag_pool.py", line 43, in forward
    if i % 2 == 0 and i < (self.num_layers - 2):
  File "/usr/local/anaconda3/envs/torch3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'SAGPool' object has no attribute 'num_layers'

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Should be already fixed in master, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/top_k.py).
