### ISSUE TITLE
CUDA Initialization Error in Dataloader when num_workers > 1

### ISSUE THREAD

**Issue by tawe141** [rusty1s/pytorch_geometric#499]
Setting num_workers results in a CUDA initialization error for a Dataloader using an InMemoryDataset: 

```
/home/erictaw/miniconda3/bin/python /home/erictaw/PycharmProjects/experimental_uv_vis/models/pytorch_geometric/test.py
Traceback (most recent call last):
  File "/home/erictaw/PycharmProjects/experimental_uv_vis/models/pytorch_geometric/test.py", line 141, in <module>
    for i, batch in enumerate(train_dl):
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 75, in __getitem__
    data = self.get(idx)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 111, in get
    slices[idx], slices[idx + 1])
RuntimeError: CUDA error: initialization error
```

Is this a bug, or am I doing something wrong?

**Comment by rusty1s** [comment]
Can you show me an example to reproduce? I am using `num_workers > 1` constantly without any problems.

**Comment by tawe141** [comment]
Sure. See below. The dataset is loading a cached copy of the data. 

```
    train_dataset = SmilesDataset()
    train_dataset.data.edge_attr = train_dataset.data.edge_attr.type('torch.FloatTensor').cuda()
    train_dataset.data.x = train_dataset.data.x.type('torch.FloatTensor').cuda()
    train_dataset.data.y = train_dataset.data.y.type('torch.FloatTensor').cuda()
    
    test_dataset = SmilesDataset(mode='test')
    test_dataset.data.edge_attr = test_dataset.data.edge_attr.type('torch.FloatTensor').cuda()
    test_dataset.data.x = test_dataset.data.x.type('torch.FloatTensor').cuda()
    test_dataset.data.y = test_dataset.data.y.type('torch.FloatTensor').cuda()

    train_dl = DataLoader(train_dataset, batch_size=500, shuffle=True)
    test_dl = DataLoader(test_dataset, batch_size=500, shuffle=True)
```

**Comment by rusty1s** [comment]
This should work just fine without manually transferring the complete dataset to the GPU. I guess this is not supported by PyTorch.

**Comment by tawe141** [comment]
The error still occurs when I remove `.cuda()`. If I force the `slices` tensors to CPU, it works great, although now training becomes quite slow as the GPU is no longer in use. Should I be transferring each individual batch to GPU prior to training instead of keeping the entire dataset on the GPU?

**Comment by rusty1s** [comment]
Yes, this is what we do in all examples, transferring each batch separately to the GPU by calling `data.to(device)`.

**Comment by tawe141** [comment]
Ah should've known. Thanks.
