### ISSUE TITLE
error: data_parallel

### ISSUE THREAD

**Issue by Bonsen** [rusty1s/pytorch_geometric#54]
Traceback (most recent call last):
  File "train.py", line 167, in validate
    output = model(x)
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 122, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 127, in replicate
    return replicate(module, device_ids)
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 12, in replicate
    param_copies = Broadcast.apply(devices, *params)
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 19, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/z/anaconda36/lib/python3.6/site-packages/torch/cuda/comm.py", line 40, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 1: unhandled cuda error

It seems the multi-gpus error? (using GATlayers)

**Comment by rusty1s** [comment]
Do you have a short example to reproduce this error?

**Comment by Bonsen** [comment]
Sorry, it's the other bug of the code.
