### ISSUE TITLE
Can PyG run on cuda9?

### ISSUE THREAD

**Issue by qslim** [rusty1s/pytorch_geometric#557]
## ❓ Questions & Help

The nvidia driver version of our server is low. I can only use cuda9 on server. I test it and failed. Could you please tell me that can PyG run on cuda9?

**Comment by rusty1s** [comment]
It can run on cuda9, see our [dockerfile](https://github.com/rusty1s/pytorch_geometric/tree/master/docker).

**Comment by qslim** [comment]
That is really helpful! I will try it. Thanks for your reply.

**Comment by qslim** [comment]
I use image provided in https://hub.docker.com/r/shengwenliang/pytorch_graph
and got following error:
`user@331999e30282:~/pytorch_geometric/examples$ python gcn.py 
Traceback (most recent call last):
  File "gcn.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
  File "/home/user/pytorch_geometric/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/user/pytorch_geometric/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/user/pytorch_geometric/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/user/pytorch_geometric/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/user/pytorch_geometric/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch_sparse/__init__.py", line 5, in <module>
    from .spspmm import spspmm
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch_sparse/spspmm.py", line 7, in <module>
    import torch_sparse.spspmm_cuda
ImportError: libcusparse.so.9.0: cannot open shared object file: No such file or directory
user@331999e30282:~/pytorch_geometric/examples$ `

**Comment by qslim** [comment]
I use image provided in https://hub.docker.com/r/shengwenliang/pytorch_graph
and got following error:

user@331999e30282:~/pytorch_geometric/examples$ python gcn.py 
Traceback (most recent call last):
  File "gcn.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
  File "/home/user/pytorch_geometric/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/user/pytorch_geometric/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/user/pytorch_geometric/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/user/pytorch_geometric/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/user/pytorch_geometric/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch_sparse/__init__.py", line 5, in <module>
    from .spspmm import spspmm
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch_sparse/spspmm.py", line 7, in <module>
    import torch_sparse.spspmm_cuda
ImportError: libcusparse.so.9.0: cannot open shared object file: No such file or directory
user@331999e30282:~/pytorch_geometric/examples$

**Comment by qslim** [comment]
image was updated by @shengwenLeong in https://hub.docker.com/r/shengwenliang/pytorch_geometric_liang
