### ISSUE TITLE
set2set output depends on batch order?

### ISSUE THREAD

**Issue by allchemist** [rusty1s/pytorch_geometric#57]
Hello,

i have noticed that the output of set2set layer may depend on the order of the batch. For example, if i stack two graphs into a batch, the output is different than if i feed the graphs separately into the set2set, or stack the graphs in reverse order. I suppose that set2set uses torch_geometric.utils.to_batch function to separate convolution output to separate structures and feed them separately into set2set...

Moreover, this behaviour occures not very often. For example, in my dataset it happens in 408 cases of 1870 ones (~20%). In the rest 80% way of stacking into a batch does not influence the output (outputs are strictly equal).

I'm not saying it is a bug in pytorch_geometric, probably i'm doing smth wrong, could you please help me find the problem. I can prepare and share the data and a script which reproduces the behavior

**Comment by rusty1s** [comment]
I will look into this. Thank you very much.

**Comment by allchemist** [comment]
Thanks, i'll prepare the script in few hours

**Comment by rusty1s** [comment]
No need to. I can reproduce the error.

**Comment by rusty1s** [comment]
Fixed in master :) Thank you so much for finding this bug!

**Comment by allchemist** [comment]
Thanks for quick fix!

**Comment by allchemist** [comment]
After update i have faced the problem:

>> import torch_geometric.nn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .conv import *  # noqa
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/__init__.py", line 13, in <module>
    from .x_conv import XConv
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/x_conv.py", line 6, in <module>
    from torch_cluster import knn_graph
ImportError: cannot import name 'knn_graph'

**Comment by rusty1s** [comment]
Yes, please upgrade torch_cluster.

**Comment by allchemist** [comment]
After updating i have this:
```
>>> import torch_geometric.nn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .conv import *  # noqa
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/__init__.py", line 10, in <module>
    from .spline_conv import SplineConv
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/spline_conv.py", line 3, in <module>
    from torch_spline_conv import SplineConv as Conv
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_spline_conv/__init__.py", line 1, in <module>
    from .basis import SplineBasis
  File "/home/alchemist/.local/lib/python3.6/site-packages/torch_spline_conv/basis.py", line 2, in <module>
    import basis_cpu
ImportError: /home/alchemist/.local/lib/python3.6/site-packages/basis_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE
```

Probably better to move isntallation stuff to a separate issue?

**Comment by rusty1s** [comment]
Mh, did you upgrade all packages? This seems highly related to https://github.com/rusty1s/pytorch_scatter/issues/7. Can you clear the pip cache and try again?

**Comment by allchemist** [comment]
Yes, i have upgraded everything including pytorch itself, as descriped in installation instructions.

**Comment by allchemist** [comment]
With clear cache it has been installed ok!

**Comment by rusty1s** [comment]
Cool! Have fun with the updated version!
