### ISSUE TITLE
UnicodeDecodeError during installation

### ISSUE THREAD

**Issue by jinze1994** [rusty1s/pytorch_geometric#578]
## 📚 Installation

Encounter the problem `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte` during installing the `torch_scatter`.

Detailed log:
```
(torch110) baijin@pku:~/Code/test$ pip install --verbose --no-cache-dir torch-scatter
Collecting torch-scatter
  1 location(s) to search for versions of torch-scatter:
  * https://pypi.python.org/simple/torch-scatter/
  Getting page https://pypi.python.org/simple/torch-scatter/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/torch-scatter/ HTTP/1.1" 301 122
  Starting new HTTPS connection (1): pypi.org
  "GET /simple/torch-scatter/ HTTP/1.1" 200 1104
  Analyzing links from page https://pypi.org/simple/torch-scatter/
    Found link https://files.pythonhosted.org/packages/29/96/566ac314e796d4b07209a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.org/simple/torch-scatter/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/6a/b0/ecffacddf573c147c70c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.org/simple/torch-scatter/), version: 1.0.2
    Found link https://files.pythonhosted.org/packages/08/09/07b106f3e74246f4ecf6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.org/simple/torch-scatter/), version: 1.0.3
    Found link https://files.pythonhosted.org/packages/2d/70/df2bc259d9606f00854ca43b6839f9047ec44900563435e0067584c93864/torch_scatter-1.0.4.tar.gz#sha256=ec004d687e47da9d5477407849d815629fc8b571ee87aeeebf6af8ed6f16defc (from https://pypi.org/simple/torch-scatter/), version: 1.0.4
    Found link https://files.pythonhosted.org/packages/2f/97/c50a6aeaedc6924180c6f5810d2a7405ce11aa9b82ba4284badad549d665/torch_scatter-1.1.0.tar.gz#sha256=e534cc2ecb2f9d9b559b1513cd411737d26ea5585d1d65ff571fec55f42a49de (from https://pypi.org/simple/torch-scatter/), version: 1.1.0
    Found link https://files.pythonhosted.org/packages/91/5f/eb1d3ef3810cb1165859d40db4d9ee6d7f1dfef97d7e5c34010055f43d95/torch_scatter-1.1.1.tar.gz#sha256=9db7f2c0a5cddf6cfde633e33db7c2c94eaab163e9f8edb46460d6414cc97917 (from https://pypi.org/simple/torch-scatter/), version: 1.1.1
    Found link https://files.pythonhosted.org/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a (from https://pypi.org/simple/torch-scatter/), version: 1.1.2
    Found link https://files.pythonhosted.org/packages/07/c0/f7ac424496f4a3bcb31aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz#sha256=3a0259105d07d264c740eec8e4267260a5c144cf55472abd26022fff4fd73281 (from https://pypi.org/simple/torch-scatter/), version: 1.2.0
    Found link https://files.pythonhosted.org/packages/24/b7/680c3b392a4b55a0ebfb480aabb0d5c188e94bb21790104175c8cd614947/torch_scatter-1.3.0.tar.gz#sha256=bf7d561b8ef12b39a99f5797c90b989a0ce2c3ee4de74dff3b170f2d8566e1d4 (from https://pypi.org/simple/torch-scatter/), version: 1.3.0
    Found link https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.org/simple/torch-scatter/), version: 1.3.1
  Using version 1.3.1 (newest of versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1)
  Starting new HTTPS connection (1): files.pythonhosted.org
  "GET /packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz HTTP/1.1" 200 12787
  Downloading https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.org/simple/torch-scatter/)
  Running setup.py (path:/tmp/pip-build-2msq0zxk/torch-scatter/setup.py) egg_info for package torch-scatter
    Running command python setup.py egg_info
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-build-2msq0zxk/torch-scatter/.eggs/pytest_runner-5.1-py3.6.egg
    running egg_info
    creating pip-egg-info/torch_scatter.egg-info
    writing pip-egg-info/torch_scatter.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/torch_scatter.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/torch_scatter.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/torch_scatter.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/torch_scatter.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/torch_scatter.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-2msq0zxk/torch-scatter has version 1.3.1, which satisfies requirement torch-scatter from https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter ...     Running command /home/baijin/Lib/anaconda3/envs/torch110/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2msq0zxk/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-352j3_tr-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
    creating build/lib.linux-x86_64-3.6/test
    copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_max_min.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
    copying test/utils.py -> build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    running build_ext
    building 'torch_scatter.scatter_cpu' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cpu
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include -I/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/TH -I/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/THC -I/home/baijin/Lib/anaconda3/envs/torch110/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /usr/include/c++/7/iomanip:43:0,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/c10/util/logging_is_not_google_glog.h:8,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/c10/util/Logging.h:28,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/c10/core/TensorImpl.h:17,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/core/Tensor.h:10,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/core/Type.h:569,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/Type.h:2,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                     from /home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                     from cpu/scatter.cpp:1:
    /usr/bin/locale:1:1: error: stray ‘\177’ in program
error
Cleaning up...
  Removing source in /tmp/pip-build-2msq0zxk/torch-scatter
Exception:
Traceback (most recent call last):
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

## Environment

* OS: Ubuntu 18.04.2 LTS
* Python version: 3.6.2
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 10.0
* GCC version: 7.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

Detailed env:
```
(torch110) baijin@pku:~/Code/test$ python collect_env.py
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
[conda] mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.3.0           py36_cu10.0.130_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
(torch110) baijin@pku:~/Code/test$ echo $PATH
/home/baijin/Lib/anaconda3/envs/torch110/bin:/home/baijin/Lib/anaconda3/bin:/home/baijin/Lib/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(torch110) baijin@pku:~/Code/test$ echo $CPATH
/home/baijin/Lib/cuda-10.0/include:/home/baijin/Lib/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(torch110) baijin@pku:~/Code/test$ echo $LD_LIBRARY_PATH
/home/baijin/Lib/cuda-10.0/lib64:/home/baijin/Lib/cuda-10.0/extras/CUPTI/lib64:
(torch110) baijin@pku:~/Code/test$ conda list -n torch110
# packages in environment at /home/baijin/Lib/anaconda3/envs/torch110:
#
blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
certifi                   2016.2.28                py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cffi                      1.10.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cudatoolkit               10.0.130                      0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
freetype                  2.5.5                         2    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
intel-openmp              2019.4                      243    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
jbig                      2.1                           0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
libffi                    3.2.1                         1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
libpng                    1.6.30                        1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
libtiff                   4.0.6                         3    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ninja                     1.7.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
numpy                     1.13.3           py36ha12f23b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
olefile                   0.44                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
openssl                   1.0.2l                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pandas                    0.25.0                    <pip>
pillow                    4.2.1                    py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pycparser                 2.18                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
python                    3.6.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
python-dateutil           2.8.0                     <pip>
pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2019.1                    <pip>
readline                  6.2                           2    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
setuptools                36.4.0                   py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
torchvision               0.3.0           py36_cu10.0.130_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
wheel                     0.29.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
xz                        5.2.3                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
```

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
Can you downgrade your `gcc` to version 5.4 and see if this fixes the issue?

**Comment by jinze1994** [comment]
I still have the same problem when I downgrade my gcc to 5.4.

The error log and env:
```
(torch110) baijin@pku:~$ pip install torch_scatter-1.3.1.tar.gz
Processing ./torch_scatter-1.3.1.tar.gz
Building wheels for collected packages: torch-scatter
  Running setup.py bdist_wheel for torch-scatter ... error
  Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter ... error
Exception:
Traceback (most recent call last):
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(torch110) baijin@pku:~$ cd ~/Code/test/
(torch110) baijin@pku:~/Code/test$ ls
collect_env.py  log.txt  t.py  tt.py
(torch110) baijin@pku:~/Code/test$ python collect_env.py
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (GCC) 5.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
[conda] mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.3.0           py36_cu10.0.130_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
```

**Comment by SeokjuLee** [comment]
Hi, did you solve this issue?

**Comment by jinze1994** [comment]
@SeokjuLee My problem is that the CPATH includes the PATH incorrectly, and I fix it by resetting CPATH in `~/.bashrc`. I hope it is helpful for you.
