### ISSUE TITLE
DataLoader and torch_geometric.data

### ISSUE THREAD

**Issue by milts10** [rusty1s/pytorch_geometric#653]
Hello again, I know that I need to use torch_geometric.data on my data loader and only return data so I build a data loader based on that which works perfectly.

However right now I need to do something more complicated, I have three possible ways that I can go for:
1) I need to have multiple graphs on multiple arrays
2) a 3-dimensional array that has everything
3) Or I need to have a 2 Dimensional extra array that will give me the information in order to separate a really large graph into the other ones. 

I know that we can store very specific information on Data:
1) x
2) edge_index
3) etc.
However, I found that we can also store other variables ( great addition) so the question is can we also store extra 2D arrays when I tried I had with a np.zeros(10,10) array I had this error

```
Traceback (most recent call last):
  File "mnist_voxel_grid2.py", line 379, in <module>
    train()
  File "mnist_voxel_grid2.py", line 265, in train
    for data in train_loader_flow:
  File "/mnt/storage/home/qb18517/qb18517/.conda/envs/graphCon2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/mnt/storage/home/qb18517/qb18517/.conda/envs/graphCon2/lib/python3.7/site-packages/torch_geometric/data/dataloader.py", line 32, in <lambda>
    data_list, follow_batch),
  File "/mnt/storage/home/qb18517/qb18517/.conda/envs/graphCon2/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 70, in from_data_list
    raise ValueError('Unsupported attribute type.')
ValueError: Unsupported attribute type.
```

**Comment by rusty1s** [comment]
The default `collate` of the `DataLoader` can only collate scalars and `torch.tensor`, so converting your `numpy` array to a `torch.tensor` should work.

**Comment by milts10** [comment]
Wow, works thank you good thing that I asked you. Amazing response time as always!!!
