### ISSUE TITLE
Cannot specify 'collate_fn' in DataLoader

### ISSUE THREAD

**Issue by VladYushchenko** [rusty1s/pytorch_geometric#662]
## 🐛 Bug

Cannot specify custom collate_fn in torch_geometric.data.DataLoader

The desired behaviour is to have collate_fn that filters empty Data() entries from the batch

## To Reproduce

Note that ModelNet10 dataset does not have empty data and is just provided as an example.
Use this code snippet to reproduce the behaviour:

```
import os.path as osp
import torch_geometric.transforms as T
from torch_geometric.data import DataLoader, Batch
from torch_geometric.datasets import ModelNet

def filter_empty(data_list):
    return list(filter(lambda x: x is not None, data_list))

if __name__ == '__main__':
    path = osp.join(osp.dirname(osp.realpath(__file__)), 'data/ModelNet10')
    pre_transform, transform = T.NormalizeScale(), T.SamplePoints(1024)
    train_dataset = ModelNet(path, '10', True, transform, pre_transform)
    test_dataset = ModelNet(path, '10', False, transform, pre_transform)
    batch_size = 8
    num_workers = 2

    collate_fn = lambda x: Batch.from_data_list(filter_empty(x))

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                              num_workers=num_workers, collate_fn=collate_fn)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False,
                             num_workers=num_workers, collate_fn=collate_fn)
```

The code fails with following message:

```
Traceback (most recent call last):
  File "/home/vlad/.PyCharm2019.2/config/scratches/scratch_4.py", line 21, in <module>
    num_workers=num_workers, collate_fn=collate_fn)
  File "/home/vlad/Packages/miniconda3/envs/pytorch_geometric/lib/python3.7/site-packages/torch_geometric/data/dataloader.py", line 33, in __init__
    **kwargs)
TypeError: __init__() got multiple values for keyword argument 'collate_fn'
```

## Expected behaviour

The reason of failure is initialization of DataLoader.

```
class DataLoader(torch.utils.data.DataLoader):
    r"""Data loader which merges data objects from a
    :class:`torch_geometric.data.dataset` to a mini-batch.

    Args:
        dataset (Dataset): The dataset from which to load the data.
        batch_size (int, optional): How many samples per batch to load.
            (default: :obj:`1`)
        shuffle (bool, optional): If set to :obj:`True`, the data will be
            reshuffled at every epoch. (default: :obj:`False`)
        follow_batch (list or tuple, optional): Creates assignment batch
            vectors for each key in the list. (default: :obj:`[]`)
    """

    def __init__(self,
                 dataset,
                 batch_size=1,
                 shuffle=False,
                 follow_batch=[],
                 **kwargs):
        super(DataLoader, self).__init__(
            dataset,
            batch_size,
            shuffle,
            collate_fn=lambda data_list: Batch.from_data_list(
                data_list, follow_batch),
            **kwargs)
```

Possible solution is to check if the 'collate_fn' was specified in kwargs, I believe such behaviour is desirable. 

   ```
 def __init__(self,
                 dataset,
                 batch_size=1,
                 shuffle=False,
                 follow_batch=[],
                 **kwargs):

        if 'collate_fn' not in kwargs:
            kwargs['collate_fn'] = lambda data_list: Batch.from_data_list(
                data_list, follow_batch)

        super(DataLoader, self).__init__(
            dataset,
            batch_size,
            shuffle,
            **kwargs)
```

## Environment

* OS: Linux Mint 19.2 Tina
* Python version: 3.7
* PyTorch version: 1.2.0
* CUDA/cuDNN version: 10.0 / 7.6.2

**Comment by rusty1s** [comment]
Use the PyTorch DataLoader, not the PyTorch Geometric DataLoader, and this should work properly.

**Comment by VladYushchenko** [comment]
Thanks, can confirm that torch.utils.data.DataLoader works without any problems.
