### ISSUE TITLE
CUDA runtime error occurs when runing splineCNN on MNIST with grid graphs

### ISSUE THREAD

**Issue by ganji15** [rusty1s/pytorch_geometric#716]
## ❓ Questions & Help

Hi, @rusty1s. Thanks for your amazing project. I am new to pytorch_geometric, and I want to reproduce the results on MNIST with grid graphs (instead of supper pixels). 

At first, I convert the digit image into a grid graph as the paper mentioned, i.e.,

```python
    def __getitem__(self, index):  # pragma: no cover
        r"""Gets the data object at index :obj:`idx` and transforms it (in case
        a :obj:`self.transform` is given)."""

        img, target = self.data[index], int(self.targets[index])
        data = Data(x=img.flatten().float() / 255.,
                    edge_index=self.edge_index,
                    edge_attr=self.edge_attr,
                    pos=self.pos,
                    y=torch.LongTensor([[target]]))
        return data
```
Specifically, the edge_index stores the edge connections with grid structure, which has the shape of [2, num_edges]; and edge_attr stores the edge weights with the shape of [num_edges, 1], where each edge weight is calculated by exp(-||z_i - z_j||^2); and the pos (with shape of [num_nodes, 2]) stores the coordinates of allnodes.

After that, I run the SplineCNN on the defined MNIST dataset with grid graphs as follows:
```python

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SplineConv(d.num_features, 32, dim=1, kernel_size=5)
        self.conv2 = SplineConv(32, 64, dim=1, kernel_size=5)
        self.fc1 = torch.nn.Linear(64, 512)
        self.fc2 = torch.nn.Linear(512, d.num_classes)

    def forward(self, data):
        data.x = F.elu(self.conv1(data.x, data.edge_index, data.edge_attr))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        data.edge_attr = None
        data = max_pool(cluster, data, transform=T.Cartesian(cat=False))

        data.x = F.elu(self.conv2(data.x, data.edge_index, data.edge_attr))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        x, batch = max_pool_x(cluster, data.x, data.batch)

        x = global_mean_pool(x, batch)
        x = F.elu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        return F.log_softmax(self.fc2(x), dim=1)


def train(epoch):
    model.train()

    if epoch == 16:
        for param_group in optimizer.param_groups:
            param_group['lr'] = 0.001

    if epoch == 26:
        for param_group in optimizer.param_groups:
            param_group['lr'] = 0.0001

    for data in train_loader:
        data = data.to(device)
        optimizer.zero_grad()
        F.nll_loss(model(data), data.y).backward()
        optimizer.step()

for epoch in range(1, 31):
    train(epoch)
```

However, I encountered the CUDA runtime errors as follows:
```
* number of parameters: 50986  mode size: 0.1945MB
Net(
  (conv1): SplineConv(1, 32)
  (conv2): SplineConv(32, 64)
  (fc1): Linear(in_features=64, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=10, bias=True)
)
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/generic/THCTensorMath.cu line=16 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "mnist_full_spine_conv.py", line 91, in <module>
    train(epoch)
  File "mnist_full_spine_conv.py", line 74, in train
    F.nll_loss(model(data), data.y).backward()
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "mnist_full_spine_conv.py", line 43, in forward
    data.x = F.elu(self.conv2(data.x, data.edge_index, data.edge_attr))
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch_geometric/nn/conv/spline_conv.py", line 133, in forward
    return self.propagate(edge_index, x=x, pseudo=pseudo)
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 125, in propagate
    out = scatter_(self.aggr, out, edge_index[i], dim_size=size[i])
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 28, in scatter_
    out = op(src, index, 0, None, dim_size, fill_value)
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch_scatter/mean.py", line 68, in scatter_mean
    out = scatter_add(src, index, dim, out, dim_size, fill_value)
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch_scatter/add.py", line 72, in scatter_add
    src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
  File "/home/ganji/anaconda3/envs/graph/lib/python3.7/site-packages/torch_scatter/utils/gen.py", line 24, in gen
    out = src.new_full(out_size, fill_value)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/generic/THCTensorMath.cu:16
```

It seems that the error occurred when calculating the second SplineConv layer, and this is quite confusing since it is totally ok when calculating the first SplineConv layer.  I guess there may be something wrong when I prepare the MNIST data with grid structures, since the SplineConv works fine with the MNISTSuperpixels dataset. Are there some constraints on the order of data in edge_index, edge_attr, pos or x?

Could you kindly help me figure out what causes the issue? Thanks.

**Comment by rusty1s** [comment]
You can enable debugging mode via `torch_geometric.debug()` in the beginning of your script. For SplineCNN, we need edge features in the interval `[0, 1]`, and this may not be the case for your experiment.

**Comment by rusty1s** [comment]
Oh, I see that you make sure that features are in range `[0,1]` via `exp(.)`, but the `debug()` method nonetheless should help to track down the error.

**Comment by rusty1s** [comment]
Another potential issue is that you are computing Cartesian coordinates after the first pooling layer. Hence, your dimension changes from `1` to `2` in the second spline convolution.

**Comment by ganji15** [comment]
@rusty1s Thanks for your quick reply.

1. As suggested, I add the ```torch_geometric.debug()``` at the beginning of my script, but no further errors are printed.

![微信截图_20191003093157](https://user-images.githubusercontent.com/3733327/66093004-f5b0d880-e5c0-11e9-8cee-62af40d8e587.png)

![微信截图_20191003093505](https://user-images.githubusercontent.com/3733327/66093034-1c6f0f00-e5c1-11e9-9ba2-4f378e93e558.png)

2. I did compute Cartesian coordinates as edge features after the first pooling layer via ``` data = max_pool(cluster, data, transform=T.Cartesian(cat=False)) ``` 
Since I am new to GNN, I don't know the exact details of ``` max_pool``` and why I should use the transform ```T.Cartesian(cat=False))```. Moreover, you are definitely right that the dimension of edge features change from ```1``` to ```2``` as you said, and I don't know why it works like this. As expected, the dimension of edge features should remain unchanged, is that right?  Then, what should I do to fix this problem?

![微信截图_20191003094705](https://user-images.githubusercontent.com/3733327/66093448-dca92700-e5c2-11e9-8398-843f25f4ca2e.png)
![微信截图_20191003094735](https://user-images.githubusercontent.com/3733327/66093453-df0b8100-e5c2-11e9-83f8-f028bee363aa.png)

3. There are some other questions to construct the custom dataset, i.e., for the ```Data(x=None, edge_index=None, edge_attr=None, y=None, pos=None, norm=None, face=None, **kwargs)```

    i.  should the node orders of ```x``` be consistent with that of ```y```?

    ii.  should the edge orders of ```edge_index``` be consistent with that of ```edge_attr```?

    iii.  for ```edge_attr``` with the shape of ```[num_edges, num_edge_features]```, should each edge feature ```[1, num_edge_features]``` reflects the distance (of importance) of that edge in *Euclidean* space or something else?

I am looking forward to your help. Thanks

**Comment by ganji15** [comment]
I have changed dim of SplineConv from 1 to 2, and changed the dimension of edge_attr to 2 (offsets of x-, y- coordinates),  
```python
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SplineConv(d.num_features, 32, dim=2, kernel_size=5)
        self.conv2 = SplineConv(32, 64, dim=2, kernel_size=5)
        self.fc1 = torch.nn.Linear(64, 512)
        self.fc2 = torch.nn.Linear(512, d.num_classes)

    def forward(self, data):
        data.x = F.elu(self.conv1(data.x, data.edge_index, data.edge_attr))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        data.edge_attr = None
        data = max_pool(cluster, data, transform=T.Cartesian(cat=False))

        data.x = F.elu(self.conv2(data.x, data.edge_index, data.edge_attr))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        x, batch = max_pool_x(cluster, data.x, data.batch)

        x = global_mean_pool(x, batch)
        x = F.elu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        return F.log_softmax(self.fc2(x), dim=1)
```
if I set the initial learning rate with 0.01, and decay by 0.1  at epoch 16 & 26, then I got the following results:
```
* number of parameters: 92586  mode size: 0.3532MB
Net(
  (conv1): SplineConv(1, 32)
  (conv2): SplineConv(32, 64)
  (fc1): Linear(in_features=64, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=10, bias=True)
)
Epoch: 01, Test: 0.4831
Epoch: 02, Test: 0.6575
Epoch: 03, Test: 0.7300
Epoch: 04, Test: 0.7656
Epoch: 05, Test: 0.7980
Epoch: 06, Test: 0.8422
Epoch: 07, Test: 0.8376
Epoch: 08, Test: 0.8455
Epoch: 09, Test: 0.8599
Epoch: 10, Test: 0.8582
Epoch: 11, Test: 0.8454
Epoch: 12, Test: 0.8875
Epoch: 13, Test: 0.9013
Epoch: 14, Test: 0.8955
Epoch: 15, Test: 0.8706
Epoch: 16, Test: 0.9246
Epoch: 17, Test: 0.9279
Epoch: 18, Test: 0.9259
Epoch: 19, Test: 0.9305
Epoch: 20, Test: 0.9285
Epoch: 21, Test: 0.9321
Epoch: 22, Test: 0.9306
Epoch: 23, Test: 0.9300
Epoch: 24, Test: 0.9300
Epoch: 25, Test: 0.9261
Epoch: 26, Test: 0.9352
Epoch: 27, Test: 0.9341
Epoch: 28, Test: 0.9329
Epoch: 29, Test: 0.9341
Epoch: 30, Test: 0.9335
```
The results seem too  bad, and I guess there is something wrong with dataset construction.

**Comment by rusty1s** [comment]
1. First of all sorry, it should have been `torch_geometric.set_debug(True)` instead of `torch_geometric.debug()`.

2. After pooling, we need to compute new spatial coordinates based on changed graph connectivity. We cannot simply use the existing ones. Hence, there is a need to transform your graph data once again. 

3. Order of `edge_index` and `edge_attr` should be consistent. Ordering of `x` and `y` needs to be only consistent in case of node classification/regression tasks. What you encode in `edge_attr` is up to you. General speaking, encoding Cartesian coordinates works best. Those can be computed by `pos` which saves the absolute coordinates.

**Comment by ganji15** [comment]
@rusty1s I completely understand it, and thank you very much for your kind help.  I will try to reproduce the results on MNIST grid graphs.

**Comment by tonyandsunny** [comment]
@ganji15 
Which .py file do you put the above getitem code in?
The mnist dataset downloaded by url in the mnist_superpixels.py file is a 75 super pixel block. How do you download a new full-grid mnist data?
Looking forward to your reply！
Thanks

**Comment by ganji15** [comment]
@tonyandsunny I downloaded the MNIST images with torchvision API, and then constructed grid graphs by myself.

**Comment by rusty1s** [comment]
Yes, the way it should be done is using the MNIST image dataset from `torchvision`, and manually create your graphs using the `torch_geometric.utils.grid` function.

**Comment by arshishir** [comment]
@ganji15 Did you manage to get about 99% accuracy using SplineCNN? I have documented my effort here (https://github.com/rusty1s/pytorch_geometric/issues/1242) and I am only getting about ~70%. I used `torch_geometric.utils.grid` to create the grid graph. For `edge_attr`, I used `transform.Cartesian(cat= False)`

**Comment by ganji15** [comment]
@arshishir Yes, I did. The recognition code is similar to the example in tutorials, so the problem may come from the data construction. You can try the following way to construct the MNIST dataset:
```
edge_index, pos = grid(self.grid_size, self.grid_size) # self.grid_size = 28
np_img = np.array(img).flatten() # img is a PIL.Image object.
data = Data(x=torch.from_numpy(np_img).float() / 128. - 1.0,
                    edge_index=edge_index,
                    pos=pos,
                    y=torch.LongTensor([target]))
```
good luck.

**Comment by arshishir** [comment]
@ganji15  Thanks for replying. That's awesome :)  It seems like I am missing something here. 

 Why are you subtracting 1.0? In my case, I have normalized my data by dividing by 255. It seems like you have different normalization. You can see my full code here: https://github.com/rusty1s/pytorch_geometric/issues/1242

Did you use `transform.Cartesian(cat= False)` for `edge_attr`? 
Could you please share your full dataset class code?

Best

**Comment by ganji15** [comment]
@arshishir 
1. Normalization:   x->[0, 255.], after the normalization, x->[-1., 1.]
2. Yes, I use the ``transform.Cartesian(cat= False)``. It is the same with the tutorials.
3. The full dataset class code is given as follows:

```
class GridMNIST(InMemoryDataset):
    training_file, test_file = 'training.pt', 'test.pt'
    classes = ['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four',
               '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
    grid_size = 28
    sub_dir = '/gmnist/'

    def __init__(self, root, train=True, transform=None, pre_transform=None):
        super(GridMNIST, self).__init__(root + self.sub_dir, transform, pre_transform)
        path = self.processed_paths[0] if train else self.processed_paths[1]
        self.data, self.slices = torch.load(path)

    @property
    def raw_file_names(self):
        return [self.training_file, self.test_file]

    @property
    def processed_file_names(self):
        return [self.training_file, self.test_file]

    @property
    def num_classes(self):
        return 10

    def get_raw_dataset(self):
        train_dataset = MNIST(root=self.root + '/../', train=True, download=True)
        test_dataset = MNIST(root=self.root + '/../', train=False, download=True)
        return train_dataset, test_dataset

    def _load_alphabet(self):
        dict = {}
        for i in range(10):
            dict[i] = self.classes[i]
        return dict

    def download(self):
        self.get_raw_dataset()

    def process(self):
        train_dataset, test_dataset = self.get_raw_dataset()
        edge_index, pos = grid(self.grid_size, self.grid_size)

        def _process(dset, spath):
            data_list = []
            for img, target in tqdm(dset, desc='%s'%spath):
                np_img = np.array(img).flatten()
                data = Data(x=torch.from_numpy(np_img).float() / 128. - 1.0,
                            edge_index=edge_index,
                            pos=pos,
                            y=torch.LongTensor([target]))
                data_list.append(data)
            data, slices = self.collate(data_list)
            torch.save((data, slices), spath)
            print('save to ', spath)

        _process(test_dataset, self.processed_paths[1])
        _process(train_dataset, self.processed_paths[0])
```
I hope that it can solve the problem.

**Comment by arshishir** [comment]
@ganji15 Thanks again. I am getting about 48% accuracy @ epoch 15. Did you change something in the model too?

This is what I did:

```
import torchvision.datasets as datasets
class GridMNIST(InMemoryDataset):
    grid_size = 28

    def __init__(self, 
                 root, 
                 train=True, 
                 transform=None, 
                 pre_transform=None):
        super(GridMNIST, self).__init__(root, transform, pre_transform)
        path = self.processed_paths[0] if train else self.processed_paths[1]
        self.data, self.slices = torch.load(path)

    @property
    def raw_file_names(self):
        return ['training.pt', 'testing.pt']

    @property
    def processed_file_names(self):
        return ['training.pt', 'testing.pt']

    def get_raw_dataset(self):
        train_dataset = datasets.MNIST(root='/tmp/gmnist', train=True, download=True)
        test_dataset = datasets.MNIST(root='tmp/gmnist', train=False, download=True)
        return train_dataset, test_dataset


    def download(self):
        self.get_raw_dataset()

    def process(self):
        train_dataset, test_dataset = self.get_raw_dataset()
        edge_index, pos = grid(self.grid_size, self.grid_size)

        def _process(dset, spath):
            data_list = []
            for img, target in tqdm(dset, desc='%s'%spath):
                np_img = np.array(img).flatten()
                data = Data(x=torch.from_numpy(np_img).float() / 128. - 1.0,
                            edge_index=edge_index,
                            pos=pos,
                            y=torch.LongTensor([target]))
                data_list.append(data)
            data, slices = self.collate(data_list)
            torch.save((data, slices), spath)
            print('save to ', spath)

        _process(test_dataset, self.processed_paths[1])
        _process(train_dataset, self.processed_paths[0])

```
```
transform = T.Cartesian(cat=False)
ttdata = GridMNIST(root='/tmp/ttd',train= False,transform=transform)
trdata = GridMNIST(root='/tmp/ttd',train= True,transform=transform)
from torch_geometric.data import DataLoader
train_loader = DataLoader(trdata, batch_size=64, shuffle=True)
test_loader = DataLoader(ttdata, batch_size=64)
```
Here's the model, which is exactly the same as the one @ganji15 posted above:
```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SplineConv(d.num_features, 32, dim=2, kernel_size=5)
        self.conv2 = SplineConv(32, 64, dim=2, kernel_size=5)
        self.fc1 = torch.nn.Linear(64, 512)
        self.fc2 = torch.nn.Linear(512, d.num_classes)

    def forward(self, data):
        data.x = F.elu(self.conv1(data.x, data.edge_index, data.edge_attr))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        data.edge_attr = None
        data = max_pool(cluster, data, transform=transform)

        data.x = F.elu(self.conv2(data.x, data.edge_index, data.edge_attr))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        x, batch = max_pool_x(cluster, data.x, data.batch)

        x = global_mean_pool(x, batch)
        x = F.elu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        return F.log_softmax(self.fc2(x), dim=1)
```

```
#Training and testing module
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-4)

def train(epoch):
    model.train()

    for data in train_loader:
        data = data.to(device)
        optimizer.zero_grad()
        F.nll_loss(model(data), data.y).backward()
        optimizer.step()

def test():
    model.eval()
    correct = 0

    for data in test_loader:
        data = data.to(device)
        pred = model(data).max(1)[1]
        correct += pred.eq(data.y).sum().item()
    return correct / len(ttdata)



for epoch in range(1, 50):
    train(epoch)
    test_acc = test()
    print('Epoch: {:02d}, Test: {:.4f}'.format(epoch, test_acc))
```

**Comment by ganji15** [comment]
@arshishir How about set weight_decay=0 in ``optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-4)``?

**Comment by arshishir** [comment]
@ganji15 Sorry for not replying earlier. 

I think `weight_decay` isn't the problem here. Something weird was happening with the way I was using the MNIST data.
