### ISSUE TITLE
mac import error

### ISSUE THREAD

**Issue by 649459021** [rusty1s/pytorch_geometric#737]
## Environment

* OS: mac OS 10.14.6
* Python version: 3.6
* PyTorch version: 1.3.0
* CUDA/cuDNN version:None
* How did you try to install PyTorch Geometric and its extensions (pip, source):pip

## Checklist

- [ ] I followed the installation guide.

## Additional context
I entered the following lines of commands and completed the installation, but the import module showed an error.

$ MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install torch-scatter
$ MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install torch-sparse
$ MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install torch-cluster
$ MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install torch-geometric

No error occurred midway.

Installing collected packages: pytz, python-dateutil, pandas, idna, chardet, urllib3, requests, googledrivedownloader, pyparsing, isodate, rdflib, plyfile, decorator, networkx, h5py, joblib, scikit-learn, torch-geometric
Successfully installed chardet-3.0.4 decorator-4.4.0 googledrivedownloader-0.4 h5py-2.10.0 idna-2.8 isodate-0.6.0 joblib-0.14.0 networkx-2.4 pandas-0.25.1 plyfile-0.7.1 pyparsing-2.4.2 python-dateutil-2.8.0 pytz-2019.3 rdflib-4.2.2 requests-2.22.0 scikit-learn-0.21.3 torch-geometric-1.3.2 urllib3-1.25.6

Exception has occurred: ModuleNotFoundError
No module named 'torch_geometric'

**Comment by rusty1s** [comment]
Does `torch-geometric` show up in `pip list`?

**Comment by 649459021** [comment]
Yes!
(gnn) bash-3.2$ pip list
Package               Version        
--------------------- ---------------
certifi               2019.9.11      
cffi                  1.12.3         
chardet               3.0.4          
decorator             4.4.0          
googledrivedownloader 0.4            
h5py                  2.10.0         
idna                  2.8            
isodate               0.6.0          
joblib                0.14.0         
mkl-fft               1.0.14         
mkl-random            1.1.0          
mkl-service           2.3.0          
networkx              2.4            
numpy                 1.17.2         
olefile               0.46           
pandas                0.25.1         
Pillow                6.2.0          
pip                   19.2.3         
plyfile               0.7.1          
pycparser             2.19           
pyparsing             2.4.2          
python-dateutil       2.8.0          
pytz                  2019.3         
rdflib                4.2.2          
requests              2.22.0         
scikit-learn          0.21.3         
scipy                 1.3.1          
setuptools            41.4.0         
six                   1.12.0         
torch                 1.3.0          
torch-cluster         1.4.5          
torch-geometric       1.3.2          
torch-scatter         1.3.2          
torch-sparse          0.4.3          
torch-spline-conv     1.1.1          
torchvision           0.4.1a0+d94043a
urllib3               1.25.6         
wheel                 0.33.6

**Comment by 649459021** [comment]
I am using a virtual environment created with conda.Is it related to this?

**Comment by rusty1s** [comment]
I guess. There is no reason why `python` should not find `torch-geometric` if it is listed in `pip`. Do `pip` and `python` link to the same directory? I guess you are installing to the wrong `python` environment.

**Comment by 649459021** [comment]
I can import torch_scatter in the terminal, but it still shows no module in .py. The following error occurs when importing other modules

>>> import torch_scatter
>>> import torch_sparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Anaconda/anaconda3/envs/gnn/lib/python3.6/site-packages/torch_sparse/__init__.py", line 6, in <module>
    from .spspmm import spspmm
  File "/Applications/Anaconda/anaconda3/envs/gnn/lib/python3.6/site-packages/torch_sparse/spspmm.py", line 4, in <module>
    import torch_sparse.spspmm_cpu
ImportError: dlopen(/Applications/Anaconda/anaconda3/envs/gnn/lib/python3.6/site-packages/torch_sparse/spspmm_cpu.cpython-36m-darwin.so, 2): Symbol not found: _THPVariable_Wrap
  Referenced from: /Applications/Anaconda/anaconda3/envs/gnn/lib/python3.6/site-packages/torch_sparse/spspmm_cpu.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Applications/Anaconda/anaconda3/envs/gnn/lib/python3.6/site-packages/torch_sparse/spspmm_cpu.cpython-36m-darwin.so
