### ISSUE TITLE
No module named `unique_cuda` if CUDA is available

### ISSUE THREAD

**Issue by osanwe** [rusty1s/pytorch_geometric#75]
Hello,

To reproduce this error I'm using the following Dockerfile:
```
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    vim \
    ca-certificates \
    libjpeg-dev \
    libpng-dev \
    python3.5 \
    python3-pip

RUN pip3 install jupyterlab

RUN pip3 install torch
RUN pip3 install torchvision

RUN pip3 install --upgrade torch-scatter
RUN pip3 install --upgrade torch-sparse
RUN pip3 install --upgrade torch-cluster
RUN pip3 install --upgrade torch-spline-conv
RUN pip3 install torch-geometric

WORKDIR /workspace
RUN chmod -R a+x /workspace

EXPOSE 8888

CMD ["bash",  "-c", "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"]
```
and following commands:
```
$ nvidia-docker build -t pytorch-geometric .
$ nvidia-docker run -it --rm --ipc=host -p 8888:8888 -v $PWD:/workspace pytorch-geometric
```

According to another issue (https://github.com/rusty1s/pytorch_geometric/issues/8) the problem is with `torch-unique`. As I found, it was not installed as a required package for `pytorch-geometric`.

When I tried to install the `torch-unique` package the following error appeared:
```
# pip3 install --upgrade torch-unique

...
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.5/dist-packages/torch/lib/include -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c cuda/unique_kernel.cu -o build/temp.linux-x86_64-3.5/cuda/unique_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=unique_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cuda/unique_kernel.cu(22): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists
  
cuda/unique_kernel.cu(22): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
            argument types are: (int64_t)
  
2 errors detected in the compilation of "/tmp/tmpxft_00000037_00000000-6_unique_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
```

All works if `pytorch/pytorch` image is used as a base image like
```
FROM pytorch/pytorch

RUN conda install jupyterlab

RUN pip install --upgrade torch-scatter
RUN pip install --upgrade torch-sparse
RUN pip install --upgrade torch-cluster
RUN pip install --upgrade torch-spline-conv
RUN pip install torch-geometric

EXPOSE 8888

CMD ["bash",  "-c", "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"]
```
but for some reasons it doesn't have GPU support.

**Comment by rusty1s** [comment]
`torch-unique` does not work in PyTorch 1.0.0 and is no longer needed within PyTorch Geometric. So this error is to be expected.

**Comment by osanwe** [comment]
But for any `pytorch-geometric` import from the tutorial (https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cora.py) the following error is appeared:
```
>>> from torch_geometric.nn import SplineConv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .conv import *  # noqa
  File "/usr/local/lib/python3.5/dist-packages/torch_geometric/nn/conv/__init__.py", line 1, in <module>
    from .gcn_conv import GCNConv
  File "/usr/local/lib/python3.5/dist-packages/torch_geometric/nn/conv/gcn_conv.py", line 3, in <module>
    from torch_sparse import spmm
  File "/usr/local/lib/python3.5/dist-packages/torch_sparse/__init__.py", line 1, in <module>
    from .coalesce import coalesce
  File "/usr/local/lib/python3.5/dist-packages/torch_sparse/coalesce.py", line 4, in <module>
    from .utils.unique import unique
  File "/usr/local/lib/python3.5/dist-packages/torch_sparse/utils/unique.py", line 5, in <module>
    import unique_cuda
ImportError: No module named 'unique_cuda'
```

**Comment by rusty1s** [comment]
`unique_cuda` is now installed by `torch-sparse`, so please remove all instances of `torch-sparse` and `torch-unique` and reinstall only `torch-sparse`.

**Comment by osanwe** [comment]
Unfortunately the same.

```
# pip3 uninstall torch-unique
Cannot uninstall requirement torch-unique, not installed
```

```
# pip3 uninstall torch-sparse
Uninstalling torch-sparse-0.2.2:
  /usr/local/lib/python3.5/dist-packages/test/__init__.py
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/__init__.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/test_coalesce.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/test_eye.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/test_spmm.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/test_spspmm.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/test_transpose.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/__pycache__/utils.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/test/test_coalesce.py
  /usr/local/lib/python3.5/dist-packages/test/test_eye.py
  /usr/local/lib/python3.5/dist-packages/test/test_spmm.py
  /usr/local/lib/python3.5/dist-packages/test/test_spspmm.py
  /usr/local/lib/python3.5/dist-packages/test/test_transpose.py
  /usr/local/lib/python3.5/dist-packages/test/utils.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/INSTALLER
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/METADATA
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/RECORD
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/WHEEL
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/metadata.json
  /usr/local/lib/python3.5/dist-packages/torch_sparse-0.2.2.dist-info/top_level.txt
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__init__.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__pycache__/__init__.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__pycache__/coalesce.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__pycache__/eye.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__pycache__/spmm.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__pycache__/spspmm.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/__pycache__/transpose.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/coalesce.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/eye.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/spmm.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/spspmm.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/transpose.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/utils/__init__.py
  /usr/local/lib/python3.5/dist-packages/torch_sparse/utils/__pycache__/__init__.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/utils/__pycache__/unique.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/torch_sparse/utils/unique.py
Proceed (y/n)? y
  Successfully uninstalled torch-sparse-0.2.2
```

```
# pip3 install --upgrade torch_sparse
Collecting torch_sparse
Requirement already up-to-date: scipy in /usr/local/lib/python3.5/dist-packages (from torch_sparse)
Collecting numpy>=1.8.2 (from scipy->torch_sparse)
  Downloading https://files.pythonhosted.org/packages/64/24/2e9c72f44cec8c872000d78c54230e40550c494647e352d1d06724cdaee6/numpy-1.16.0-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
    100% |################################| 17.2MB 57kB/s
Installing collected packages: torch-sparse, numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
Successfully installed numpy-1.16.0 torch-sparse-0.2.2
```

```
# python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch_geometric.nn import SplineConv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .conv import *  # noqa
  File "/usr/local/lib/python3.5/dist-packages/torch_geometric/nn/conv/__init__.py", line 1, in <module>
    from .gcn_conv import GCNConv
  File "/usr/local/lib/python3.5/dist-packages/torch_geometric/nn/conv/gcn_conv.py", line 3, in <module>
    from torch_sparse import spmm
  File "/usr/local/lib/python3.5/dist-packages/torch_sparse/__init__.py", line 1, in <module>
    from .coalesce import coalesce
  File "/usr/local/lib/python3.5/dist-packages/torch_sparse/coalesce.py", line 4, in <module>
    from .utils.unique import unique
  File "/usr/local/lib/python3.5/dist-packages/torch_sparse/utils/unique.py", line 5, in <module>
    import unique_cuda
ImportError: No module named 'unique_cuda'
>>> torch.cuda.is_available()
True
```

**Comment by rusty1s** [comment]
Can you show me the log of `python setup.py install`?

**Comment by osanwe** [comment]
I changed my `Dockerfile` to:
```
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
                                                                                                                                                                                                            
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    vim \
    ca-certificates \
    libjpeg-dev \
    libpng-dev \
    python3.5 \
    python3-pip

RUN pip3 install jupyterlab

RUN pip3 install torch
RUN pip3 install torchvision

RUN pip3 install --upgrade numpy
RUN pip3 install --upgrade scipy
RUN pip3 install --upgrade networkx
RUN pip3 install --upgrade plyfile
RUN pip3 install --upgrade pandas
RUN pip3 install --upgrade rdflib

RUN git clone https://github.com/rusty1s/pytorch_scatter.git && \
    cd ./pytorch_scatter && \
    python3 ./setup.py install

RUN cd .. && \
    git clone https://github.com/rusty1s/pytorch_sparse.git && \
    cd ./pytorch_sparse && \
    python3 ./setup.py install

RUN cd .. && \
    git clone https://github.com/rusty1s/pytorch_cluster.git && \
    cd ./pytorch_cluster && \
    python3 ./setup.py install

RUN cd .. && \
    git clone https://github.com/rusty1s/pytorch_spline_conv.git && \
    cd ./pytorch_spline_conv && \
    python3 ./setup.py install

RUN cd .. && \
    git clone https://github.com/rusty1s/pytorch_geometric.git && \
    cd ./pytorch_geometric && \
    python3 ./setup.py install

WORKDIR /workspace
RUN chmod -R a+x /workspace

EXPOSE 8888

CMD ["bash",  "-c", "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"]
```
Now it seems that all work correctly using GPU.

Unfortunately I do not know why `pip` version does not work.

**Comment by rusty1s** [comment]
Hi, glad to hear! Sadly, the `pip` installer does not work correctly for everyone. If you have any idea why, please let me know :)

**Comment by ChanaRoss** [comment]
i have the same problem and none of these solutions helped.

any ideas?
