### ISSUE TITLE
Running Torch-Scatter

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#761]
Hey there, following up from some torch scatter running issues, I seem to be getting a similar problem to: #400

```
python -c "import torch_geometric"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "XXX/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "XXX/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "XXX/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "XXX/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "XXX/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "XXX/lib/python3.6/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "XXX/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "XXX/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "XXX/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "XXX/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by XXX/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so)
```
I cannot modify lib64 in my HPC environment. 

What can I do to circumvent this issue?

I'm not confident that a conda reinstall will do the trick. There's already many issues with conda, my environment won't solve due to well documented issues of conda bricking over time.

**Comment by jlevy44** [comment]
Why does it always search /lib64/libstdc++.so.6 ? On the HPC this path is not modifiable. 

How can I divert it?

**Comment by jlevy44** [comment]
This was also after restarting in a new conda environment

**Comment by jlevy44** [comment]
https://github.com/pytorch/pytorch/issues/8318
I think this did it.

**Comment by rusty1s** [comment]
Do you have fixed this issue? Great!

**Comment by jlevy44** [comment]
Yep, all is good. Also updating my gcc helped. I'll reopen if there are issues.
