### ISSUE TITLE
Edge Feature encoding

### ISSUE THREAD

**Issue by SaschaStenger** [rusty1s/pytorch_geometric#771]
## ❓ Questions & Help

Hi, i have a short question.

I'm building my own dataset and i do appear to have some problems with my edge attribute encoding. 
The edges in my graph can be one of 2 possible kinds of edges. 
So currently i try to encode them like this (example for 8 edges):
`tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])`

But this results in the following error:
```Traceback (most recent call 
File "/home/gcn_model.py", line 139, in <module>
    loss = train()    
  File "home/gcn_model.py", line 90, in train
    F.hinge_embedding_loss(model(data), data.y).backward()
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)    
  File "/home/gcn_model.py", line 67, in forward
    x = F.selu(self.conv1(x, edge_index, edge_attr))
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__    
    result = self.forward(*input, **kwargs)
  File "/hom/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 100, in forward
    self.improved, x.dtype)    
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 78, in norm
    edge_index, edge_weight, fill_value, num_nodes)    
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/utils/loop.py", line 106, in add_remaining_self_loops
    assert edge_weight.numel() == edge_index.size(1)
AssertionError
```

I also tried a boolean encoding before that, with:
`tensor([0., 0., 0., 0., 1., 1., 1., 1.], dtype=torch.byte)`

**Comment by rusty1s** [comment]
You can use the RGCNConv and save your edge type as a long tensor.

**Comment by SaschaStenger** [comment]
With my tensor now in long.
`tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]])`

 I get
```
Traceback (most recent call last):
  File "/home/gcn_model.py", line 141, in <module>
    loss = train()
  File "/home/gcn_model.py", line 92, in train
    F.hinge_embedding_loss(model(data), data.y).backward()
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gcn_model.py", line 69, in forward
    x = F.selu(self.conv1(x, edge_index, edge_attr))
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 69, in forward
    edge_index, x=x, edge_type=edge_type, edge_norm=edge_norm)
  File "/home/anaconda3/env/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 120, in propagate
    out = self.message(*message_args)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 82, in message
    w = torch.index_select(w, 0, edge_type)
RuntimeError: invalid argument 3: Index is supposed to be 1-dimensional at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:166
```

I'll include the network, as i am really stuck right now and would appreciate some advice.
```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = RGCNConv(train_dataset.num_features, 64, num_relations=train_dataset.num_relations, num_bases=30)
        self.conv2 = RGCNConv(64, 64, num_relations=train_dataset.num_relations, num_bases=30)

        self.lin1 = torch.nn.Linear(64, 32)
        self.lin2 = torch.nn.Linear(32, int(train_dataset.num_classes))

    def forward(self, data):
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr.t().contiguous().long()
        print(edge_attr)
        x = F.selu(self.conv1(x, edge_index, edge_attr))
        # x = F.dropout(x, training=self.training)
        x = F.selu(self.conv2(x, edge_index, edge_attr))

        x = global_mean_pool(x, data.batch)

        x = F.selu(self.lin1(x))
        x = F.selu(self.lin2(x))
        return F.log_softmax(x, dim=1)
```

**Comment by rusty1s** [comment]
`num_relations` should be set to `2` and `edge_attr` should be one-dimensional, *e.g.* `[0, 0, 1, 1, 0, ...]`.

**Comment by SaschaStenger** [comment]
```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = RGCNConv(train_dataset.num_features, 64, num_relations=2, num_bases=30)
        self.conv2 = RGCNConv(64, 64, num_relations=2, num_bases=30)

        self.lin1 = torch.nn.Linear(64, 32)
        self.lin2 = torch.nn.Linear(32, int(train_dataset.num_classes))

    def forward(self, data):
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr.split(1,dim=0)[0].long()
        print(edge_attr)
        x = F.selu(self.conv1(x, edge_index, edge_attr))
        # x = F.dropout(x, training=self.training)
        x = F.selu(self.conv2(x, edge_index, edge_attr))

        x = global_mean_pool(x, data.batch)

        x = F.selu(self.lin1(x))
        x = F.selu(self.lin2(x))
        return F.log_softmax(x, dim=1)
```

gives me a print for my edge_attr of
`tensor([[1, 1, 1, 1, 1, 0,....]])`

And an error stack of 

```
Traceback (most recent call last):
  File "/home/gcn_model.py", line 141, in <module>
    loss = train()
  File "/home/gcn_model.py", line 92, in train
    F.hinge_embedding_loss(model(data), data.y).backward()
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gcn_model.py", line 69, in forward
    x = F.selu(self.conv1(x, edge_index, edge_attr))
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 69, in forward
    edge_index, x=x, edge_type=edge_type, edge_norm=edge_norm)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 120, in propagate
    out = self.message(*message_args)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 82, in message
    w = torch.index_select(w, 0, edge_type)
RuntimeError: invalid argument 3: Index is supposed to be 1-dimensional at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:166

```

**Comment by rusty1s** [comment]
Your edge tensor is still two-dimensional, `edge_attr.flatten()` should fix this.
