### ISSUE TITLE
No module named 'unique_cuda'

### ISSUE THREAD

**Issue by gcucurull** [rusty1s/pytorch_geometric#8]
Hi, 

I have succesfully installed the dependencies `cffi`, `torch-unique`, ...
But when I run the Cora example `python cora.py` I get the following error:

```
Traceback (most recent call last):
  File "cora.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/datasets/__init__.py", line 1, in <module>
    from .tu_dataset import TUDataset
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/datasets/tu_dataset.py", line 5, in <module>
    from torch_geometric.data import InMemoryDataset, download_url, extract_zip
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 3, in <module>
    from .data import Data
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/data.py", line 2, in <module>
    from torch_geometric.utils import (is_coalesced, contains_isolated_nodes,
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/utils/__init__.py", line 4, in <module>
    from .coalesce import is_coalesced, coalesce
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/utils/coalesce.py", line 2, in <module>
    from torch_unique import unique
  File "/opt/conda/lib/python3.6/site-packages/torch_unique/__init__.py", line 1, in <module>
    from .unique import unique
  File "/opt/conda/lib/python3.6/site-packages/torch_unique/unique.py", line 5, in <module>
    import unique_cuda
ModuleNotFoundError: No module named 'unique_cuda'
```

Do you know where the issue could be?

Thanks!

**Comment by rusty1s** [comment]
There must have been an error in the installation process of `torch-unique` which was not caught by pip. Please do me a favor and clone `torch-unique` and manually run `python setup.py install`and `python setup.py test`.

**Comment by asnt** [comment]
FWIW, I encountered the same issue because the discrete GPU of the laptop was switched off during the installation of the dependencies. Switching on the GPU before installing the deps fixed the issue.
(Probably due to the check for available GPU's in the build file https://github.com/rusty1s/pytorch_unique/blob/4506d0c32849983162c234af62183931afa71e1d/setup.py#L14)

**Comment by gcucurull** [comment]
Ok, that must be it, I was using Docker and when building the Docker image, the GPU was not available.
Thanks @asnt and @rusty1s

**Comment by fuxianh** [comment]
I have the same error on pytorch (version=1.0.0), but I cannot pip install torch-unique, seems something wrong with cuda.

give following errors:
cuda/unique_kernel.cu(22): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists

cuda/unique_kernel.cu(22): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
argument types are: (int64_t)
