### ISSUE TITLE
examples/qm9_nn_conv.py   ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by qslim** [rusty1s/pytorch_geometric#801]
## To Reproduce

python examples/qm9_nn_conv.py

Using a pre-processed version of the dataset. Please install `rdkit` to alternatively process the raw data.
Traceback (most recent call last):
  File "/home/ymq/github-private/pyg/pytorch_geometric/examples/qm9_nn_conv.py", line 52, in <module>
    dataset = QM9(path, transform=transform).shuffle()
  File "/home/ymq/github-private/pyg/pytorch_geometric/torch_geometric/datasets/qm9.py", line 94, in __init__
    super(QM9, self).__init__(root, transform, pre_transform, pre_filter)
  File "/home/ymq/github-private/pyg/pytorch_geometric/torch_geometric/data/in_memory_dataset.py", line 52, in __init__
    pre_filter)
  File "/home/ymq/github-private/pyg/pytorch_geometric/torch_geometric/data/dataset.py", line 102, in __init__
    self._process()
  File "/home/ymq/github-private/pyg/pytorch_geometric/torch_geometric/data/dataset.py", line 154, in _process
    self.process()
  File "/home/ymq/github-private/pyg/pytorch_geometric/torch_geometric/datasets/qm9.py", line 116, in process
    self.data, self.slices = torch.load(self.raw_paths[0])
ValueError: too many values to unpack (expected 2)

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
I can not reproduce this, so I guess there went something wrong in the processing pipeline. Can you try to remove the `/raw` and `/processed` directories and run again?

**Comment by qslim** [comment]
Thx, I try it.
