### ISSUE TITLE
How to solve the problem that one sample contains two graph inputs

### ISSUE THREAD

**Issue by 595693085** [rusty1s/pytorch_geometric#807]
## ❓ Questions & Help

Hi,
Now I come across an application of GCN. The data set is similar to the following:
[（x_1,y_1,label_1）,(x_2,y_2,label_2)...(x_n,y_n,label_n)]
This is a very common problem. One sample contains multiple graphs, that is, the multiple graphs inputs correspond to one label.
The attributes _edge_index_ and _x_ of **torch gemetric.data** can only store one graph, but not the second. If I add the information of the second graph as attributes to the data, I will get a dim mismatch error in collate.
I have searched the issues, and there is a very similar one,   #781 . According to the answer, I have constructed a similar custom dataset, which is used to return data of two graphs one-to-one, but an error is reported in dataloader:
Traceback (most recent call last):
  File "training_validation.py", line 100, in <module>
    collate_fn=collate)
  File "/home/administrator/.conda/envs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/administrator/.conda/envs/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 92, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/home/administrator/.conda/envs/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 100, in num_samples
    return len(self.data_source)
  File "/home/administrator/.conda/envs/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 63, in __len__
    return self.slices[list(self.slices.keys())[0]].size(0) - 1
AttributeError: 'NoneType' object has no attribute 'keys

This error will only appear when shuffle = True. And shuffle = False will pass safely, but it will affect performance. I guess this error should be related to the **data, slices = self.collate (data list)**, but I don't know how to set the collate for two graphs. There are two options I have tried:
Option 1

data1, slices1 = self.collate(data_list1)
data2, slices2 = self.collate(data_list2)

But I don't know what to do next.

Option 2

data_list=[(data_x1,data_y1),(data_x2,data_y2)...]
data, slices = self.collate(data_list)

where, data_xi and data_yi refer to two input graphs (torch gemetric.data) in each sample. But there are still many errors.

So now, I don't know how to deal with the situation that the multiple graphs inputs correspond to one label. Is there a more concise implementation scheme in PyG? Or how to handle the error of shuffle = True of dataloader.

Thanks~

**Comment by 595693085** [comment]
Sorry, I found my mistake. When this function is added to the dataset, it is solved.

def __len__(self):
      return len(self.data[0])
