### ISSUE TITLE
NeighborSampler for graph-level output

### ISSUE THREAD

**Issue by pulimeng** [rusty1s/pytorch_geometric#815]
## ❓ Questions & Help

Hello and thanks for the wonderful tool you provided.
I'm trying to use the NeighborSampler for the graph-level output. It seems like the NeighborSampler works on batch of nodes instead of batch of graphs. So I just changed the `batch_size` in NeighborSampler to `len(data.batch)`. It works fine. I'm just wondering if this is the right way to do it and is there any other more elegant way to do this. Below is a simple piece of code I used to test it.
```
dl = DataLoader(data, shuffle=True,batch_size=2)

class Net(torch.nn.Module):
        def __init__(self):
                super(Net, self).__init__()
                self.conv1 = SAGEConv(4, 16)
                self.conv2 = SAGEConv(16,16)
                self.conv3 = SAGEConv(16,16)

        def forward(self, data, data_flow):
                x = data.x
                block = data_flow[0]
                x = x[block.n_id]
                x = F.relu(self.conv1((x, None), block.edge_index, size=block.size))
                block = data_flow[1]
                x = self.conv2((x, None), block.edge_index, size=block.size)
                block = data_flow[2]
                x = self.conv3((x, None), block.edge_index, size=block.size)
                x = global_max_pool(x,data.batch)
                return x


model = Net()
model.to(device)
print(model)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
for i, data in enumerate(dl):
        print(i)
        print(data)
        sampl_loader = NeighborSampler(data, size=[0.5, 0.5, 0.5], shuffle=True, num_hops=3, batch_size=len(data.batch))
        optimizer.zero_grad()
        out = model(data.to(device), next(sampl_loader()).to(device))
        print(out)
#       break

```

Thanks!

**Comment by pulimeng** [comment]
I think I've figured out how the sampler works. However, there is a weird error. My objective is to randomly generate a subgraph for each input graph using the sampler. The generated subgraph will be used for training. The following is the code for this.
```
data = d[0:100]
dl = DataLoader(data, shuffle=False,batch_size=7)

class Net(torch.nn.Module):
        def __init__(self):
                super(Net, self).__init__()
                self.conv1 = SAGEConv(4, 16)
                self.pool1 = SAGPooling(16,0.5)
                self.conv2 = SAGEConv(16,16)
                self.pool2 = SAGPooling(16,0.5)
                self.conv3 = SAGEConv(16,16)

        def forward(self, data, subdata):
                batch = data.batch
                edge_index, sub_batch = subdata.edge_index, subdata.b_id
                x = data.x[sub_batch]
                x = F.relu(self.conv1(x, edge_index, edge_weight=None))
                x, edge_index, _, batch, perm, score = self.pool1(x, edge_index, None, batch[sub_batch])
                x = self.conv2(x, edge_index, edge_weight=None)
                x, edge_index, _, batch, perm, score = self.pool2(x, edge_index, None, batch)
                x = self.conv3(x, edge_index, edge_weight=None)
                x = global_max_pool(x, batch)
                return x
odel = Net()
model.to(device)
print(model)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
for i, data in enumerate(dl):
        sampled_loader = NeighborSampler(data, size=[0.3,0.3,0.3], shuffle=True, num_hops=3, batch_size=len(data.batch), bipartite=False)
        sampled = next(sampled_loader())
        optimizer.zero_grad()
        out = model(data.to(device), sampled.to(device))
```
It works perfectly fine for batch_size (the DataLoader batch size not the sampler) less than 8. When the batch size goes to 8. I got the following error.
```
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/worka/project/michal/packages/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [172,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    out = model(data.to(device), sampled.to(device))
  File "/project/michal/packages/acd3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "test.py", line 36, in forward
    x, edge_index, _, batch, perm, score = self.pool1(x, edge_index, None, batch[sub_batch])
  File "/project/michal/packages/acd3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/michal/packages/acd3/lib/python3.7/site-packages/torch_geometric/nn/pool/sag_pool.py", line 103, in forward
    num_nodes=score.size(0))
  File "/project/michal/packages/acd3/lib/python3.7/site-packages/torch_geometric/nn/pool/topk_pool.py", line 59, in filter_adj
    row, col = row[mask], col[mask]
RuntimeError: copy_if failed to synchronize: device-side assert triggered
```
Any idea what is wrong?

**Comment by rusty1s** [comment]
Can you run your example with `CUDA_LAUNCH_BLOCKING=1` to see exactly where the error occurs?

**Comment by pulimeng** [comment]
I think it's something wrong with the shuffle in the NeighborSampler. I changed it to False and it just runs without any problem.
