### ISSUE TITLE
Can I install pytorch_geometric without CUDA? If yes, how？

### ISSUE THREAD

**Issue by sain** [rusty1s/pytorch_geometric#837]
## Environment

* OS: Centos
* Python version: 3.5
* PyTorch version: 1.2.0 without cuda
* CUDA/cuDNN version: None
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by sain** [comment]
Can I install pytorch_geometric without CUDA? If yes, how？

**Comment by rusty1s** [comment]
If you have no GPU, all GPU related installations will be skipped. So simply installing PyG should be sufficient. Does this not work for you?

**Comment by StephDocTUM** [comment]
I have the same problem, since I am using a MBP 2019 with a AMD Radeon Pro 5500M 4 GB/
Intel UHD Graphics 630 1536 MB which does not support CUDA.
@rusty1s do you mean with PyG=pytorch geometric? but this needs CUDA?

Best,
Steph

**Comment by rusty1s** [comment]
For macOS without NVIDIA card, you need to install the CPU version of PyG(=PyTorch Geometric), following the installation guide (either via `conda` or `pip`). Let me know if this works for you.

**Comment by nastaranmarzban** [comment]
hi, hope you're doing well, unfortunately my system can't support cuda, how can i install pyg in my system?please help me if anyone know, i really need it.......of course i can use colab, but as you know it has a limitation for using cuda, so i have to install pyg without  cuda

**Comment by rusty1s** [comment]
You can install the `CPU` wheels from https://data.pyg.org/whl`, e.g.:
```
pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
```

**Comment by garymm** [comment]
The installation instructions [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) say that this should work (I selected CPU on the CUDA row):
`conda install pyg -c pyg -c conda-forge`

However when I run that command, conda wants to install `cudatoolkit`, `cudnn`, etc.
So I guess the documentation should be updated to say that CPU-only needs to use pip rather than conda?

**Comment by nastaranmarzban** [comment]
hi, thanks for your responding, i run these codes on my jupyter notebook:
!pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
!pip install torch-geometric


import numpy as np
import torch
import torch_geometric.datasets as datasets
import torch_geometric.data as data
import torch_geometric.transforms as transforms
import networkx as nx
from torch_geometric.utils.convert import to_networkx
from torch_geometric.transforms import RandomLinkSplit

but after running, i receive an error again which says:
 Could not find module 'C:\Users\ARA-SOFT\anaconda3\Lib\site-packages\torch_scatter\_scatter_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

where is my problem?

**Comment by rusty1s** [comment]
@garymm CPU `conda` installation should work when in case you already have the PyTorch `conda` package installed. Otherwise, run:
```
conda install pytorch cpuonly  pyg -c pytorch -c pyg -c conda-forge
```

@nastaranmarzban When using [`colab`](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing), you should use the `cu113` packages:
```
!pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```

**Comment by Zethson** [comment]
> @garymm CPU `conda` installation should work when in case you already have the PyTorch `conda` package installed. Otherwise, run:
> 
> ```
> conda install pytorch cpuonly pyg -c pytorch -c pyg -c conda-forge
> ```
> 
> @nastaranmarzban When using [`colab`](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing), you should use the `cu113` packages:
> 
> ```
> !pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
> !pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
> ```

Did exactly that but still run into```


>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

```

**Comment by Zethson** [comment]
> Can you share some more details? What's your PyTorch/CUDA version? In general, I think this issue suggests that you are trying to install/run a CUDA version that is not found on your machine.

This is issue https://github.com/pyg-team/pytorch_geometric/issues/4160
