### ISSUE TITLE
can not run some examples

### ISSUE THREAD

**Issue by cccecilia** [rusty1s/pytorch_geometric#850]
## To Reproduce

There are same errors in colors_topk_pool.py and triangles_sag_pool.py when i run them
Traceback (most recent call last):
  File "/home/ubuntu/pytorch_geometric/examples/colors_topk_pool.py", line 266, in <module>
    loss = train(epoch)
  File "/home/ubuntu/pytorch_geometric/examples/colors_topk_pool.py", line 243, in train
    out, attn_loss, _ = model(data)
  File "/home/ubuntu/anaconda3/envs/geo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pytorch_geometric/examples/colors_topk_pool.py", line 218, in forward
    out = global_add_pool(out, batch)
  File "/home/ubuntu/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric/nn/glob/glob.py", line 24, in global_add_pool
    return scatter_('add', x, batch, dim=0, dim_size=size)
  File "/home/ubuntu/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric/utils/scatter.py", line 34, in scatter_
    out = op(src, index, dim, None, dim_size, fill_value)
  File "/home/ubuntu/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter/add.py", line 74, in scatter_add
    src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
  File "/home/ubuntu/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter/utils/gen.py", line 44, in gen
    out = src.new_full(out_size, fill_value)
RuntimeError: Trying to create tensor with negative dimension -9223372036854775807: [-9223372036854775807, 64]

## Environment

* OS:ubuntu16.04
* Python version:3.6.2
* PyTorch version:1.1.0
* CUDA/cuDNN version:9.0, V9.0.176
* GCC version:5.4.0
* Any other relevant information:

**Comment by rusty1s** [comment]
Kind of a strange error. It seems that there are wrong indices encoded in the dataset. However, it works fine for me. Since PyG requires PyTorch >= 1.2, this might be the issue.

**Comment by bknyaz** [comment]
@cccecilia 
I just tried with PyTorch 1.2.0 and the colors_topk_pool example worked fine. 
But triangles_sag_pool didn't work (I had a different error related to the shape of attention vectors), so I opened a PR #888 to fix that.

Let me know if the error remains.
