### ISSUE TITLE
nvcc fatal: Unsupported gpu architecture 'compute_75'

### ISSUE THREAD

**Issue by bosydne** [rusty1s/pytorch_geometric#869]
## ❓ Questions & Help

when I run "pip install --verbose --no-cache-dir torch-scatter", I get a error.I hope somebody can help me.
ps:I have already install pytorch 1.3.0, and the cuda9.2.

 warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
    building 'torch_scatter.scatter_cpu' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cpu
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/PUBLIC/xyj/software/anaconda3/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared -L/PUBLIC/xyj/software/anaconda3/lib -Wl,-rpath=/PUBLIC/xyj/software/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.6/cpu/scatter.o -L/PUBLIC/xyj/software/anaconda3/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
    building 'torch_scatter.scatter_cuda' extension
    creating build/temp.linux-x86_64-3.6/cuda
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/PUBLIC/xyj/software/anaconda3/include/python3.6m -c cuda/scatter.cpp -o build/temp.linux-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    /usr/local/cuda/bin/nvcc -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/PUBLIC/xyj/software/anaconda3/include/python3.6m -c cuda/scatter_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-cihokmnz/torch-scatter
Command "/PUBLIC/xyj/software/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cihokmnz/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wkc0haf4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cihokmnz/torch-scatter/
Exception information:
Traceback (most recent call last):
  File "/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/PUBLIC/xyj/software/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/PUBLIC/xyj/software/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cihokmnz/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wkc0haf4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cihokmnz/torch-scatter/

**Comment by rusty1s** [comment]
It seems that your GPU does not support `compute_75`:
```
nvcc fatal : Unsupported gpu architecture 'compute_75'
```
I do not have a solution to your problem, but I guess you need to set them via the environment variable `TORCH_CUDA_ARCH_LIST`.

**Comment by bosydne** [comment]
@rusty1s thank you very much! I will try it.
