### ISSUE TITLE
torch_scatter.scatter_cpu issue.

### ISSUE THREAD

**Issue by parang17** [rusty1s/pytorch_geometric#952]
## Environment

* OS: Linux
* Python version: 3.6
* PyTorch version:1.4
* CUDA/cuDNN version: 9.1
* GCC version: 7.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [] I do have multiple CUDA versions on my machine.
- [x] I checked if the official extension example runs on my machine.
- [x] The offical extension example runs on my machine.

## Additional context

I have installed pytorch_geometric, but I had the following error.

Traceback (most recent call last):
  File "/home/USER/PycharmProjects/pytorch_geometric/main.py", line 8, in <module>
    from torch_geometric.data import Data
  File "/home/USER/.local/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/USER/.local/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/USER/.local/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/USER/.local/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/USER/.local/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/USER/.local/lib/python3.6/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/USER/.local/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/USER/.local/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/USER/.local/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/USER/.local/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /home/USER/.local/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_29E

**Comment by qiuhaolu** [comment]
I have the same problem.
