### ISSUE TITLE
ImportError: `fps` requires `torch-cluster`.

### ISSUE THREAD

**Issue by Jollibeee** [rusty1s/pytorch_geometric#968]
## ❓ Questions & Help

`$ python examples/pointnet2_segmentation.py `

Traceback (most recent call last):
  File "examples/pointnet2_segmentation.py", line 142, in <module>
    train()
  File "examples/pointnet2_segmentation.py", line 91, in train
    out = model(data)
  File "/home/sohee/anaconda3/envs/PyGeo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "examples/pointnet2_segmentation.py", line 63, in forward
    sa1_out = self.sa1_module(*sa0_out)
  File "/home/sohee/anaconda3/envs/PyGeo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sohee/coding/pytorch_geometric/examples/pointnet2_classification.py", line 20, in forward
    idx = fps(pos, batch, ratio=self.ratio)
  File "/home/sohee/coding/pytorch_geometric/torch_geometric/nn/pool/__init__.py", line 43, in fps
    raise ImportError('`fps` requires `torch-cluster`.')
ImportError: `fps` requires `torch-cluster`.

**Comment by rusty1s** [comment]
You need the `torch-cluster` package for this (it is now optional on master).

**Comment by Na-Z** [comment]
Hi @rusty1s, after installing torch-cluster, there is a segmentation fault when passing data (i.e., model instance) from cpu to gpu. Do u have any idea?

**Comment by rusty1s** [comment]
So `torch-cluster` does not work for you? Might be an installation problem :(

**Comment by Na-Z** [comment]
> So `torch-cluster` does not work for you? Might be an installation problem :(

Yes. I have tested the installation of torch_cluster. It shows that the fps causes segmentation fault. Could you give any suggestion on installing torch_cluster?

Thanks a lot.

**Comment by rusty1s** [comment]
Please show me the installation log to see where the error occurs :)

**Comment by Na-Z** [comment]
> Please show me the installation log to see where the error occurs :) 
Sorry for the late reply. Follows are the logs of torch_cluster installation and test.. Please do take a look. Thank you a lot!
+++++++++++++++++++++++++++Installation log+++++++++++++++++++++++++++
$ pip install torch-cluster
Processing ./.cache/pip/wheels/a7/48/06/cdfb109d6a396fe9edc266ffe4d145438f2852d6a82bd1aa2d/torch_cluster-1.4.5-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: scipy in ./anaconda3/envs/env_fsseg/lib/python3.6/site-packages (from torch-cluster) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in ./anaconda3/envs/env_fsseg/lib/python3.6/site-packages (from scipy->torch-cluster) (1.18.1)
Installing collected packages: torch-cluster
Successfully installed torch-cluster-1.4.5

+++++++++++++++++++++++++++testing log+++++++++++++++++++++++++++
$ python setup.py  test
running pytest
Searching for pytest-cov
Best match: pytest-cov 2.8.1
Processing pytest_cov-2.8.1-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/pytest_cov-2.8.1-py3.6.egg
Searching for pytest
Best match: pytest 5.3.5
Processing pytest-5.3.5-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg
Searching for coverage>=4.4
Best match: coverage 5.0.3
Processing coverage-5.0.3-py3.6-linux-x86_64.egg

Using $CODE_PATH/pytorch_cluster/.eggs/coverage-5.0.3-py3.6-linux-x86_64.egg
Searching for wcwidth
Best match: wcwidth 0.1.8
Processing wcwidth-0.1.8-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/wcwidth-0.1.8-py3.6.egg
Searching for py>=1.5.0
Best match: py 1.8.1
Processing py-1.8.1-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/py-1.8.1-py3.6.egg
Searching for pluggy<1.0,>=0.12
Best match: pluggy 0.13.1
Processing pluggy-0.13.1-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg
Searching for packaging
Best match: packaging 20.1
Processing packaging-20.1-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/packaging-20.1-py3.6.egg
Searching for more-itertools>=4.0.0
Best match: more-itertools 8.2.0
Processing more_itertools-8.2.0-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/more_itertools-8.2.0-py3.6.egg
Searching for importlib-metadata>=0.12
Best match: importlib-metadata 1.5.0
Processing importlib_metadata-1.5.0-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/importlib_metadata-1.5.0-py3.6.egg
Searching for attrs>=17.4.0
Best match: attrs 19.3.0
Processing attrs-19.3.0-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/attrs-19.3.0-py3.6.egg
Searching for zipp>=0.5
Best match: zipp 3.0.0
Processing zipp-3.0.0-py3.6.egg

Using $CODE_PATH/pytorch_cluster/.eggs/zipp-3.0.0-py3.6.egg
running egg_info
writing torch_cluster.egg-info/PKG-INFO
writing dependency_links to torch_cluster.egg-info/dependency_links.txt
writing requirements to torch_cluster.egg-info/requires.txt
writing top-level names to torch_cluster.egg-info/top_level.txt
reading manifest file 'torch_cluster.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_cluster.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/torch_cluster/graclus_cpu.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/grid_cpu.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/fps_cpu.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/rw_cpu.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/sampler_cpu.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/graclus_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/grid_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/fps_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/nearest_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/knn_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/radius_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
copying build/lib.linux-x86_64-3.6/torch_cluster/rw_cuda.cpython-36m-x86_64-linux-gnu.so -> torch_cluster
=============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.6.8, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: $CODE_PATH/pytorch_cluster, inifile: setup.cfg
plugins: cov-2.8.1
collected 111 items                                                                                                                                                                                                                                                               

test/test_fps.py .Fatal Python error: Segmentation fault

Current thread 0x00007f6e10864700 (most recent call first):
  File "$CODE_PATH/pytorch_cluster/test/utils.py", line 18 in tensor
  File "$CODE_PATH/pytorch_cluster/test/test_fps.py", line 21 in test_fps
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/python.py", line 167 in pytest_pyfunc_call
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/callers.py", line 187 in _multicall
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 87 in <lambda>
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 93 in _hookexec
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/hooks.py", line 286 in __call__
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/python.py", line 1445 in runtest
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 134 in pytest_runtest_call
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/callers.py", line 187 in _multicall
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 87 in <lambda>
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 93 in _hookexec
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/hooks.py", line 286 in __call__
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 210 in <lambda>
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 237 in from_call
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 210 in call_runtest_hook
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 185 in call_and_report
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 99 in runtestprotocol
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/runner.py", line 84 in pytest_runtest_protocol
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/callers.py", line 187 in _multicall
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 87 in <lambda>
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 93 in _hookexec
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/hooks.py", line 286 in __call__
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/main.py", line 271 in pytest_runtestloop
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/callers.py", line 187 in _multicall
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 87 in <lambda>
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 93 in _hookexec
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/hooks.py", line 286 in __call__
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/main.py", line 247 in _main
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/main.py", line 197 in wrap_session
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/main.py", line 240 in pytest_cmdline_main
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/callers.py", line 187 in _multicall
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 87 in <lambda>
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/manager.py", line 93 in _hookexec
  File "$CODE_PATH/pytorch_cluster/.eggs/pluggy-0.13.1-py3.6.egg/pluggy/hooks.py", line 286 in __call__
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest-5.3.5-py3.6.egg/_pytest/config/__init__.py", line 93 in main
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest_runner-5.2-py3.6.egg/ptr.py", line 220 in run_tests
  File "$CODE_PATH/pytorch_cluster/.eggs/pytest_runner-5.2-py3.6.egg/ptr.py", line 209 in run
  File "/home/anaconda3/envs/env_fsseg/lib/python3.6/distutils/dist.py", line 974 in run_command
  File "/home/anaconda3/envs/env_fsseg/lib/python3.6/distutils/dist.py", line 955 in run_commands
  File "/home/anaconda3/envs/env_fsseg/lib/python3.6/distutils/core.py", line 148 in setup
  File "/home/anaconda3/envs/env_fsseg/lib/python3.6/site-packages/setuptools/__init__.py", line 145 in setup
  File "setup.py", line 84 in <module>
Segmentation fault (core dumped)
