### ISSUE TITLE
Windows 10 - DLL error (post-installation)

### ISSUE THREAD

**Issue by snyguy** [rusty1s/pytorch_geometric#970]
## Environment

I verified in python that my CUDA level is 10.1.

```
>>> import torch
>>> torch.version.cuda
'10.1'
```

I managed to install torch-scatter, and torch-sparse via the new pip wheels (thank you rusty1s).

```
${CUDA}='cu101'
pip install torch-scatter==latest+${CUDA} torch-sparse==latest+${CUDA} -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
```

I installed torch-geometric afterwards.

```
pip install torch-geometric
```

Testing...

```
>>> import torch
>>> import torch_geometric
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\__init__.py", line 13, in <module>
    '_version', [osp.dirname(__file__)]).origin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\__init__.py", line 22, in <module>
    raise OSError(e)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
```

It's apparently missing a DLL. I am puzzled.

It appears to be torch-sparse.

**Comment by rusty1s** [comment]
Do you have the same issues when importing torch-scatter?

**Comment by snyguy** [comment]
Similar.

```
>>> import torch_scatter
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_scatter\__init__.py", line 13, in <module>
    '_version', [osp.dirname(__file__)]).origin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_scatter\__init__.py", line 22, in <module>
    raise OSError(e)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
>>> import torch_sparse
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\__init__.py", line 13, in <module>
    '_version', [osp.dirname(__file__)]).origin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\__init__.py", line 22, in <module>
    raise OSError(e)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
```

**Comment by rusty1s** [comment]
I will look into it. Sorry!

**Comment by rusty1s** [comment]
Just to be sure, are you using PyTorch 1.4.0?

**Comment by snyguy** [comment]
1.3.1
I'll upgrade it and redo the install of torch_geometric.

**Comment by rusty1s** [comment]
That should explain the error. Please let me know if upgrading fixes the issue.

**Comment by snyguy** [comment]
That has done it! Thank you so much. Sorry for taking your time.

**Comment by snyguy** [comment]
Very excited to use this library.

**Comment by asarigun** [comment]
> That should explain the error. Please let me know if upgrading fixes the issue.
I use the 1.7.1+cu101 version but I get the same issues.
