### ISSUE TITLE
Runtime Error on Training Custom Dataset

### ISSUE THREAD

**Issue by ilteralp** [rusty1s/pytorch_geometric#982]
## ❓ Questions & Help

Hi everyone, I am trying to train a simple GNN with using my dataset. I created the dataset with following [Creating Your Own Datasets](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html) tutorial. In my case nodes with the same label are connected to each other. To create the GNN, I used [enzymes_topk_pool.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/enzymes_topk_pool.py) example. Here is the error I get, 

`RuntimeError: CUDA error: device-side assert triggered
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/rog/anaconda3/envs/py36_pytorch/lib/python3.6/site-packages/torch_scatter/scatter.py", line 39
        else:
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
              ~~~~~~~~~~~ <--- HERE
        return out.scatter_add_(dim, index, src)
    else:`

I also tried to train with `device = torch.device('cpu')`, it produces the error below, 

`RuntimeError: index out of range: Tried to access index 11 out of table with 3 rows. at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418`

Here is what I have tried,
```
import json
import torch
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.data import DataLoader
from torch_geometric.nn import GraphConv, TopKPooling
from torch_geometric.nn import global_mean_pool as gap, global_max_pool as gmp
import torch.nn.functional as F
import os.path as osp


NUM_CLASSES = 15
ROOT_PATH = "./data/"

################################ Create Dataset ################################
class GraphInputDataset(InMemoryDataset):
    def __init__(self, root, train, transform=None, pre_transform=None):
        
        super(GraphInputDataset, self).__init__(root, transform, pre_transform)
        path = self.processed_paths[0] if train else self.processed_paths[1]
        self.data, self.slices = torch.load(path)
        
    # The name of the files to find in the self.raw_dir folder in order to skip the download.
    @property
    def raw_file_names(self):
        return ['sub_{}_edges.txt'.format(file_name) for file_name in ['train', 'test']]
    
    # A list of files in the processed_dir which needs to be found in order to skip the processing.
    @property
    def processed_file_names(self):
        return ['train.pt', 'test.pt']
    
    def download(self):
        pass 
    
    def process(self):
        for split, processed_path in zip (['train', 'test'], self.processed_paths):
            node_file_path = osp.join(self.root, 'sub_{}_gcn_dataset.txt'.format(split))
            edge_file_path = osp.join(self.root, 'sub_{}_edges.txt'.format(split))
            
            # Read data into huge `Data` list.
            is_data_fetched, data_list = read_dataset(node_file_path, edge_file_path)
            if is_data_fetched:
                if self.pre_filter is not None:
                    data_list = [data for data in data_list if self.pre_filter(data)]
        
                if self.pre_transform is not None:
                    data_list = [self.pre_transform(data) for data in data_list]
                
            data, slices = self.collate(data_list)
            torch.save((data, slices), processed_path)

"""
Reads given dataset file which includes all data samples (contains test and 
train set together) and edge file which contains relations between nodes 
where two nodes are connected if they belong to the same class. Returns 
resulting graph that is undirected. 
"""
def read_dataset(node_file_path, edge_file_path):
    with open(node_file_path) as node_file: # Read node file. 
        node_data = json.load(node_file)
        with open(edge_file_path) as edge_file: # Read edge file. 
            edge_data = json.load(edge_file)
            # Check number of classes
            if len(edge_data) != NUM_CLASSES:
                print("Classes length", len(edge_data))
                return False, []
            else:
                data_list = []
                # Fetch each sample seperately
                for sample in node_data:
                    node_id = sample['nodeId']
                    features = torch.FloatTensor(sample['features']) # 1D, convert to 2d
                    features = features.view(1, features.shape[0])   # Data expects [num_nodes, num_node_features]
                    label = sample['label'] - 1                      # -1 since classes start from 1
                    raw_edges = edge_data[label][str(label+1)]       # Edges include id of node being processed, so remove it. 
                    e_from = []
                    e_to = []
                    for neighbour_id in raw_edges:
                        if neighbour_id != node_id:
                            e_from.append(node_id)
                            e_to.append(neighbour_id)
                    edge_index = torch.LongTensor([e_from, e_to])
                    data = Data(x=features, y=torch.LongTensor([label]), edge_index=edge_index)
                    data_list.append(data)
                return True, data_list
                
# Create dataset
train_dataset = GraphInputDataset(ROOT_PATH, train=True)
test_dataset = GraphInputDataset(ROOT_PATH, train=False)

# Check number of classes & features of nodes in datasets 
assert train_dataset.num_classes == test_dataset.num_classes
assert train_dataset.num_features == test_dataset.num_features

####################################### Build a GNN #######################################
# See https://github.com/rusty1s/pytorch_geometric/blob/master/examples/enzymes_topk_pool.py

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GraphConv(train_dataset.num_features, 128)
        self.pool1 = TopKPooling(128, ratio=0.8)
        self.conv2 = GraphConv(128, 128)
        self.pool2 = TopKPooling(128, ratio=0.8)
        self.conv3 = GraphConv(128, 128)
        self.pool3 = TopKPooling(128, ratio=0.8)
        
        self.lin1 = torch.nn.Linear(256, 128)
        self.lin2 = torch.nn.Linear(128, 64)
        self.lin3 = torch.nn.Linear(64, train_dataset.num_classes)
        
    def forward(self, data):
            x, edge_index, batch = data.x, data.edge_index, data.batch
            x = F.relu(self.conv1(x, edge_index))
            x, edge_index, _, batch, _, _ = self.pool1(x, edge_index, None, batch)
            x1 = torch.cat([gmp(x, batch), gap(x, batch)], dim=1)
            x = F.relu(self.conv2(x, edge_index))
            x, edge_index, _, batch, _, _ = self.pool2(x, edge_index, None, batch)
            x2 = torch.cat([gmp(x, batch), gap(x, batch)], dim=1)
            x = F.relu(self.conv3(x, edge_index))
            x, edge_index, _, batch, _, _ = self.pool3(x, edge_index, None, batch)
            x3 = torch.cat([gmp(x, batch), gap(x, batch)], dim=1)
            x = x1 + x2 + x3
            x = F.relu(self.lin1(x))
            x = F.dropout(x, p=0.5, training=self.training)
            x = F.relu(self.lin2(x))
            x = F.log_softmax(self.lin3(x), dim=-1)
    
            return x
        
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#device = torch.device('cpu')
print("device:", device)
model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)

def train(epoch):
    model.train()

    loss_all = 0
    for data in train_loader:
        data = data.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, data.y)
        loss.backward()
        loss_all += data.num_graphs * loss.item()
        optimizer.step()
    return loss_all / len(train_dataset)

def test(loader):
    model.eval()
    correct = 0
    for data in loader:
        data = data.to(device)
        pred = model(data).max(dim=1)[1]
        correct += pred.eq(data.y).sum().item()
    return correct / len(loader.dataset)

train_loader = DataLoader(train_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

for epoch in range(1, 201):
    loss = train(epoch)
    train_acc = test(train_loader)
    test_acc = test(test_loader)
    print('Epoch: {:03d}, Loss: {:.5f}, Train Acc: {:.5f}, Test Acc: {:.5f}'.
          format(epoch, loss, train_acc, test_acc))
```

Here are the files to produce the same error, 
[sub_train_gcn_dataset.txt](https://github.com/rusty1s/pytorch_geometric/files/4232265/sub_train_gcn_dataset.txt)
[sub_train_edges.txt](https://github.com/rusty1s/pytorch_geometric/files/4232266/sub_train_edges.txt)
[sub_test_gcn_dataset.txt](https://github.com/rusty1s/pytorch_geometric/files/4232267/sub_test_gcn_dataset.txt)
[sub_test_edges.txt](https://github.com/rusty1s/pytorch_geometric/files/4232268/sub_test_edges.txt)

**Comment by rusty1s** [comment]
There is an index error going on. Eventually, you have an invalid entry in `edge_index` that is larger or equal to `x.size(0)`?

**Comment by ilteralp** [comment]
I have changed the `node_id`s in `edge_index`, all `node_id`s start from 0 and their values are less than `x.size(0)`. Train and test set `node_id`'s are same now (both starting from 0 and increasing) but they are in different `Dataset` objects. Would it cause a problem ?

The other issue is setting `batch_size`. There are 3 nodes in both train and test set. If I choose `batch_size>=3` there is not any issue but if I choose `batch_size=2`, it gives the error below,

```
Traceback (most recent call last):

  File "/home/rog/code/geometric/GraphInputDataset.py", line 269, in <module>
    loss = train(epoch)

  File "/home/rog/code/geometric/GraphInputDataset.py", line 237, in train
    output = model(data)

  File "/home/rog/anaconda3/envs/py36_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/rog/code/geometric/GraphInputDataset.py", line 207, in forward
    x = F.relu(self.conv1(x, edge_index))

  File "/home/rog/anaconda3/envs/py36_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/rog/anaconda3/envs/py36_pytorch/lib/python3.6/site-packages/torch_geometric/nn/conv/graph_conv.py", line 49, in forward
    edge_weight=edge_weight)

  File "/home/rog/anaconda3/envs/py36_pytorch/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 170, in propagate
    kwargs = self.__collect__(edge_index, size, kwargs)

  File "/home/rog/anaconda3/envs/py36_pytorch/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 118, in __collect__
    out[arg] = data.index_select(self.node_dim, edge_index[idx])

RuntimeError: index out of range: Tried to access index 2 out of table with 1 rows. at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

**Comment by ilteralp** [comment]
I also tried installing PyTorch Geometric from source with `python setup.py install`. 
```
>>> import torch_geometric
>>> print(torch_geometric.__version__)
1.4.2
```

The error mentioned in the above post didn't change. Below is the error for `device = torch.device('cpu') `
```
RuntimeError: index out of range: Tried to access index 2 out of table with 1 rows. at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

Here is the error for `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')`

```
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCTensorIndex.cu:307: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCTensorIndex.cu:307: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCTensorIndex.cu:307: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCTensorIndex.cu:307: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):

  File "/home/rog/code/geometric/GraphInputDataset.py", line 269, in <module>
    loss = train(epoch)

  File "/home/rog/code/geometric/GraphInputDataset.py", line 237, in train
    output = model(data)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/rog/code/geometric/GraphInputDataset.py", line 207, in forward
    x = F.relu(self.conv1(x, edge_index))

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch_geometric-1.4.2-py3.6.egg/torch_geometric/nn/conv/graph_conv.py", line 49, in forward
    edge_weight=edge_weight)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch_geometric-1.4.2-py3.6.egg/torch_geometric/nn/conv/message_passing.py", line 173, in propagate
    out = self.aggregate(out, **aggr_kwargs)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch_geometric-1.4.2-py3.6.egg/torch_geometric/nn/conv/message_passing.py", line 202, in aggregate
    return scatter_(self.aggr, inputs, index, self.node_dim, dim_size)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch_geometric-1.4.2-py3.6.egg/torch_geometric/utils/scatter.py", line 27, in scatter_
    out = op(src, index, dim, None, dim_size)

RuntimeError: CUDA error: device-side assert triggered
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch_scatter/scatter.py", line 21
        else:
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
              ~~~~~~~~~~~ <--- HERE
        return out.scatter_add_(dim, index, src)
    else:
```

**Comment by rusty1s** [comment]
Can you give me an example of the sizes of the used tensors? There seems to be something wrong here.

**Comment by ilteralp** [comment]
Sure, here it is:

**train_dataset**

- num_classes: 14
- num_features: 2
- edge_index: torch.Size([2, 2])
- x: torch.Size([3, 2])
- y: torch.Size([3])

**test_dataset**

- num_classes: 14
- num_features: 2
- edge_index: torch.Size([2, 2])
- x: torch.Size([3, 2])
- y: torch.Size([3])

**contents, train dataset:**
```
('edge_index', tensor([[0, 1],
        [1, 0]]))
('x', tensor([[76., 21.],
        [ 9., 65.],
        [21., 13.]]))
('y', tensor([13, 13,  2]))
```
**contents, test_dataset:**
```
('edge_index', tensor([[0, 1],
        [1, 0]]))
('x', tensor([[33., 51.],
        [17., 41.],
        [21., 88.]]))
('y', tensor([ 0,  0, 13]))
```

**Comment by ilteralp** [comment]
If I create one `Data` object for  instead of a `data_list` within `process()`, this is the error I receive,
```
Traceback (most recent call last):

  File "/home/rog/code/geometric/GraphInputDataset.py", line 302, in <module>
    loss = train(epoch)

  File "/home/rog/code/geometric/GraphInputDataset.py", line 273, in train
    loss = F.nll_loss(output, data.y)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))

ValueError: Expected input batch_size (1) to match target batch_size (2).
```

Here is the method for creating `Data` object,
```
def read_dataset_one_tuple(node_file_path, edge_file_path):
    with open(node_file_path) as node_file: # Read node file. 
        node_data = json.load(node_file)
        with open(edge_file_path) as edge_file: # Read edge file. 
            edge_data = json.load(edge_file)
            # Check number of classes
            if len(edge_data) != NUM_CLASSES:
                print("Classes length", len(edge_data))
            else:
                xs = []
                ys = []
                source_edges = []
                target_edges = []
                for sample in node_data:
                    node_id = sample['nodeId']
                    xs.append(sample['features'])
                    label = sample['label'] - 1
                    ys.append(label)
                    raw_edges = edge_data[label][str(label+1)]
                    e_from = []
                    e_to = []
                    for neighbour_id in raw_edges:
                        if neighbour_id != node_id:
                            source_edges.append(node_id)
                            target_edges.append(neighbour_id)
                x = torch.from_numpy(np.array(xs)).to(torch.float)
                y = torch.from_numpy(np.array(ys)).to(torch.long)
                edge_index = torch.from_numpy(np.array([source_edges, target_edges])).to(torch.long)
                return True, Data(x=x, y=y, edge_index=edge_index)
    return False, None
```

**Comment by rusty1s** [comment]
Can you be a bit more specific and provide a minimal example to reproduce this? There seems to be a lot of information missing.

**Comment by ilteralp** [comment]
Here is the code produces above error. 

I attached the sample train and test set files, they should be placed under `data` folder. In this graph, all of the samples with the same label are connected to each other, samples with different labels are disconnected. 
[test_edges.txt](https://github.com/rusty1s/pytorch_geometric/files/4279747/test_edges.txt)
[test_gcn_dataset.txt](https://github.com/rusty1s/pytorch_geometric/files/4279748/test_gcn_dataset.txt)
[train_edges.txt](https://github.com/rusty1s/pytorch_geometric/files/4279749/train_edges.txt)
[train_gcn_dataset.txt](https://github.com/rusty1s/pytorch_geometric/files/4279750/train_gcn_dataset.txt)



```
import os.path as osp
import numpy as np
import json
import torch

from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.data import DataLoader
from torch_geometric.nn import GraphConv, TopKPooling
from torch_geometric.nn import global_mean_pool as gap, global_max_pool as gmp
import torch.nn.functional as F

# Constants
ROOT_PATH = './data'

""" ======================================== Create Dataset ======================================== """

class GraphInputDataset(InMemoryDataset):
    def __init__(self, root, train, transform=None, pre_transform=None):
        
        super(GraphInputDataset, self).__init__(root, transform, pre_transform)
        path = self.processed_paths[0] if train else self.processed_paths[1]
        self.data, self.slices = torch.load(path)
        
    # The name of the files to find in the self.raw_dir folder in order to skip the download.
    @property
    def raw_file_names(self):
        return ['{}_edges.txt'.format(file_name) for file_name in ['train', 'test']]
    
    # A list of files in the processed_dir which needs to be found in order to skip the processing.
    @property
    def processed_file_names(self):
        return ['train.pt', 'test.pt']
    
    def download(self):
        pass 
    
    """
    Gather your data into a list of Data objects. Then call self.collate() to 
    compute slices that will be used by the DataLoader object. 
    """
    def process(self):
        for split, processed_path in zip (['train', 'test'], self.processed_paths):
            node_file_path = osp.join(self.root, '{}_gcn_dataset.txt'.format(split))
            edge_file_path = osp.join(self.root, '{}_edges.txt'.format(split))
            is_data_fetched, data = read_dataset_one_tuple(node_file_path, edge_file_path)
            if is_data_fetched:
                torch.save(self.collate([data]), processed_path)
            else:
                print("Dataset cannot be read! Given", node_file_path, "and", edge_file_path)
            
"""
Reads given dataset from file into one tuple
"""
def read_dataset_one_tuple(node_file_path, edge_file_path):
    with open(node_file_path) as node_file: # Read node file. 
        node_data = json.load(node_file)
        with open(edge_file_path) as edge_file: # Read edge file. 
            edge_data = json.load(edge_file)
            xs = []
            ys = []
            source_edges = []
            target_edges = []
            for sample in node_data:
                node_id = sample['nodeId']
                xs.append(sample['features'])
                label = sample['label'] - 1
                ys.append(label)
                raw_edges = edge_data[label][str(label+1)]
                for neighbour_id in raw_edges:
                    if neighbour_id != node_id:
                        source_edges.append(node_id)
                        target_edges.append(neighbour_id)
            x = torch.from_numpy(np.array(xs)).to(torch.float)
            y = torch.from_numpy(np.array(ys)).to(torch.long)
            edge_index = torch.from_numpy(np.array([source_edges, target_edges])).to(torch.long)
            return True, Data(x=x, y=y, edge_index=edge_index)
    return False, None

# Create dataset
train_dataset = GraphInputDataset(ROOT_PATH, train=True)
test_dataset = GraphInputDataset(ROOT_PATH, train=False)

# Check number of classes & features of nodes in datasets 
assert train_dataset.num_classes == test_dataset.num_classes
assert train_dataset.num_features == test_dataset.num_features

""" ======================================== Build a GNN ======================================== """

class Net(torch.nn.Module):
    def __init__(self):
        print("network num_features:", train_dataset.num_features)
        print("network num_classes:", train_dataset.num_classes)
        super(Net, self).__init__()
        self.conv1 = GraphConv(train_dataset.num_features, 128)
        self.pool1 = TopKPooling(128, ratio=0.8)
        self.conv2 = GraphConv(128, 128)
        self.pool2 = TopKPooling(128, ratio=0.8)
        self.conv3 = GraphConv(128, 128)
        self.pool3 = TopKPooling(128, ratio=0.8)
        
        self.lin1 = torch.nn.Linear(256, 128)
        self.lin2 = torch.nn.Linear(128, 64)
        self.lin3 = torch.nn.Linear(64, train_dataset.num_classes)
        
    def forward(self, data):
            x, edge_index, batch = data.x, data.edge_index, data.batch
            x = F.relu(self.conv1(x, edge_index))
            x, edge_index, _, batch, _, _ = self.pool1(x, edge_index, None, batch)
            x1 = torch.cat([gmp(x, batch), gap(x, batch)], dim=1)
            x = F.relu(self.conv2(x, edge_index))
            x, edge_index, _, batch, _, _ = self.pool2(x, edge_index, None, batch)
            x2 = torch.cat([gmp(x, batch), gap(x, batch)], dim=1)
            x = F.relu(self.conv3(x, edge_index))
            x, edge_index, _, batch, _, _ = self.pool3(x, edge_index, None, batch)
            x3 = torch.cat([gmp(x, batch), gap(x, batch)], dim=1)
            x = x1 + x2 + x3
            x = F.relu(self.lin1(x))
            x = F.dropout(x, p=0.5, training=self.training)
            x = F.relu(self.lin2(x))
            x = F.log_softmax(self.lin3(x), dim=-1)
    
            return x
        
device = torch.device('cpu')
model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)

def train(epoch):
    model.train()

    loss_all = 0
    for data in train_loader:
        data = data.to(device)
        optimizer.zero_grad()
        output = model(data)
        print('output.size', output.size(), 'target.size', data.y.size())
        print('output', output, 'target', data.y)
        loss = F.nll_loss(output, data.y)
        loss.backward()
        loss_all += data.num_graphs * loss.item()
        optimizer.step()
    return loss_all / len(train_dataset)

def test(loader):
    model.eval()
    correct = 0
    for data in loader:
        data = data.to(device)
        pred = model(data).max(dim=1)[1]
        correct += pred.eq(data.y).sum().item()
    return correct / len(loader.dataset)

train_loader = DataLoader(train_dataset, batch_size=2)
test_loader = DataLoader(test_dataset, batch_size=2)

for epoch in range(1, 201):
    loss = train(epoch)
    train_acc = test(train_loader)
    test_acc = test(test_loader)
    print('Epoch: {:03d}, Loss: {:.5f}, Train Acc: {:.5f}, Test Acc: {:.5f}'.
          format(epoch, loss, train_acc, test_acc))
```
This is the error it produces, 

```
Traceback (most recent call last):

  File "/home/rog/code/geometric/GraphInputDataset.py", line 165, in <module>
    loss = train(epoch)

  File "/home/rog/code/geometric/GraphInputDataset.py", line 146, in train
    loss = F.nll_loss(output, data.y)

  File "/home/rog/anaconda3/envs/py36_source_pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))

ValueError: Expected input batch_size (1) to match target batch_size (4).
```
Here are the sizes of `output` and `target` which produce the above error. I am confused about this part, the network that I use is the one from [enzymes_topk_pool](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/enzymes_topk_pool.py) example and it's working properly when I test it. 
```
output.size torch.Size([1, 2]) target.size torch.Size([4])
output tensor([[-5.2386, -0.0053]], grad_fn=<LogSoftmaxBackward>) target tensor([0, 0, 1, 1])
```

**Comment by ilteralp** [comment]
This is the line giving the error,

```
F.nll_loss(output, data.y)
```

According to [nll_loss](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.nll_loss) documentation on PyTorch, these are the expected sizes,
```
torch.nn.functional.nll_loss(input, target, weight=None, size_average=None, ignore_index=-100, reduce=None, reduction='mean')
input – (N,C) where N = batch size and C = number of classes. 
target – (N)
```
I have 2 classes and `batch_size=2` in the samples I have attached to the above post. So, following the `nll_loss` documentation, correct sizes should be like this,
```
output size: torch.Size([2, 2]) # batch size, number of classes
data.y size: torch.Size([2])    # batch size
```
But I have the following sizes where the sizes of `output` and `data.y` look wrong for ` input` and `target`, respectively. 
```
output size: torch.Size([1, 2])
data.y size: torch.Size([4])
```
Please correct me if I'm wrong. I've tested with different `batch_size` values and the error did not change.  As I mentioned in the above post, I followed [enzymes_topk_pool](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/enzymes_topk_pool.py) from `examples` and it's working properly when I test it.

**Comment by rusty1s** [comment]
Are you sure that your data is correctly processed?
Does `dataset[0]` only hold one label in `dataset[0].y`?

**Comment by ilteralp** [comment]
> Are you sure that your data is correctly processed?

Since creating a `data_list` did not work for me (first post in the thread), I followed [Reddit dataset](https://github.com/rusty1s/pytorch_geometric/tree/master/torch_geometric/datasets/reddit.py) example to create custom dataset where one `Data` object is used instead of a `data_list`. 

> Does `dataset[0]` only hold one label in `dataset[0].y`?

There is a label for each node in the dataset, here is the output,
```
print('train_dataset[0]:', train_dataset[0])
train_dataset[0]: Data(edge_index=[2, 4], x=[4, 2], y=[4])

print("y:", train_dataset[0].y)
y: tensor([0, 0, 1, 1])
```
Does this network expect graph-wise labeling ?

**Comment by rusty1s** [comment]
No it does not, but you are training against graph-wise labeling.

**Comment by ilteralp** [comment]
How can I train it for node labels ? If this is not the correct architecture for this purpose, any other network also would be fine.

**Comment by rusty1s** [comment]
Well you can look up examples that are suitable for node classification (examples that do not make use of `global_pooling` or `pooling` operators), *.e.g.*, `gcn.py` or `ppi.py`.

**Comment by ilteralp** [comment]
Thanks a lot for your patience and great work, I'll give them a try.
