### ISSUE TITLE
DataLoader or DataListLoader with DistributedDataParallel

### ISSUE THREAD

**Issue by jinserk** [rusty1s/pytorch_geometric#985]
## ❓ Questions & Help

Hi,
first of all, thank you for this great packages for graph based ML!
I'd like to test QM9 dataset with very simple 2-layered GCN, however, I've stucked how to make the dataset and corresponding dataloader work with PyTorch's DistributedDataParallel. Of course I know there is its own DataParallel module but I prefer to use DistributedDataParallel instead since its much flexible not only for a single node with multiple GPUs but also for multiple nodes with multiple GPUs.

When I use QM9 with DataListLoader with DistributedDataParallel, I've got an error like:
```
Traceback (most recent call last):
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jinserk/kyu/pyg/train.py", line 184, in run
    train_loss_per_target, ave_train_loss = self.train(epoch)
  File "/home/jinserk/kyu/pyg/train.py", line 269, in train
    for i, data in enumerate(self.train_loader):
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/jinserk/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DataLoader.__init__.<locals>.<lambda>'
```

**Comment by akihironitta** [comment]
I haven't had a chance to try `DataListLoader`, but for anyone seeing errors saying some objects are unpicklable, one alternative is to switch the start method from `spawn` (that requires picklability of objects) to `fork` (https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) although you also need to make sure your script doesn't create cuda context before forking the process.
