### ISSUE TITLE
Dataloader throwing TypeError 

### ISSUE THREAD

**Issue by 1byxero** [rusty1s/pytorch_geometric#996]
## ❓ Questions & Help

Using Skeleton from [this colab notbook](https://colab.research.google.com/drive/1DIQm9rOx2mT1bZETEeVUThxcrP1RKqAn#scrollTo=IS1dPinuyPCy) I am trying to implement a GCN for custom data set.

I used [this reference](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#data-handling-of-graphs) to create the data object as follows.

```
startpt = []
endpt = []

with open("Graph.txt", "r") as f:
    ct = 0
    for line in f.readlines():
        a,b,c = line.strip().split()
        startpt.append(int(a))
        endpt.append(int(b))
        ct+=1
    print(ct)
print(len(startpt), len(endpt))
labels = []
with open("label.txt", "r") as f:
    for l in f.readlines():
        labels.append(int(l.strip().split()[1]))
from torch_geometric.data import Data
edges = torch.tensor([startpt, endpt], dtype=torch.long)
x = torch.tensor([[1]]*len(labels), dtype=torch.float)
y = torch.tensor(labels, dtype=torch.int)
data2 = Data(x=x, edge_index=edges, y=y)
```

Now, when i create a data loader object to train the network it throws following error.
I double checked everything but I couldn't find anything that is being passed as string in there.
What could be going wrong?

```
TypeError                                 Traceback (most recent call last)
<ipython-input-167-0f6157c8bf31> in <module>
      2 # model = train(data2, task, writer)
      3 l = DataLoader(data2)
----> 4 [i for i in l.__iter__()]

<ipython-input-167-0f6157c8bf31> in <listcomp>(.0)
      2 # model = train(data2, task, writer)
      3 l = DataLoader(data2)
----> 4 [i for i in l.__iter__()]

~/virtualenv-forest/gcn/lib/python3.5/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/virtualenv-forest/gcn/lib/python3.5/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    383     def _next_data(self):
    384         index = self._next_index()  # may raise StopIteration
--> 385         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    386         if self._pin_memory:
    387             data = _utils.pin_memory.pin_memory(data)

~/virtualenv-forest/gcn/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/virtualenv-forest/gcn/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/virtualenv-forest/gcn/lib/python3.5/site-packages/torch_geometric/data/data.py in __getitem__(self, key)
     90     def __getitem__(self, key):
     91         r"""Gets the data of the attribute :obj:`key`."""
---> 92         return getattr(self, key, None)
     93 
     94     def __setitem__(self, key, value):

TypeError: getattr(): attribute name must be string
```

Contents of "Graph.txt" files are as follows
`node1 node2 edge_weight`
Contents of "labels.txt" are
`node1 label`

**Comment by rusty1s** [comment]
You can only pass a list of data objects to the `DataLoader`, not a single list. If you want to perform mini-batching on a single graph, have a look at the `NeighborSampler` (example `reddit.py`) and `ClusterGCN` (currently only supported on master).

**Comment by 1byxero** [comment]
Thanks!
I tried updating to torch-geometric-1.4.1 to make cluster gcn work.
However, nothing was working on that version.
Everything started throwing error, even imports.
Following is the traceback

```

 In [1]: import torch_geometric                                                                                                                                                                 
 Traceback (most recent call last):
 
   File "/home/anuj/virtualenv-forest/gcn/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
     exec(code_obj, self.user_global_ns, self.user_ns)
 
   File "<ipython-input-1-c36e13293883>", line 1, in <module>
     import torch_geometric
 
 
   File "/home/anuj/virtualenv-forest/gcn/lib/python3.5/site-packages/torch_geometric/__init__.py", line 2, in <module>
     import torch_geometric.nn
 
   File "/home/anuj/virtualenv-forest/gcn/lib/python3.5/site-packages/torch_geometric/nn/__init__.py", line 4, in <module>
     from .conv import *  # noqa
 
   File "/home/anuj/virtualenv-forest/gcn/lib/python3.5/site-packages/torch_geometric/nn/conv/__init__.py", line 1, in <module>
     from .message_passing import MessagePassing
 
   File "/home/anuj/virtualenv-forest/gcn/lib/python3.5/site-packages/torch_geometric/nn/conv/message_passing.py", line 88
     (f'Encountered node tensor with size '
                                          ^
 SyntaxError: invalid syntax
```

**Comment by rusty1s** [comment]
Oh, you are using Python 3.5. Formatted strings are only supported from Python 3.6, so this throws an error for you. BTW, `Cluster-GCN` is only available on PyG master.

**Comment by 1byxero** [comment]
When you say `Cluster-GCN is only available on PyG master.`

You mean, if i am to use it, i will need to install by cloning the repo and installing it from that source?

**Comment by rusty1s** [comment]
Yes! But this should be really easy. Simply run: `python setup.py install` inside the repo.

**Comment by 1byxero** [comment]
Will installing it break anything else?

**Comment by rusty1s** [comment]
Not that I am aware of :D

**Comment by 1byxero** [comment]
Thanks,
Is `res_n_id` parameter of forward function for `SAGEConv` also available only on PyG Master?

**Comment by rusty1s** [comment]
Yes.

**Comment by 1byxero** [comment]
I've gotten things working by installing from source!
I'll close this issue now
Thanks for all the help
I may try contributing by writing some documentation/tutorials.
